### ISSUE TITLE
KeyError prints `(null)` in the dictionary

### ISSUE THREAD

**Issue by Thirumalai-Shaktivel** [lcompilers/lpython#1208]
This is a bug in LPython. This file:
```
from ltypes import i32

def test_dictionary():
    x: dict[i32, str]
    x = {1: "one", 2: "two"}
    print(x[10])

test_dictionary()
```
gives for me:
```console
$ lpython a.py -o a       
$ ./a
(null)
$ PYTHONPATH=src/runtime/ltypes  python a.py
Traceback (most recent call last):
  File "/Users/ondrej/repos/lpython/a.py", line 8, in <module>
    test_dictionary()
  File "/Users/ondrej/repos/lpython/a.py", line 6, in test_dictionary
    print(x[10])
KeyError: 10
```
So the runtime bounds check does not work in this case. So we have to debug this and fix it.

_Originally posted by @certik in https://github.com/lcompilers/lpython/issues/1180#issuecomment-1276494243_

**Comment by Thirumalai-Shaktivel** [comment]
This throws an error message:
```console
$ lpython a.py
KeyError: The dict does not contain the specified key
```
