### ISSUE TITLE
The @packed does not work in pure Python mode

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#1433]
One must use the following technique for packed structures:
```diff
--- a/src/runtime/ltypes/ltypes.py
+++ b/src/runtime/ltypes/ltypes.py
@@ -275,6 +275,7 @@ def convert_to_ctypes_Structure(f):
         fields.append((name, convert_type_to_ctype(ltype_)))
 
     class ctypes_Structure(ctypes.Structure):
+        _pack_ = 1
         _fields_ = fields
 
     ctypes_Structure.__name__ = f.__name__
```
Obviously this would then fail for non-packed structures. 

I have a large example where this is needed, so there is definitely a bug. We need to create a simple example that fails at the CI, and then fix it. The `_pack_` attribute must be set according to the presence of the `@packed` decorator.

**Comment by certik** [comment]
Something like the following should exercise the issue:
```diff
diff --git a/integration_tests/structs_18.py b/integration_tests/structs_18.py
index 45ba10d1b..a28ba1fdf 100644
--- a/integration_tests/structs_18.py
+++ b/integration_tests/structs_18.py
@@ -5,6 +5,7 @@ from copy import deepcopy
 @packed
 @dataclass
 class buffer_struct:
+    tmp: i8
     buffer8: i8[32]
     buffer1: i32[32]
     buffer2: f32[32]
@@ -18,6 +19,7 @@ class buffer_struct:
 @packed
 @dataclass
 class buffer_struct_clink:
+    tmp: i8
     buffer8: i8[32]
     buffer1: i32[32]
     buffer2: f32[32]
diff --git a/integration_tests/structs_18b.c b/integration_tests/structs_18b.c
index fb24bd593..9a8cb93d8 100644
--- a/integration_tests/structs_18b.c
+++ b/integration_tests/structs_18b.c
@@ -10,6 +10,7 @@ int16_t sum_buffer_i16(int16_t data[], int32_t size) {
 }
 
 struct __attribute__((packed)) buffer_c {
+    int8_t tmp;
     int8_t buffer8[32];
     int32_t buffer1[32];
     float buffer2[32];
```
But then I found out that this test does not run in cpython, since this:
```diff
--- a/integration_tests/CMakeLists.txt
+++ b/integration_tests/CMakeLists.txt
@@ -367,7 +367,7 @@ RUN(NAME structs_14          LABELS cpython llvm c)
 RUN(NAME structs_15          LABELS cpython llvm c)
 RUN(NAME structs_16          LABELS cpython llvm c)
 RUN(NAME structs_17          LABELS cpython llvm c)
-RUN(NAME structs_18          LABELS llvm c
+RUN(NAME structs_18          LABELS cpython llvm c
     EXTRAFILES structs_18b.c)
 RUN(NAME sizeof_01           LABELS llvm c
         EXTRAFILES sizeof_01b.c)
```
fails with:
```
Traceback (most recent call last):
  File "/Users/ondrej/repos/lpython/integration_tests/structs_18.py", line 112, in <module>
    f()
  File "/Users/ondrej/repos/lpython/integration_tests/structs_18.py", line 50, in f
    buffer_: buffer_struct = buffer_struct(deepcopy(buffer8_var), deepcopy(buffer1_var),
TypeError: buffer_struct.__init__() missing 1 required positional argument: 'buffer7'

```


So there are several bugs to fix here:

* [ ] get CPython integration tests running for C interop of structs
* [ ] add a test for both packed and non-packed (ensure the packed one fails, but non-packed succeed, and ensure that `_pack_=1` makes the packed one succeed and non-packed to fail)
* [ ] Make both tests pass by inferring `_pack_` based on the `@packed` decorator

**Comment by certik** [comment]
The following segfaults, with or without `_pack_`:
```diff
diff --git a/integration_tests/CMakeLists.txt b/integration_tests/CMakeLists.txt
index a322f10b8..23eb70b71 100644
--- a/integration_tests/CMakeLists.txt
+++ b/integration_tests/CMakeLists.txt
@@ -367,7 +367,7 @@ RUN(NAME structs_14          LABELS cpython llvm c)
 RUN(NAME structs_15          LABELS cpython llvm c)
 RUN(NAME structs_16          LABELS cpython llvm c)
 RUN(NAME structs_17          LABELS cpython llvm c)
-RUN(NAME structs_18          LABELS llvm c
+RUN(NAME structs_18          LABELS cpython llvm c
     EXTRAFILES structs_18b.c)
 RUN(NAME sizeof_01           LABELS llvm c
         EXTRAFILES sizeof_01b.c)
diff --git a/src/runtime/ltypes/ltypes.py b/src/runtime/ltypes/ltypes.py
index 815cbd3be..c0eb92b3d 100644
--- a/src/runtime/ltypes/ltypes.py
+++ b/src/runtime/ltypes/ltypes.py
@@ -275,6 +275,7 @@ def convert_to_ctypes_Structure(f):
         fields.append((name, convert_type_to_ctype(ltype_)))
 
     class ctypes_Structure(ctypes.Structure):
+        _pack_ = 1
         _fields_ = fields
 
     ctypes_Structure.__name__ = f.__name__
```
So this should be fixed first.

**Comment by certik** [comment]
It looks like the `_pack_=1` feature is rather equal to:
```diff
--- a/integration_tests/structs_18b.c
+++ b/integration_tests/structs_18b.c
@@ -9,7 +9,7 @@ int16_t sum_buffer_i16(int16_t data[], int32_t size) {
     return sum_buffer;
 }
 
-struct __attribute__((packed)) buffer_c {
+struct __attribute__((packed)) __attribute__((ms_struct)) buffer_c {
     int8_t buffer8[32];
     int32_t buffer1[32];
     float buffer2[32];
```
Per the comment here: https://github.com/python/cpython/pull/97702/files#r990785728

**Comment by certik** [comment]
The issue seems to be to create the struct in C, not in CPython, that's another bug.

We actually need to access the struct created in C. Here is a simple test that works for me:

https://github.com/lcompilers/lpython/pull/1435

and that will fail if `_pack_` is removed. This test should be done both with pack and unpack.

**Comment by czgdp1807** [comment]
So I did my investigation and here are my conclusions,

1. The underlying issue is not related to `@packed` at all. For structs without `@packed` decorator we face the same problem.
2. If you want to modify the struct in C then it should be defined, allocated and written to in C. Python should deal with it as a `CPtr`. The reason is there is a difference in how structs are treated by ctypes and C. So inter-operating structs defined via ctypes.Structure and C would be very fragile.

Here is a simple test,

**structs_19.py**

```python
from ltypes import i8, dataclass, i32, f32, f64, i16, i64, ccallable, ccall, CPtr, p_c_pointer, empty_c_void_p, pointer, sizeof

@ccallable
@dataclass
class buffer_struct_clink:
    buffer8: i8
    buffer1: i32
    buffer2: f32
    buffer4: f64
    buffer5: i16
    buffer6: i64

@ccall
def fill_buffer(ptr: CPtr):
    pass

def f():
    buffer_clink_: buffer_struct_clink = buffer_struct_clink()
    buffer_clink_cptr: CPtr = empty_c_void_p()

    p_c_pointer(pointer(buffer_clink_), buffer_clink_cptr)
    print("Python.buffer_clink_cptr: ", buffer_clink_cptr)
    print("Python.sizeof: ", sizeof(buffer_struct_clink))
    print("Python.buffer_clink_->buffer8: ", id(buffer_clink_.buffer8))
    fill_buffer(buffer_clink_cptr)
    print("Python.buffer_clink_->buffer8.value: ", buffer_clink_.buffer8)

f()
```

**structs_19b.h**

```c
#include <inttypes.h>

void fill_buffer(void* pointer);
```

**structs_19b.c**

```c
#include "structs_19b.h"
#include <stdio.h>

struct buffer_c {
    int8_t buffer8;
    int32_t buffer1;
    float buffer2;
    double buffer4;
    int16_t buffer5;
    int64_t buffer6;
};

void fill_buffer(void* pointer) {
    printf("C.pointer: %lld\n", pointer);
    struct buffer_c* buffer_clink_ = (struct buffer_c*) pointer;
    printf("C.sizeof: %d\n", sizeof(struct buffer_c));
    printf("C.buffer_clink_: %lld\n", buffer_clink_);
    printf("C.buffer_clink_->buffer8: %lld\n", &(buffer_clink_->buffer8));
    buffer_clink_->buffer8 = 2;
}
```

LPython diff applied over 23311c7419c13086b4693912b57,

```diff
diff --git a/integration_tests/CMakeLists.txt b/integration_tests/CMakeLists.txt
index a322f10b8..0592a8339 100644
--- a/integration_tests/CMakeLists.txt
+++ b/integration_tests/CMakeLists.txt
@@ -369,6 +369,8 @@ RUN(NAME structs_16          LABELS cpython llvm c)
 RUN(NAME structs_17          LABELS cpython llvm c)
 RUN(NAME structs_18          LABELS llvm c
     EXTRAFILES structs_18b.c)
+RUN(NAME structs_19          LABELS cpython llvm c
+    EXTRAFILES structs_19b.c)
 RUN(NAME sizeof_01           LABELS llvm c
         EXTRAFILES sizeof_01b.c)
 RUN(NAME enum_01             LABELS cpython llvm c)
diff --git a/src/runtime/ltypes/ltypes.py b/src/runtime/ltypes/ltypes.py
index 815cbd3be..83eafc5a7 100644
--- a/src/runtime/ltypes/ltypes.py
+++ b/src/runtime/ltypes/ltypes.py
@@ -179,6 +179,8 @@ def convert_type_to_ctype(arg):
         return ctypes.POINTER(type)
     elif is_dataclass(arg):
         return convert_to_ctypes_Structure(arg)
+    elif issubclass(arg, ctypes.Structure):
+        return arg
     else:
         raise NotImplementedError("Type %r not implemented" % arg)
 
@@ -317,6 +319,8 @@ def pointer(x, type_=None):
                     ctypes.c_void_p)
         elif is_dataclass(type_):
             return x
+        elif issubclass(type_, ctypes.Structure):
+            return x
         else:
             raise Exception("Type not supported in pointer()")
 
@@ -344,6 +348,8 @@ def c_p_pointer(cptr, targettype):
 def p_c_pointer(ptr, cptr):
     if isinstance(ptr, ctypes.c_void_p):
         cptr.value = ptr.value
+    elif isinstance(ptr, ctypes.Structure):
+        cptr.value = id(ptr)
     else:
         # assign the address of ptr in memory to cptr.value
         # the case for numpy arrays converted to a pointer
@@ -356,4 +362,6 @@ def sizeof(arg):
     return ctypes.sizeof(convert_type_to_ctype(arg))
 
 def ccallable(f):
+    if is_dataclass(f):
+        return convert_to_ctypes_Structure(f)
     return f
```

**Output**

```bash
133: Python.buffer_clink_cptr:  c_void_p(4374538944)
133: Python.sizeof:  40
133: Python.buffer_clink_->buffer8:  4371398864
133: Python.buffer_clink_->buffer8.value:  0
133: C.pointer: 4374538944
133: C.sizeof: 40
133: C.buffer_clink_: 4374538944
133: C.buffer_clink_->buffer8: 4374538944
```

So you can see, size of structs defined in `.py` file and `.c` is same. The address sent to C from Python is also correct. However, the address of `buffer8` differs in Python and C. In fact the line, `buffer_clink_->buffer8 = 2` doesn't have any affect and the Python output for `buffer_clink_.buffer8` is `0`, which makes sense because the address of `buffer8` is different in Python and C. So C is writing somewhere else and Python is reading from somewhere else. In fact, the segmentation faults which I and @certik got are because of the same reason. C tries to write to a memory location which is not owned by the process and we get segmentation fault.

**Comment by certik** [comment]
There are two issues here:
* [ ] creating the struct in C and accessing from Python (high priority)
* [ ] creating the struct in Python and accessing from C (low priority)

Let's just fix the high priority issue.
