### ISSUE TITLE
Returning garbage value instead of Error on referencing variable before assignment ?

### ISSUE THREAD

**Issue by faze-geek** [lcompilers/lpython#1452]
I recently came across this behavior and was curious if this is intended?

```
i: str
j: i32
print(i)
print(j)

C:\Users\kunni\lpython>python try.py
Traceback (most recent call last):
  File "try.py", line 10, in <module>
    f()
  File "try.py", line 6, in f
    print(i)
UnboundLocalError: local variable 'i' referenced before assignment

C:\Users\kunni\lpython>src\bin\lpython try.py
   Creating library try.lib and object try.exp
(null)
0       # Sometimes gives garbage value here but generally 0.
```

Wouldn't this be problematic if user forgets assignment at some point in the code (and no error shows on compilation). Just an eg...... on user experience this code which should instantly give an error lands up printing loads of garbage values !?

```
i: i32
j: i32
for i in range(1,1000000000):
        print(j)
```

**Comment by certik** [comment]
Yes, we need to handle this somehow, as indeed this breaks the "contract" that it runs in LPython, but doesn't run in CPython.

**Comment by czgdp1807** [comment]
We just need to track whether a variable was assigned at the time it was used in a statement. This can be happen in either of the following ways,

1. The variable was initialised at declaration.
2. The variable was assigned via an assignment statement. 

In an expression/statement, check if all variables in it were assigned at some point earlier. 

I think it should be possible to turn off these kinds of checks via a compiler option because they tend to slow down overall compilation.
