### ISSUE TITLE
WAT: Bug in WASM Decoding

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lcompilers/lpython#1453]
**Example:**
```python
def main0():
    print("01234567891") # string of length 11
    print("hi")

main0()
```
**Output:**
```bash
(lp) lpython$ lpython examples/expr2.py --show-wat                                        
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ubaid/Desktop/OpenSource/lpython/src/bin/lpython.cpp", line 1609
    return emit_wat(arg_file, runtime_library_dir, compiler_options);
  File "/Users/ubaid/Desktop/OpenSource/lpython/src/bin/lpython.cpp", line 351
    LCompilers::Result<std::string> res = LCompilers::wasm_to_wat(r2.result, al, diagnostics);
  File "/Users/ubaid/Desktop/OpenSource/lpython/src/libasr/codegen/wasm_to_wat.cpp", line 392
    std::string wat;
  File "../libasr/codegen/wasm_decoder.h", line 312
  File "../libasr/codegen/wasm_decoder.h", line 273
  File "/Users/ubaid/Desktop/OpenSource/lpython/src/libasr/codegen/wasm_utils.cpp", line 76
    LCOMPILERS_ASSERT(offset < code.size());
AssertFailed: offset < code.size()
(lp) lpython$ 
```

**Comment by Shaikh-Ubaid** [comment]
**PS:** The above example at https://github.com/lcompilers/lpython/issues/1453#issue-1553212840 is a (simplified and) specialized example formed after investigating the issue. The original example over which this bug was discovered is

```bash
(lp) lpython$ cat examples/expr2.py 
def comp():
   print("x < y")
   print("x !< y")
   print("x > y")
   print("x !> y")
   print("x == y")
   print("x != y")


def main0():
   comp()

main0()
(lp) lpython$ lpython examples/expr2.py --show-wat
code generation error: Only active default memory (index = 0) is currently supported


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
(lp) lpython$ 
```
