### ISSUE TITLE
Escape sequence recognized but not ignored in printing.

### ISSUE THREAD

**Issue by faze-geek** [lcompilers/lpython#1473]
The parser identifies backslash as an escape sequence and allows the printing but the `\` also gets printed.

```
    s: str
    s = 'I said 'Wow' '  # Without escape sequence 
    print(s)

(lp) C:\Users\kunni\lpython>python try.py
  File "C:\Users\kunni\lpython\try.py", line 3
    s = 'I said 'Wow''
                 ^^^
SyntaxError: invalid syntax

(lp) C:\Users\kunni\lpython>src\bin\lpython try.py
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: The string is not recognized by the parser.
```
```
    s: str
    s = 'I said \'Wow\' '  # With escape sequence
    print(s)

(lp) C:\Users\kunni\lpython>python try.py
I said 'Wow'

(lp) C:\Users\kunni\lpython>src\bin\lpython try.py
   Creating library try.lib and object try.exp
I said \'Wow\'
```

**Comment by faze-geek** [comment]
Simple eg - 
```
s = '\a'
print(s)
(lp) C:\Users\kunni\lpython>python try.py
(lp) C:\Users\kunni\lpython>src\bin\lpython try.py
   Creating library try.lib and object try.exp
\a
```

**Comment by certik** [comment]
Thanks for the bug report!

There are two bugs. This:
```python
s: str
s = 'I said 'Wow' '  # Without escape sequence 
print(s)
```
Triggers:
```console
$ lpython a.py 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 1668
    {
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 651
    fl.in_filename = infile;
  File "/Users/ondrej/repos/lpython/src/lpython/parser/parser.cpp", line 126
    Result<LPython::AST::Module_t*> res = parse(al, input, prev_loc, diagnostics);
  File "/Users/ondrej/repos/lpython/src/lpython/parser/parser.cpp", line 22
    p.parse(s, prev_loc);
  File "/Users/ondrej/repos/lpython/src/lpython/parser/parser.cpp", line 53
    m_tokenizer.set_string(inp, prev_loc);
  File "parser.yy", line 1105
  File "/Users/ondrej/repos/lpython/src/lpython/parser/semantics.h", line 892
    throw LCompilers::LCompilersException("The string is not recognized by the parser.");
LCompilersException: The string is not recognized by the parser.
```
While it should give an error message along the lines of:
```python
$ python a.py
  File "a.py", line 2
    s = 'I said 'Wow' '  # Without escape sequence 
                 ^
SyntaxError: invalid syntax
```


The other bug is that this code:
```python
s: str
s = 'I said \'Wow\' '  # Without escape sequence 
print(s)
```
should print:
```console
$ python a.py
I said 'Wow' 
```
But instead it prints:
```console
$ lpython a.py 
I said \'Wow\' 
```

**Comment by faze-geek** [comment]
Could be reopened until this [comment](https://github.com/lcompilers/lpython/pull/1500#issuecomment-1416918122) is addressed.
