### ISSUE TITLE
visit_Global() not implemented

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#1528]
Minimal example:
```python
msg : str = ""


def f():
    global msg
    print(msg)

f()
```
Gives:
```console
$ lpython b.py 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 1682
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 679
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics, compiler_options,
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 6207
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 6160
    while (idx >= 0 && path[idx] != '/' && path[idx] != '\\') idx--;
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3885
    }
  File "/Users/ondrej/repos/lpython/src/lpython/python_ast.h", line 1882
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/ondrej/repos/lpython/src/lpython/python_ast.h", line 1750
    case stmtType::FunctionDef: { v.visit_FunctionDef((const FunctionDef_t &)x); return; }
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3945
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3920
    }
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3845
    tmp_vec.clear();
  File "/Users/ondrej/repos/lpython/src/lpython/python_ast.h", line 1882
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/ondrej/repos/lpython/src/lpython/python_ast.h", line 1769
    case stmtType::ImportFrom: { v.visit_ImportFrom((const ImportFrom_t &)x); return; }
  File "/Users/ondrej/repos/lpython/src/lpython/python_ast.h", line 1903
    void visit_Global(const Global_t & /* x */) { throw LCompilersException("visit_Global() not implemented"); }
LCompilersException: visit_Global() not implemented
```

**Comment by anutosh491** [comment]
Hello @certik , I understood the problem here , but  being new to contributing here I am not sure which `make_...` function from the ASR namespace should I be using to create nodes for the ASR ?

I guess I have these options to choose from 
```
enum stmtType // Types
{
    Allocate, Assign, Assignment, Associate, Cycle, ExplicitDeallocate, ImplicitDeallocate, DoConcurrentLoop, DoLoop, ErrorStop, Exit, ForAllSingle, GoTo, GoToTarget, If, IfArithmetic, Print, FileOpen, FileClose, FileRead, FileBackspace, FileRewind, FileInquire, FileWrite, Return, Select, Stop, Assert, SubroutineCall, Where, WhileLoop, Nullify, Flush, ListAppend, AssociateBlockCall, SelectType, CPtrToPointer, BlockCall, SetInsert, SetRemove, ListInsert, ListRemove, ListClear, DictInsert
};
``

**Comment by czgdp1807** [comment]
I think this is same as importing a global variable into a function. So two cases would arise (I would explain through the example of `msg` variable in the description)

1. `msg` is not at all declared or defined in `f`'s scope. Then all is good just add `msg` in `f`'s scope as an `ExternalSymbol`.
2. If `msg` is already declared in `f`, something like,

```python
>>> msg : str = ""
>>> def f():
...     msg: str = "a"
...     print(msg)
...     global msg
...     print(msg)
... 
  File "<stdin>", line 4
SyntaxError: name 'msg' is used prior to global declaration
```

then throw a similar `SemanticError` in LPython.

@certik Any other case I am missing out here?
