### ISSUE TITLE
Implement indexing in 2D lists

### ISSUE THREAD

**Issue by namannimmo10** [lcompilers/lpython#161]
```python
a: list[list[i32], list[i32]]
a = [[1, 2], [3, 4], [5, 6]]
print(a[1][0])
```
AST:
```bash
(Module [
   (AnnAssign
      (Name
         a
         Store)
      (Subscript
         (Name
            list
            Load)
         (Tuple [
            (Subscript
               (Name
                  list
                  Load)
               (Name
                  i32
                  Load)
               Load)
            (Subscript
               (Name
                  list
                  Load)
               (Name
                  i32
                  Load)
               Load)]
            Load)
         Load) () 1)
   (Assign [
      (Name
         a
         Store)]
      (List [
         (List [
            (ConstantInt 1 ())
            (ConstantInt 2 ())]
            Load)
         (List [
            (ConstantInt 3 ())
            (ConstantInt 4 ())]
            Load)
         (List [
            (ConstantInt 5 ())
            (ConstantInt 6 ())]
            Load)]
         Load) ())
   (Expr
      (Call
         (Name
            print
            Load) [
         (Subscript
            (Subscript
               (Name
                  a
                  Load)
               (ConstantInt 1 ())
               Load)
            (ConstantInt 0 ())
            Load)] []))] [])
```
ASR:
```stdout
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/namannimmo/Applications/oss/lpython/src/bin/lpython.cpp", line 1470
    return emit_asr(arg_file, runtime_library_dir,
  File "/Users/namannimmo/Applications/oss/lpython/src/bin/lpython.cpp", line 547
    r = LFortran::Python::python_ast_to_asr(al, *ast, diagnostics, true);
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2567
    tu = res2.result;
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2523
    Error error;
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 704
    visit_stmt(*x.m_body[i]);
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/python_ast.h", line 1827
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/python_ast.h", line 1719
    case stmtType::Nonlocal: { v.visit_Nonlocal((const Nonlocal_t &)x); return; }
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1885
    args.push_back(al, expr);
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/python_ast.h", line 1854
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/python_ast.h", line 1755
    case exprType::Attribute: { v.visit_Attribute((const Attribute_t &)x); return; }
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 912
    ASR::Variable_t *v = ASR::down_cast<ASR::Variable_t>(s);
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/asr.h", line 40
    LFORTRAN_ASSERT(is_a<T>(*f));
AssertFailed: is_a<T>(*f)
```

**Comment by Thirumalai-Shaktivel** [comment]
After altering the above example to:
```py
def t():
    a: list[list[i32]]
    a = [[1, 2], [3, 4], [5, 6]]
    print(a[1][0])

t()
```
it generates the output
```console
$ lpython examples/expr2.py && ./a.out                
3
$ python examples/expr2.py       
3
```
I think this issue is fixed!
