### ISSUE TITLE
Empty data set should be treated differently by functions in `statistics.py`

### ISSUE THREAD

**Issue by faze-geek** [lcompilers/lpython#1692]
Was trying some benchmarks and came across functions in `statistics.py` 
Iterables like an empty list must not return 0 as an initialized value but return an error.

```
import statistics
def f():
    l:list[i32] = []
    print(statistics.mean(l))
f()

(lp) faze-geek@DESKTOP-497JDCU:~/lpython/lpython$ python try.py
Traceback (most recent call last):
  File "/home/faze-geek/lpython/lpython/try.py", line 37, in <module>
    f()
  File "/home/faze-geek/lpython/lpython/try.py", line 36, in f
    print(statistics.mean(l))
          ^^^^^^^^^^^^^^^^^^
statistics.StatisticsError: mean requires at least one data point

(lp) faze-geek@DESKTOP-497JDCU:~/lpython/lpython$ ./src/bin/lpython try.py
0.00000000000000000e+00
```
Seems like a straightforward fix, but should be done for all the functions present.

**Comment by harshitmathur2000** [comment]
I was working on this issue and came up with this diff -
```
--- a/src/runtime/statistics.py
+++ b/src/runtime/statistics.py
@@ -8,7 +8,7 @@ def mean(x: list[i32]) -> f64:
     """
     k: i32 = len(x)
     if k == 0:
-        return 0.0
+        raise Exception("ERROR: Dataset empty")
     sum: f64
```

But after build when I run the test snippet it gives the following instead of raising an error-
```
(lp) C:\Users\Lenovo\lpython>src\bin\lpython try.py
ERROR STOP
```
I have recently build lpython on windows machnie , am I supposed to get this output or is there some error with my build ?

**Comment by faze-geek** [comment]
It is unexpected. I run `lpython` on a WSL setup. 
I tested an existing error -
https://github.com/lcompilers/lpython/blob/ade107a593a888d95f715b08f9075ff2000b3782/src/runtime/statistics.py#L116-L118

```
import statistics
def f():
    l:list[i32] = [-1,-2,-3]
    print(statistics.geometric_mean(l))
f()
(lp) faze-geek@DESKTOP-497JDCU:~/lpython/lpython$ ./src/bin/lpython try.py
ERROR STOP             # Should have raised an exception 
```

**Comment by Thirumalai-Shaktivel** [comment]
I think `raise Exception` is not implemented yet.

**Comment by harshitmathur2000** [comment]
So should I continue to implement my changes ? It will work as expected in when in future `raise Exception` will be implemented.
