### ISSUE TITLE
Implement `--fast` tests in integration_tests

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#1793]
For example this fails:
```console
$ lpython -I$CONDA_PREFIX/lib/python3.11/site-packages/ test_package_01.py --fast
ASR verify pass error: ASR verify: FunctionCall::m_name `func` cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 1822
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 809
    res = fe.get_llvm3(*asr, pass_manager, diagnostics, infile);
  File "/Users/ondrej/repos/lpython/src/lpython/python_evaluator.cpp", line 58
    run_fn, infile);
  File "/Users/ondrej/repos/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 8062
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/ondrej/repos/lpython/src/libasr/pass/pass_manager.h", line 269
    _apply_passes(al, asr, _with_optimization_passes, pass_options,
  File "/Users/ondrej/repos/lpython/src/libasr/pass/pass_manager.h", line 148
    throw LCompilersException("Verify failed");
LCompilersException: Verify failed
```

**Comment by certik** [comment]
I think all the tests should run both `--fast` and no fast. Then some tests will fail, so for those we can introduce some label like `NOFAST` which will only run without `--fast`, for all the backends.
