### ISSUE TITLE
Support ``+=`` with ``dict``

### ISSUE THREAD

**Issue by czgdp1807** [lcompilers/lpython#1804]
> Looks like `+=` isn't currently supported for `dict` yet.

```python
from lpython import i32

def test_dict_bool():
    d_int: dict[bool, i32] = {}
    i: i32

    for i in range(10, 99):
        d_int[i%2 == 0] += 1

test_dict_bool()
```

```zsh
(lp) 16:09:21:~/lpython_project/lpython % lpython integration_tests/test_dict_bool.py --show-llvm
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/czgdp1807/lpython_project/lpython/src/bin/lpython.cpp", line 1765
    return emit_llvm(arg_file, runtime_library_dir, lpython_pass_manager, compiler_options);
  File "/Users/czgdp1807/lpython_project/lpython/src/bin/lpython.cpp", line 720
    res = fe.get_llvm3(*asr, pass_manager, diagnostics, infile);
  File "/Users/czgdp1807/lpython_project/lpython/src/lpython/python_evaluator.cpp", line 58
    run_fn, infile);
  File "/Users/czgdp1807/lpython_project/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 8075
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 4681
  File "../libasr/asr.h", line 4657
  File "../libasr/asr.h", line 4682
  File "../libasr/asr.h", line 4407
  File "/Users/czgdp1807/lpython_project/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 1317
    ASR::symbol_t *mod = x.m_global_scope->get_symbol(item);
  File "../libasr/asr.h", line 4684
  File "../libasr/asr.h", line 4415
  File "/Users/czgdp1807/lpython_project/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 2703
    finish_module_init_function_prototype(x);
  File "/Users/czgdp1807/lpython_project/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 4248
    visit_Function(*s);
  File "/Users/czgdp1807/lpython_project/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 3862
    visit_procedures(x);
  File "/Users/czgdp1807/lpython_project/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 4199
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4699
  File "../libasr/asr.h", line 4465
  File "/Users/czgdp1807/lpython_project/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 5339
    }, [=]() {
  File "/Users/czgdp1807/lpython_project/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 316
    start_new_block(loopbody); {
  File "/Users/czgdp1807/lpython_project/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 5341
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4699
  File "../libasr/asr.h", line 4472
  File "/Users/czgdp1807/lpython_project/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 4890
    this->visit_stmt(*(block->m_body[i]));
  File "../libasr/asr.h", line 4699
  File "../libasr/asr.h", line 4437
  File "/Users/czgdp1807/lpython_project/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 4746
    } else {
  File "../libasr/asr_utils.h", line 99
  File "../libasr/asr.h", line 41
AssertFailed: is_a<T>(*f)
```

**Comment by czgdp1807** [comment]
@kabra1110 Please take this up once you complete your work on ``list.reverse``.

**Comment by czgdp1807** [comment]
Completed in #1843.
