### ISSUE TITLE
Inheritance produces traceback instead of error message

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1923]
Consider [this code]

```python
@dataclass
class StringIO(IOBase):
    """Imitate the parts of io.StringIO we need."""
...
```

and this command:

`lpython lasr_lexer.py`

It produces the following traceback, but should probably produce a nice Rust-like error message:

```
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1828
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 783
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics, compiler_options,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7413
    diagnostics.diagnostics.push_back(e.d);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4411
    // We skip this in the SymbolTable visitor, but visit it in the BodyVisitor
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3748
    /* a_symtab */ current_scope,
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1883
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1752
    case stmtType::AsyncFunctionDef: { v.visit_AsyncFunctionDef((const AsyncFunctionDef_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2989
    throw SemanticError("Inheritance in classes isn't supported yet.",
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2783
    }
AssertFailed: AST::is_a<AST::AnnAssign_t>(*x.m_body[i])
```

**Comment by certik** [comment]
That's a bug, thanks! It looks like we don't support docstrings in dataclasses yet.

**Comment by rebcabin** [comment]
This one actually has an inheritance from `IOBase`! The docstring bug is a separate (but related) bug.

**Comment by certik** [comment]
I missed that.
