### ISSUE TITLE
Docstring in dataclass produces bogus Inheritance semantic error

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1924]
The following dataclass has a docstring

```python
@dataclass
class StringIO:
    """Imitate the parts of io.StringIO we need."""
    _buf     : str
    _0cursor : int = 0
    _len     : int = 0
```

produces the following traceback

```
└─(14:33:58 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython lasr_lexer.py                                                               2 ↵ ──(Fri,Jun16)─┘
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1828
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 783
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics, compiler_options,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7413
    diagnostics.diagnostics.push_back(e.d);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4411
    // We skip this in the SymbolTable visitor, but visit it in the BodyVisitor
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3748
    /* a_symtab */ current_scope,
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1883
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1752
    case stmtType::AsyncFunctionDef: { v.visit_AsyncFunctionDef((const AsyncFunctionDef_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2989
    throw SemanticError("Inheritance in classes isn't supported yet.",
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2783
    }
AssertFailed: AST::is_a<AST::AnnAssign_t>(*x.m_body[i])
```

Removing the docstring produces another error, but this one is expected:

```python
@dataclass
class StringIO:
    _buf     : str
    _0cursor : int = 0
    _len     : int = 0
```

~~~>

```
└─(14:34:57 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython lasr_lexer.py                                                               1 ↵ ──(Fri,Jun16)─┘
semantic error: Unsupported type annotation: int
  --> lasr_lexer.py:12:16
   |
12 |     _0cursor : int = 0
   |                ^^^ 
```

**Comment by certik** [comment]
The first error message I think is the same as #1923.

The second one I think is correct (no bug?).

**Comment by rebcabin** [comment]
#1923 actually has an inheritance from `IOBase`, so a separate bug!

**Comment by rebcabin** [comment]
> The first error message I think is the same as #1923.
> 
> The second one I think is correct (no bug?).

by #1926, it's a usability Issue, but not quite the level of a usability bug.
