### ISSUE TITLE
Integer initializer not defaulting to type `i32`?

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1925]
```python
@dataclass
class StringIO:
    _buf     : str
    _0cursor : i32 = 0
    _len     : i32 = 0
```

produces

```
└─(14:37:27 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython lasr_lexer.py                                                               1 ↵ ──(Fri,Jun16)─┘
ASR verify pass error: ASR verify: Initialisation of _0cursor must reduce to a compile time constant.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1828
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 783
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics, compiler_options,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7424
    int idx = path.size()-1;
LCompilersException: Verify failed
```

Isn't `0` by default a compile-time constant `i32(0)`

**Comment by certik** [comment]
It is, it should work. Thanks!

**Comment by Smit-create** [comment]
A similar test here works: https://github.com/lcompilers/lpython/pull/1936/files#diff-bc11971566a93c40104ec10f49e8ca4adb402c0e19d3b677392e2f87e8d30702

**Comment by Smit-create** [comment]
The following also works in the same PR:
```py
from lpython import dataclass, i32

@dataclass
class StringIO:
    _buf     : str
    _0cursor : i32 = 0
    _len     : i32 = 0

if __name__ == '__main__':
    integer_asr : str = '(Integer 4 [])'
    test_dude   : StringIO = StringIO(integer_asr)
    assert test_dude._buf == integer_asr
    assert test_dude._len == 0
    assert test_dude._0cursor == 0
    test_dude._len = 100
    assert test_dude._len == 100
    test_dude._0cursor = 31
    assert test_dude._0cursor == 31

```

**Comment by Shaikh-Ubaid** [comment]
This issue was fixed in [ASRVerify: Do not check init val for struct members](https://github.com/lcompilers/lpython/pull/1934/commits/ed21bf53a3f354b4907d6b91f0f592a4a745c34e).
