### ISSUE TITLE
Any method in dataclass produces bogus `Inheritance` traceback

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1929]
The following should be legal

```python
@dataclass
class StringIO:
    _buf     : str
    _0cursor : i32 = i32(0)
    _len     : i32 = i32(0)

    def read() -> str:
        result = ''
        return result

if __name__ == '__main__':
    integer_asr : str = '(Integer 4 [])'
    test_dude   : StringIO = StringIO(integer_asr, 0, len(integer_asr))
    assert test_dude._buf == integer_asr
    assert test_dude._len == len(integer_asr)
```

but it produces a traceback:

```
└─(15:18:12 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython lasr_lexer.py                                                               1 ↵ ──(Fri,Jun16)─┘
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1828
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 783
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics, compiler_options,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7413
    diagnostics.diagnostics.push_back(e.d);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4411
    // We skip this in the SymbolTable visitor, but visit it in the BodyVisitor
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3748
    /* a_symtab */ current_scope,
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1883
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1752
    case stmtType::AsyncFunctionDef: { v.visit_AsyncFunctionDef((const AsyncFunctionDef_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2989
    throw SemanticError("Inheritance in classes isn't supported yet.",
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2783
    }
AssertFailed: AST::is_a<AST::AnnAssign_t>(*x.m_body[i])
```

This has two problems. First, the error should produce a message and not a traceback (noted in other issues). Second, it should not be an error at all!

**Comment by rebcabin** [comment]
repro case : https://github.com/rebcabin/lpython/tree/brian-lasr/lasr/lpython/Issue1936

Works in CPython:

```python
from dataclasses import dataclass
i32 = int
from typing import \
    Generic, TypeVar, Optional, Union, \
    Tuple, Any, List, Pattern
T_ = TypeVar('T_')
class InOut(Generic[T_]):
    pass


@dataclass
class StringIO:
    _buf     : str
    _0cursor : i32 = i32(0)
    _len     : i32 = i32(0)


if __name__ == '__main__':
    integer_asr : str = '(Integer 4 [])'
    fd   : StringIO = StringIO(integer_asr)
    assert fd._len == 0
    assert fd._0cursor == 0
```

LPython version (comment out the compatibility block, that's the only change):

```python
# from dataclasses import dataclass
# i32 = int
# from typing import \
#     Generic, TypeVar, Optional, Union, \
#     Tuple, Any, List, Pattern
# T_ = TypeVar('T_')
# class InOut(Generic[T_]):
#     pass


@dataclass
class StringIO:
    _buf     : str
    _0cursor : i32 = i32(0)
    _len     : i32 = i32(0)


if __name__ == '__main__':
    integer_asr : str = '(Integer 4 [])'
    fd   : StringIO = StringIO(integer_asr)
    assert fd._len == 0
    assert fd._0cursor == 0
```

Improper (but not incorrect!) error message:

```bash
└─(15:33:11 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython -I. lasr_lexer.py && ./lasr_lexer.out                                           ──(Sun,Jun18)─┘
semantic error: StructConstructor arguments do not match the number of struct members
  --> lasr_lexer.py:20:23
   |
20 |     fd   : StringIO = StringIO(integer_asr)
   |                       ^^^^^^^^^^^^^^^^^^^^^ 
```
