### ISSUE TITLE
Fixing redefinition error causes `SIGSEGV`

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1938]
LPython (correctly) reports a redefinition error for the following code

```python
@dataclass
class StringIO:
    _buf     : str
    _0cursor : i32 = i32(0)
    _len     : i32 = i32(0)


## Issue #1930: InOut type


def __post_init__(this: InOut[StringIO]):
    this._len = len(this._buf)


def read(this: InOut[StringIO], chars : i32) -> str:
    result : str = ''  # EOF
    if this._0cursor == this._len:
        result = ''  #
    else:
        mac : i32 = min(this._len, this._0cursor + chars)
        assert mac <= this._len
        result : str = this._buf[this._0cursor, mac]  ########### ATTENTION #############
        this._0cursor = mac
    return result


if __name__ == '__main__':
    integer_asr : str = '(Integer 4 [])'
    fd   : StringIO = StringIO(integer_asr, 0, 0)
    __post_init__(fd)  # Issue #1929
    assert fd._buf == integer_asr
    assert fd._len == len(integer_asr)

    a_char : str = fd.read(1)
    assert a_char == '('
```

produces

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/lpython)────────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s000)─┐
└─(06:23:01 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython lasr_lexer.py                                                               1 ↵ ──(Sun,Jun18)─┘
semantic error: Symbol is already declared in the same scope
  --> lasr_lexer.py:24:5
   |
24 |     result : str = ''  # EOF
   |     ~~~~~~~~~~~~~~~~~ original declaration
   |
30 |         result : str = this._buf[this._0cursor, mac]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ redeclaration

```

Fixing the error as follows:

```python
@dataclass
class StringIO:
    _buf     : str
    _0cursor : i32 = i32(0)
    _len     : i32 = i32(0)


## Issue #1930: InOut type


def __post_init__(this: InOut[StringIO]):
    this._len = len(this._buf)


def read(this: InOut[StringIO], chars : i32) -> str:
    result : str = ''  # EOF
    if this._0cursor == this._len:
        result = ''  #
    else:
        mac : i32 = min(this._len, this._0cursor + chars)
        assert mac <= this._len
        result = this._buf[this._0cursor, mac]  ################ ATTENTION #############
        this._0cursor = mac
    return result


if __name__ == '__main__':
    integer_asr : str = '(Integer 4 [])'
    fd   : StringIO = StringIO(integer_asr, 0, 0)
    __post_init__(fd)  # Issue #1929
    assert fd._buf == integer_asr
    assert fd._len == len(integer_asr)

    a_char : str = fd.read(1)
    assert a_char == '('
```

produces:

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/lpython)────────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s000)─┐
└─(06:23:12 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython lasr_lexer.py                                                               2 ↵ ──(Sun,Jun18)─┘
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1828
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 783
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics, compiler_options,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7429
    return path.substr(0,idx);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7382
    return;
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4492
    }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1883
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1761
    case stmtType::While: { v.visit_While((const While_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 5768
    char *s = enum_m_var->m_name;
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4452
    class BodyVisitor : public CommonVisitor<BodyVisitor> {
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1883
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1757
    case stmtType::AugAssign: { v.visit_AugAssign((const AugAssign_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4725
    // We treat this as a declaration
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2707
    wrap_derived_type_in_pointer ) {
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1910
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1799
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7040
    if( !struct_member ) {
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1106
    ASR::ttype_t* list_type = ASRUtils::TYPE(ASR::make_List_t(al, loc, type));
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x18042ea23
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by Thirumalai-Shaktivel** [comment]
Here, the problem is with the line `a_char : str = fd.read(1)`
```console
$ python a.y
Traceback (most recent call last):
  File "/Users/thirumalai/Open_Source/lpython/examples/expr2.py", line 35, in <module>
    a_char : str = fd.read(1)
AttributeError: 'StringIO' object has no attribute 'read'
```

CPython throws an error message, But in LPython it throws SIGSEBGV. We need to fix this bug. Thanks for reporting.

**Comment by rebcabin** [comment]
Yes, there was a syntax error `[i, j]` instead of `[i: j]` in my original. Looks like that caused the SIGSEGV. I'll review the PR :)

**Comment by certik** [comment]
Now LPython shows:
```console
$ lpython a.py        
semantic error: Type mismatch in index, expected a single integer
  --> a.py:22:28
   |
22 |         result = this._buf[this._0cursor, mac]  ################ ATTENTION #############
   |                            ^^^^^^^^^^^^^^^^^^ type mismatch (found: 'tuple[i32, i32]', expected: 'i32')
```
That's a nice error message. Fixing it we get:
```console
$ lpython a.py
semantic error: read not present in StringIO dataclass
  --> a.py:34:20
   |
34 |     a_char : str = fd.read(1)
   |                    ^^^^^^^^^^ 
```
Another nice message. Fixing both using @Thirumalai-Shaktivel's diff now works:
```console
$ lpython a.py
$
```

**Comment by certik** [comment]
I guess instead of `semantic error: Type mismatch in index, expected a single integer`, it should say:
`semantic error: Type mismatch in string index, expected a single integer or slice`, right?

**Comment by Shaikh-Ubaid** [comment]
>The error message in the code seems to apply to more than strings. What other types does it apply to?

It applies to any type excluding a `dict`. It means it includes `list`, `tuple`, `arrays`, `strings`.

> I guess instead of `semantic error: Type mismatch in index, expected a single integer`, it should say:
`semantic error: Type mismatch in string index, expected a single integer or slice`, right?

Yes, we can update it to `semantic error: Type mismatch in string index, expected a single integer or slice`. 

Does `^^^^ type mismatch (found: 'tuple[i32, i32]', expected: 'i32')` also need to be updated? Should it be `^^^^ type mismatch (found: 'tuple[i32, i32]', expected: 'i32' or slice)`?

**Comment by certik** [comment]
Let's do `semantic error: Type mismatch in index, expected a single integer or slice`. (I removed the word `string`, since it applies to more types). 

Good point about the label update, go ahead and do it.

I am excited about these improvements to error messages, high quality error messages are very important.
