### ISSUE TITLE
dataclass initial value causes SIGSEGV

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1954]
repro: https://github.com/rebcabin/lpython/tree/brian-lasr/lasr/lpython/Issue1954

The following code works

```python
@dataclass
class LasrLexer:
    fd   : StringIO = StringIO('', 0, 0)
    line : i32
    col  : i32
    type : str
    val  : str
```

The following code produces a SIGSEGV:

```python
@dataclass
class LasrLexer:
    fd   : Optional[StringIO] = None # StringIO('', 0, 0)
    line : i32
    col  : i32
    type : str
    val  : str
```

produces: 

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/lpython)────────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s000)─┐
└─(15:09:07 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython -I. lasr_lexer.py && ./lasr_lexer.out                                       1 ↵ ──(Mon,Jun19)─┘
LCOMPILERS_ASSERT failed: /Users/brian/CLionProjects/lpython/src/libasr/asr.h
function expr_type0(), line number 47038 at 
false
ERROR MESSAGE:
6
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1828
    std::string emit_file_name = basename + "__tmp__generated__.c";
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 783
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics, compiler_options,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7413
    } else if (intrinsic_node_handler.is_present(call_name)) {
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4411
    ASR::abiType current_procedure_abi_type = ASR::abiType::Source;
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3748
    }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1883
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1752
    case stmtType::AsyncFunctionDef: { v.visit_AsyncFunctionDef((const AsyncFunctionDef_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2989
    return ;
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2793
    if (is_allocatable && x.m_value && AST::is_a<AST::Call_t>(*x.m_value)) {
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2689
    for (size_t i=0; i<tt->n_elts; i++) {
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1760
    ASR::ttype_t *type = ast_expr_to_asr_type(loc, *s->m_slice, is_allocatable);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1539
    }
  File "/Users/brian/CLionProjects/lpython/src/libasr/asr_utils.h", line 132
    ASR::down_cast<ASR::Var_t>(f)->m_v));
  File "/Users/brian/CLionProjects/lpython/src/libasr/asr.h", line 47038
    LCOMPILERS_ASSERT_MSG(false, std::to_string(s->type));
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18030dae7
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x1803ffc27
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x18042ea23
Abort: Signal SIGABRT (abort) received

[3]    1367 abort      ~/CLionProjects/lpython/src/bin/lpython -I. lasr_lexer.py
```

**Comment by Smit-create** [comment]
I think `Optional` isn't a supported type yet in LPython.

**Comment by certik** [comment]
Yes, we should give a nice error message that "Optional is not supported". We don't need to say "not supported yet", since we don't know if we'll support it in the future or not, but just having a nice error message will go a long way.

Alternatively it should say that `Optional` has not been imported from anywhere.

**Comment by rebcabin** [comment]
The big-picture question is "what parts of 'typing' should LPython support ?" The kind of non-numerical code I'm writing now will demand all of it. I speculate that the new Symbolic work will also end up demanding all of it, too.

**Comment by certik** [comment]
Are you able to proceed with the current set of features, or is `Optional` a blocker? It's a good feature, but I think it requires thoughtful handling: the compiler should ensure that the user always checks that the value is present before using, so that there is no undefined behavior (segfaults).

**Comment by rebcabin** [comment]
I'm not blocked, but only because ordinary Python ignores type annotations :)
