### ISSUE TITLE
another SIGSEGV from dataclass initializer

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1955]
repro: https://github.com/rebcabin/lpython/tree/brian-lasr/lasr/lpython/Issue1955

The following code produces a SIGSEGV on the initializer of 1 to `line`

```python
@dataclass
class LasrLexer:
    fd   : StringIO = StringIO('', 0, 0)
    line : i32 = 1
    col  : i32
    type : str
    val  : str
```

produces:

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/lpython)────────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s000)─┐
└─(15:15:55 on brian-lasr ✭)──> ~/CLionProjects/lpython/src/bin/lpython -I. lasr_lexer.py && ./lasr_lexer.out                                             ──(Mon,Jun19)─┘
ASR verify pass error: ASR verify: Initialisation of line must reduce to a compile time constant.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1828
    std::string emit_file_name = basename + "__tmp__generated__.c";
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 783
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics, compiler_options,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7424
    }
LCompilersException: Verify failed
```

**Comment by Shaikh-Ubaid** [comment]
On latest main, the following seems to work for me.
```bash
$ cat examples/expr2.py 
@dataclass
class StringIO:
    _buf: str
    _0cursor: i32 = 0
    _len: i32     = 0

@dataclass
class LasrLexer:
    fd   : StringIO = StringIO('', 0, 0)
    line : i32 = 1
    col  : i32
    type : str
    val  : str

def main0():
    lasr_lexer: LasrLexer = LasrLexer(StringIO('some buffer', 0, 0), 1, 0, "", "")
    lasr_lexer.type = "some type"
    print(lasr_lexer.fd, lasr_lexer.type)
main0()
$ lpython examples/expr2.py
some buffer 0 0 some type
```
Please, could you try using the latest main and share us if it works?

**Comment by rebcabin** [comment]
I tried to merge the latest main. I will try again.

**Comment by rebcabin** [comment]
no go for me :(

<img width="896" alt="image" src="https://github.com/lcompilers/lpython/assets/207047/a6ee5273-1e38-4ea3-8480-8de8d1a1aba4">

```python
from lpython import dataclass, InOut, i32
@dataclass
class StringIO:
    _buf: str
    _0cursor: i32 = 0
    _len: i32     = 0

@dataclass
class LasrLexer:
    fd   : StringIO = StringIO('', 0, 0)
    line : i32 = 1
    col  : i32
    type : str
    val  : str

def main0():
    lasr_lexer: LasrLexer = LasrLexer(StringIO('some buffer', 0, 0), 1, 0, "", "")
    lasr_lexer.type = "some type"
    print(lasr_lexer.fd, lasr_lexer.type)
main0()
```

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/lpython)────────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s000)─┐
└─(16:24:39 on brian-lasr ✹ ✭)──> cp lasr_lexer.py expr2.py                                                                                           1 ↵ ──(Mon,Jun19)─┘
(lp) ┌─(~/CLionProjects/lpython/lasr/lpython)────────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s000)─┐
└─(16:24:48 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython -I. expr2.py                                                                    ──(Mon,Jun19)─┘
ASR verify pass error: ASR verify: Initialisation of line must reduce to a compile time constant.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1828
    std::string emit_file_name = basename + "__tmp__generated__.c";
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 783
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics, compiler_options,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7424
    }
LCompilersException: Verify failed
```

**Comment by rebcabin** [comment]
Trying harder, still not working:

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/lpython)────────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s000)─┐
└─(16:29:40 on brian-lasr ✹ ✭)──> git fetch                                                                                                               ──(Mon,Jun19)─┘
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 28 (delta 22), reused 13 (delta 9), pack-reused 0
Unpacking objects: 100% (28/28), 6.10 KiB | 173.00 KiB/s, done.
From https://github.com/lcompilers/lpython
   d0b957d36..d6a6d8b72  main       -> origin/main
(lp) ┌─(~/CLionProjects/lpython/lasr/lpython)────────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s000)─┐
└─(16:29:50 on brian-lasr ✹ ✭)──> git merge origin main                                                                                                   ──(Mon,Jun19)─┘
Merge made by the 'ort' strategy.
 .github/workflows/CI.yml                      |  44 ++++++++++++++++++++++++++++++++++++++
 integration_tests/CMakeLists.txt              |  31 +++++++++++++++++++++++++--
 integration_tests/run_tests.py                |   2 +-
 integration_tests/symbolics_01.py             |  11 ++++++++++
 src/bin/lpython.cpp                           |   7 ++++++
 src/libasr/ASR.asdl                           |   1 +
 src/libasr/asr_utils.h                        |  13 ++++++++++++
 src/libasr/codegen/asr_to_c.cpp               |   8 +++++++
 src/libasr/codegen/asr_to_c_cpp.h             |  38 ++++++++++++++++++++++++++++-----
 src/libasr/codegen/c_utils.h                  |  37 ++++++++++++++++++++++++++++++++
 src/libasr/pass/intrinsic_function_registry.h | 135 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---
 src/libasr/utils.h                            |   1 +
 src/lpython/semantics/python_ast_to_asr.cpp   |  63 ++++++++++++++++++++++++++++++++++++++++++------------
 src/runtime/lpython/lpython.py                |   4 +++-
 14 files changed, 370 insertions(+), 25 deletions(-)
 create mode 100644 integration_tests/symbolics_01.py
(lp) ┌─(~/CLionProjects/lpython/lasr/lpython)────────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s000)─┐
└─(16:30:00 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython -I. expr2.py                                                                    ──(Mon,Jun19)─┘
ASR verify pass error: ASR verify: Initialisation of line must reduce to a compile time constant.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1828
    } else if (backend == Backend::wasm) {
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 783
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics, compiler_options,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7424
    target_type = ASRUtils::TYPE(ASR::make_Integer_t(al, x.base.base.loc, 2));
LCompilersException: Verify failed
```

**Comment by rebcabin** [comment]
a minute please ...
could be my bad

**Comment by rebcabin** [comment]
MY BAD

I forgot to build the new merged LPython :)

**Comment by rebcabin** [comment]
was my bad. I forgot to BUILD the fresh merge :) 1960 is closed
