### ISSUE TITLE
Valid LPython w dataclass initializer is not valid CPython

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1957]
repro: https://github.com/rebcabin/lpython/tree/brian-lasr/lasr/lpython/Issue1956

The following code passes LPython:

```python
@dataclass
class LasrLexer:
    fd   : StringIO = StringIO('', 0, 0)
    line : i32 # Issue 1955 = 1
    col  : i32
    type : str
    val  : str
```

but in ordinary CPython (in PyCharm, produces:

```bash
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/lasr/lpython/lasr_lexer.py", line 138, in <module>
    class LasrLexer:
  File "/Users/brian/CLionProjects/lpython/src/runtime/lpython/lpython.py", line 53, in dataclass
    return py_dataclass(arg)
  File "/Users/brian/mambaforge/envs/lp/lib/python3.10/dataclasses.py", line 1185, in dataclass
    return wrap(cls)
  File "/Users/brian/mambaforge/envs/lp/lib/python3.10/dataclasses.py", line 1176, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/Users/brian/mambaforge/envs/lp/lib/python3.10/dataclasses.py", line 1025, in _process_class
    _init_fn(all_init_fields,
  File "/Users/brian/mambaforge/envs/lp/lib/python3.10/dataclasses.py", line 546, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'line' follows default argument
```

**Comment by rebcabin** [comment]
The Issue # may not match the name of the repro directory because I must guess the Issue # at the time I am writing the bug. They'll be off-by-one if someone else submits an issue at the same time. Could also be off if I make a bad guess.

**Comment by Thirumalai-Shaktivel** [comment]
You can rename the directory name and push it back to git.
But it's not a problem, as you are always sharing the links to the respective issues. Thanks to that, we are able to reproduce the errors.
