### ISSUE TITLE
Full dataclass initialization produces SIGSEGV

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1959]
repro: https://github.com/rebcabin/lpython/tree/brian-lasr/lasr/lpython/Issue1960

The following code (full initialization) passes CPython:

```python
@dataclass
class LasrLexer:
    fd   : StringIO = StringIO('', 0, 0) # prefer Optional[StringIO]
    line : i32 = 1 # prefer Line
    col  : i32 = 1 # prefer Col
    type : str = '' # prefer LTType
    val  : str = '' # prefer LTVal
```

but LPython produces:

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/lpython)────────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s000)─┐
└─(16:09:55 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython -I. lasr_lexer.py && ./lasr_lexer.out                                           ──(Mon,Jun19)─┘
ASR verify pass error: ASR verify: Initialisation of col must reduce to a compile time constant.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1828
    std::string emit_file_name = basename + "__tmp__generated__.c";
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 783
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics, compiler_options,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7424
    }
LCompilersException: Verify failed
```

This may be a duplicate of an earlier Issue.

**Comment by rebcabin** [comment]
It passes both CPython and LPython as 

```python
@dataclass
class LasrLexer:
    fd   : StringIO = StringIO('', 0, 0) # prefer Optional[StringIO]
    line : i32 = i32(1) # prefer Line
    col  : i32 = i32(1) # prefer Col
    type : str = str('') # prefer LTType
    val  : str = str('') # prefer LTVal
```

**Comment by rebcabin** [comment]
The Issue # may not match the name of the repro directory because I must guess the Issue # at the time I am writing the bug. They'll be off-by-one if someone else submits an issue at the same time. Could also be off if I make a bad guess.
