### ISSUE TITLE
Instantiating `Lexer` class causes SIGABRT

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1970]
repro: https://github.com/rebcabin/lpython/tree/brian-lasr/lasr/LP-pycharm/Issue1970

This code causes a SIGABRT:

```python
def lexer_test():
    print('LEXER TEST')
    lexer : InOut[LasrLexer] = LasrLexer()  ############ ATTENTION #############
    assert True
```

produces:

```bash
/Users/brian/CLionProjects/lpython/src/bin/python /Users/brian/CLionProjects/lpython/lasr/LP-pycharm/lasr_lexer.py 
LCOMPILERS_ASSERT failed: /Users/brian/CLionProjects/lpython/src/libasr/asr.h
function expr_type0(), line number 47387 at 
false
ERROR MESSAGE:
6
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1844
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 783
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics, compiler_options,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7529
    auto res2 = body_visitor(al, lm, *ast_m, diagnostics, unit, main_module,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7482
    b.visit_Module(ast);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4585
    visit_stmt(*x.m_body[i]);
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1883
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1751
    case stmtType::FunctionDef: { v.visit_FunctionDef((const FunctionDef_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4692
    handle_fn(x, *f);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4674
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4545
    this->visit_stmt(*m_body[i]);
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1883
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1757
    case stmtType::AugAssign: { v.visit_AugAssign((const AugAssign_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4818
    visit_AnnAssignUtil(x, var_name);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2752
    ASR::ttype_t *type = ast_expr_to_asr_type(x.base.base.loc, *x.m_annotation, is_allocatable);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1793
    fill_dims_for_asr_type(dims, value, loc);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1572
    ASR::ttype_t *itype = ASRUtils::expr_type(value);
  File "/Users/brian/CLionProjects/lpython/src/libasr/asr_utils.h", line 143
    return ASR::expr_type0(f);
  File "/Users/brian/CLionProjects/lpython/src/libasr/asr.h", line 47387
    LCOMPILERS_ASSERT_MSG(false, std::to_string(s->type));
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18030dae7
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x1803ffc27
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x18042ea23
Abort: Signal SIGABRT (abort) received```

**Comment by rebcabin** [comment]
It works if I leave off the `InOut`

```python
def lexer_test():
    print('LEXER TEST')
    lexer : LasrLexer = LasrLexer()  ############ ATTENTION ############
    assert True
```

**Comment by certik** [comment]
`lexer` is not an argument, so should not have the `InOut` attribute. We need to give a nice error message here.

**Comment by rebcabin** [comment]
I think I screwed up the repro directory. Apologies if so, but the bug is clear enough I hope.

**Comment by certik** [comment]
@rebcabin if you press "y" in the file with the repro, the url changes to include the hash. If you use that url, then it should stay valid, no matter what you later do with the file (such as adding more commits).
