### ISSUE TITLE
CPython allows uninitialized variable, LPython does not ?

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1991]
Not sure whether this is intentional. 

repro: https://github.com/rebcabin/lpython/tree/brian-lasr/lasr/LP-pycharm/Issue1990

CPython:

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm/Issue1990)───────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s014)─┐
└─(13:34:57 on brian-lasr ✖ ✭)──> PYTHONPATH='../../../src/runtime/lpython' python ./lasr_lexer.py                                                        ──(Wed,Jun21)─┘
STRINGIO TEST
READ-SEEK-TELL-TEST
LEXER TEST
REGEX TEST
```

LPython:

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm/Issue1990)───────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s014)─┐
└─(13:36:44 on brian-lasr ✖ ✭)──> ../../../src/bin/lpython -I. ./lasr_lexer.py                                                                            ──(Wed,Jun21)─┘
semantic error: `rr` must be initialized with an instance of ReRange
   --> ./lasr_lexer.py:139:5
    |
139 |     rr : ReRange
    |     ^^^^^^^^^^^^ 
```

**Comment by certik** [comment]
Hm, I just discussed this precise issue yesterday with our team, I thought it's ok, but I can now see it's not.

 Here is the example:
```python
@dataclass
class ReRange:
    start_char_ord : i32
    end_char_ord   : i32

def check_re_range_alternatives(
        alts : list[ReRange],
        char : str) -> bool:
    result : bool = False
    rr : ReRange
    for rr in alts:
        if check_re_range(rr, char):
            result = True
            break
    return result
```
It gives:
```console
semantic error: `rr` must be initialized with an instance of ReRange
  --> a.py:10:5
   |
10 |     rr : ReRange
   |     ^^^^^^^^^^^^ 
```
The issue is that `rr` is used as a loop iterator, so it makes no sense to initialize it ahead of time.

This was done in https://github.com/lcompilers/lpython/pull/1808. I think we should relax this requirement. The reason we did (I think) is that it's relatively easy to enforce the struct to be initialized. But as we can see now, there is a use case when this is not a good idea.

**Comment by Shaikh-Ubaid** [comment]
```bash
$ cat examples/expr2.py   
from lpython import dataclass, i32

@dataclass
class A:
    n: i32

def main0():
    a: A
    a.n = 5
    print(a)

main0()
$ python examples/expr2.py 
Traceback (most recent call last):
  File "/Users/ubaid/Desktop/OpenSource/lpython/examples/expr2.py", line 12, in <module>
    main0()
  File "/Users/ubaid/Desktop/OpenSource/lpython/examples/expr2.py", line 9, in main0
    a.n = 5
UnboundLocalError: local variable 'a' referenced before assignment
$ lpython examples/expr2.py
5
```
It seems CPython does not define a variable unless it is assigned. Since everything that compiles/runs with LPython should run with CPython, to tackle cases as above, we made it mandatory to initialize the variable if is a not a Simple Type. We need to see for a possible Robust fix/approach here.

**Comment by Shaikh-Ubaid** [comment]
If anyone have any ideas, please feel free to share.

For the moment, I am assigning this to me.

**Comment by certik** [comment]
I would fix this issue as follows. This should not be allowed:
```
def main0():
    a: A
    a.n = 5
    print(a)
```
Rather, either this:
```
def main0():
    a: A
    a = A(5) # Or "a = A()" if CPython allows it
    a.n = 5
    print(a)
```
or this must be required:
```
def main0():
    a: A = A(5) # Or "a: A = A()" if CPython allows it
    a.n = 5
    print(a)
```

**Comment by rebcabin** [comment]
I'll give another use case for `declaring` variables with types without initializing them: imperative code where re-use of variables is intended.

This is better:

```python
def lexer_test() -> None: # lexer : InOut[LasrLexer]):
    # Issue #1981
    print('LEXER TEST')
    # re-use these variables multiple times
    lexer : LasrLexer
    t : str

    # first test
    lexer = LasrLexer(StringIO('  foo  bar  '))
    __post_init__(lexer.fd)
    eat_white(lexer)
    t = peek_debug(lexer)
    # Issue 1971 print({"t": t})
    assert t == 'f', "t == 'f'"

    # second test
    lexer = LasrLexer(StringIO('(Integer 4 [])'))
    __post_init__(lexer.fd)
    t = get_non_white((lexer))
    assert t == '(', "t = '('"
```

than this:

```python
def lexer_test() -> None: # lexer : InOut[LasrLexer]):
    # Issue #1981
    print('LEXER TEST')
    # re-use these variables multiple times
    lexer : LasrLexer
    t : str

    # first test
    lexer : LasrLexer = LasrLexer(StringIO('  foo  bar  '))
    __post_init__(lexer.fd)
    eat_white(lexer)
    t : str = peek_debug(lexer)
    # Issue 1971 print({"t": t})
    assert t == 'f', "t == 'f'"

    # second test
    lexer = LasrLexer(StringIO('(Integer 4 [])'))
    __post_init__(lexer.fd)
    t = get_non_white((lexer))
    assert t == '(', "t = '('"
```

The latter is what we must do now, due to LPython limitations.
