### ISSUE TITLE
Adding lists faults; should present error or just work

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1992]
repro: https://github.com/rebcabin/lpython/tree/brian-lasr/lasr/LP-pycharm/Issue1992

the offending code:

```python
def regex_test() -> None:
    print('REGEX TEST')
    assert ord('a') >= ord('a')
    assert ord('a') <= ord('z')

    rr : ReRange = ReRange(ord('a'), ord('z'))
    assert check_re_range(rr, 'x')
    assert not check_re_range(rr, '@')

    lower_case_alpha_range : ReRange = ReRange(ord('a'), ord('z'))
    upper_case_alpha_range : ReRange = ReRange(ord('A'), ord('Z'))
    digit_range            : ReRange = ReRange(ord('0'), ord('9'))
    underscore             : ReRange = ReRange(ord('_'), ord('_'))
    special_AT             : ReRange = ReRange(ord('@'), ord('@'))
    special_TILDE          : ReRange = ReRange(ord('~'), ord('~'))
    sym_first_pattern : list[ReRange] = \
        [underscore, lower_case_alpha_range, upper_case_alpha_range]
    sym_rest_pattern  : list[ReRange] = \   ################ ATTENTION ###############
        sym_first_pattern + [underscore, special_AT, special_TILDE]
```

Commenting out the ATTENTION lines makes the problem go away.

CPython: 

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm/Issue1992)───────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s014)─┐
└─(13:53:36 on brian-lasr ✖ ✹ ✭)──> PYTHONPATH='../../../src/runtime/lpython' python ./lasr_lexer.py                                                  1 ↵ ──(Wed,Jun21)─┘
STRINGIO TEST
READ-SEEK-TELL-TEST
LEXER TEST
REGEX TEST
```

LPython:

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm/Issue1992)───────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s014)─┐
└─(13:53:33 on brian-lasr ✖ ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython -I. lasr_lexer.py                                                             ──(Wed,Jun21)─┘
ASR verify pass error: ASR verify: The symbol table was not found in the scope of `symtab`.

ASR verify pass error: ASR verify: Struct::m_derived_type 'ReRange' cannot point outside of its symbol table, owner: _global_symbols
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1844
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 809
    res = fe.get_llvm3(*asr, pass_manager, diagnostics, infile);
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_evaluator.cpp", line 58
    run_fn, infile);
  File "/Users/brian/CLionProjects/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 8527
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/brian/CLionProjects/lpython/src/libasr/pass/pass_manager.h", line 281
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/brian/CLionProjects/lpython/src/libasr/pass/pass_manager.h", line 154
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: pass_list_expr
```

**Comment by Smit-create** [comment]
The `pass_list_expr` adds some global functions for List concat operation. This is done in global scope so we don't have to define these functions again. Now, the issue is because of the global stmts pass that wraps these symbols into some Module and use them. Because `ReRange` was in the global scope and moved under some Module in global stmts pass, the concat function didn't find the symbol. The following fix worked for me:
```diff
--- a/src/libasr/pass/pass_list_expr.cpp
+++ b/src/libasr/pass/pass_list_expr.cpp
@@ -413,6 +413,7 @@ public:
             fn_sym, nullptr, args.p, args.n, x->m_type, nullptr, nullptr));
     }
 
+
     void create_concat_function(Location& loc,
             SymbolTable*& global_scope, ASR::ttype_t* list_type) {
         /*
@@ -430,7 +431,9 @@ public:
                     __1_k += 1
                 return result_list
         */
-        SymbolTable* list_concat_symtab = al.make_new<SymbolTable>(global_scope);
+        ASR::Module_t *mod = ASR::down_cast<ASR::Module_t>(
+                            global_scope->get_symbol("_global_symbols"));
+        SymbolTable* list_concat_symtab = al.make_new<SymbolTable>(mod->m_symtab);
         std::string list_type_name = ASRUtils::get_type_code(list_type, true);
         std::string fn_name = global_scope->get_unique_name("_lcompilers_list_concat_" + list_type_name);
 
@@ -501,7 +504,7 @@ public:
             nullptr, 0,
             false, false, false);
         ASR::symbol_t *fn_sym = ASR::down_cast<ASR::symbol_t>(fn);
-        global_scope->add_symbol(fn_name, fn_sym);
+        mod->m_symtab->add_symbol(fn_name, fn_sym);
         list_concat_func_map[list_type_name] = fn_sym;
     }
```
But I am not sure how exactly to find these wrapped symbols. The above diff uses hackish `"_global_symbols"`, but there might be a better way to find this symtab.

@certik Do you know if there is a better way to find this module `_global_symbols` ?

(The above diff does fix the issue and passes all the tests.)

**Comment by certik** [comment]
I see. I see three paths forward:

* We can copy those global functions into a module
* We can call them via an interface in the module
* We can allow calling global functions in modules / programs

**Comment by rebcabin** [comment]
Seems to me that 3 (allowing calls of globals) is the easiest, cleanest,
best option. The others require copying (expensive in space) or
restructuring / lifting interface defs into a module, with risk of name
collisions.

**Comment by rebcabin** [comment]
allowing calls of globals should fit into a proper "environment" model of
lexical scope, too. A single, unique, global environment contains bindings
to global functions.

**Comment by certik** [comment]
Let's say you have two modules that both use the same global function. How should serialization and deserialization to ".mod" files work? We need to support separate compilation that allows you to compile one module at a time, save the ASR to disk, and so on. Then in the main program you load everything from disk and compile.

**Comment by rebcabin** [comment]
right. this is a complication i didn't consider.

**Comment by certik** [comment]
I think the solution is to put those "support" functions not into a global scope, but rather into a module, say "_lcompilers_list_module". Then functions from it can be easily used either at global scope, or inside other modules via ExternalSymbol and then everything works well.

@Smit-create I think this is the ultimate clean solution.

**Comment by rebcabin** [comment]
excellent!

**Comment by Smit-create** [comment]
> I think the solution is to put those "support" functions not into a global scope, but rather into a module, say "_lcompilers_list_module"

How will the function in `_lcompilers_list_module` be able to find `ReRange` which is in the module `_global_symbols`?

**Comment by certik** [comment]
Are those functions generated specifically for ReRange? I would have to understand the details. Essentially we need to find a solution that puts functions in modules, so that they can be serialized.

**Comment by Smit-create** [comment]
These functions are generated for concatenating two `list[ReRange]`.

**Comment by certik** [comment]
I see, these functions are specifically generated to handle the user type ReRange when used as `list[ReRange]` and concatenating. In this case I would put those functions right next to the type. If it is in some module, put them in the same module. If it is in the global scope, then keep it in the global scope, but then when things are moved to a module later, we have to move these functions with it.
