### ISSUE TITLE
Implement the `math` standard library module

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#2]
https://docs.python.org/3/library/math.html

Let's start with pure Python functions such as `factorial`.

**Comment by Smit-create** [comment]
Implementation of `factorial` using different ways:

1. Using `while` and `if` (for verifying positive int)
<details>
<summary> Reference code </summary>

<p>

```py
def factorial(x: i32) -> i32:
    if x < 0:
        return 0
    result: i32
    result = 1
    while x > 0:
        result = result * x
        x -= 1
    return result
```
</p>
</details>

<details>
<summary> AST </summary>

<p>

```py
(Module [
   (FunctionDef 
      factorial 
      ([] [
         (
            x 
            (Name 
               i32 
               Load) ())] [] [] [] [] []) [
      (If 
         (Compare 
            (Name 
               x 
               Load) 
            Lt [
            (ConstantInt 0 ())]) [
         (Return 
            (ConstantInt 0 ()))] []) 
      (AnnAssign 
         (Name 
            result 
            Store) 
         (Name 
            i32 
            Load) () 1) 
      (Assign [
         (Name 
            result 
            Store)] 
         (ConstantInt 1 ()) ()) 
      (While 
         (Compare 
            (Name 
               x 
               Load) 
            Gt [
            (ConstantInt 0 ())]) [
         (Assign [
            (Name 
               result 
               Store)] 
            (BinOp 
               (Name 
                  result 
                  Load) 
               Mult 
               (Name 
                  x 
                  Load)) ()) 
         (AugAssign 
            (Name 
               x 
               Store) 
            Sub 
            (ConstantInt 1 ()))] []) 
      (Return 
         (Name 
            result 
            Load))] [] 
      (Name 
         i32 
         Load) ())] [])
```
</p>
</details>

<details>
<summary> ASR </summary>
<p>

```bash
Traceback (most recent call last):
  Binary file "/home/admin-pc/Smitlunagariya/lfortran/inst/bin/lfortran", in _start()
  File "/build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c", line 310, in __libc_start_main()
  File "/home/admin-pc/Smitlunagariya/lfortran/src/bin/lfortran.cpp", line 1504, in main()
    with_intrinsic_modules, compiler_options);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/bin/lfortran.cpp", line 616, in emit_python_asr()
    r = LFortran::Python::python_ast_to_asr(al, *ast, diagnostics);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/semantics/python_ast_to_asr.cpp", line 660, in LFortran::Python::python_ast_to_asr(Allocator&, LFortran::Python::AST::ast_t&, LFortran::diag::Diagnostics&)
    auto res2 = body_visitor(al, *ast_m, diagnostics, unit);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/semantics/python_ast_to_asr.cpp", line 616, in LFortran::Python::body_visitor(Allocator&, LFortran::Python::AST::Module_t&, LFortran::diag::Diagnostics&, LFortran::ASR::asr_t*)
    b.visit_Module(ast);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/semantics/python_ast_to_asr.cpp", line 299, in LFortran::Python::BodyVisitor::visit_Module(LFortran::Python::AST::Module_t const&)
    visit_stmt(*x.m_body[i]);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/python_ast.h", line 1805, in LFortran::Python::AST::BaseVisitor<LFortran::Python::BodyVisitor>::visit_stmt(LFortran::Python::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/python_ast.h", line 1677, in visit_stmt_t<LFortran::Python::BodyVisitor>()
    case stmtType::FunctionDef: { v.visit_FunctionDef((const FunctionDef_t &)x); return; }
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/semantics/python_ast_to_asr.cpp", line 312, in LFortran::Python::BodyVisitor::visit_FunctionDef(LFortran::Python::AST::FunctionDef_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/semantics/python_ast_to_asr.cpp", line 283, in LFortran::Python::BodyVisitor::transform_stmts(LFortran::Vec<LFortran::ASR::stmt_t*>&, unsigned long, LFortran::Python::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/python_ast.h", line 1805, in LFortran::Python::AST::BaseVisitor<LFortran::Python::BodyVisitor>::visit_stmt(LFortran::Python::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/python_ast.h", line 1688, in visit_stmt_t<LFortran::Python::BodyVisitor>()
    case stmtType::If: { v.visit_If((const If_t &)x); return; }
LFortranException: visit_If() not implemented
```
</p>
</details>

2. Using only `while` and not verifying for positive integers(without `if`)

<details>
<summary> Reference code  </summary>
<p>

```py
def factorial(x: i32) -> i32:
    result: i32
    result = 1
    while x > 0:
        result = result * x
        x -= 1
    return result
```
</p>

</details>

<details>
<summary> AST </summary>

<p>

```py
(Module [
   (FunctionDef 
      factorial 
      ([] [
         (
            x 
            (Name 
               i32 
               Load) ())] [] [] [] [] []) [
      (AnnAssign 
         (Name 
            result 
            Store) 
         (Name 
            i32 
            Load) () 1) 
      (Assign [
         (Name 
            result 
            Store)] 
         (ConstantInt 1 ()) ()) 
      (While 
         (Compare 
            (Name 
               x 
               Load) 
            Gt [
            (ConstantInt 0 ())]) [
         (Assign [
            (Name 
               result 
               Store)] 
            (BinOp 
               (Name 
                  result 
                  Load) 
               Mult 
               (Name 
                  x 
                  Load)) ()) 
         (AugAssign 
            (Name 
               x 
               Store) 
            Sub 
            (ConstantInt 1 ()))] []) 
      (Return 
         (Name 
            result 
            Load))] [] 
      (Name 
         i32 
         Load) ())] [])
```
</p>
</details>

<details>
<summary> ASR </summary>

<p>

```bash
Traceback (most recent call last):
  Binary file "/home/admin-pc/Smitlunagariya/lfortran/inst/bin/lfortran", in _start()
  File "/build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c", line 310, in __libc_start_main()
  File "/home/admin-pc/Smitlunagariya/lfortran/src/bin/lfortran.cpp", line 1504, in main()
    with_intrinsic_modules, compiler_options);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/bin/lfortran.cpp", line 616, in emit_python_asr()
    r = LFortran::Python::python_ast_to_asr(al, *ast, diagnostics);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/semantics/python_ast_to_asr.cpp", line 660, in LFortran::Python::python_ast_to_asr(Allocator&, LFortran::Python::AST::ast_t&, LFortran::diag::Diagnostics&)
    auto res2 = body_visitor(al, *ast_m, diagnostics, unit);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/semantics/python_ast_to_asr.cpp", line 616, in LFortran::Python::body_visitor(Allocator&, LFortran::Python::AST::Module_t&, LFortran::diag::Diagnostics&, LFortran::ASR::asr_t*)
    b.visit_Module(ast);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/semantics/python_ast_to_asr.cpp", line 299, in LFortran::Python::BodyVisitor::visit_Module(LFortran::Python::AST::Module_t const&)
    visit_stmt(*x.m_body[i]);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/python_ast.h", line 1805, in LFortran::Python::AST::BaseVisitor<LFortran::Python::BodyVisitor>::visit_stmt(LFortran::Python::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/python_ast.h", line 1677, in visit_stmt_t<LFortran::Python::BodyVisitor>()
    case stmtType::FunctionDef: { v.visit_FunctionDef((const FunctionDef_t &)x); return; }
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/semantics/python_ast_to_asr.cpp", line 312, in LFortran::Python::BodyVisitor::visit_FunctionDef(LFortran::Python::AST::FunctionDef_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/semantics/python_ast_to_asr.cpp", line 283, in LFortran::Python::BodyVisitor::transform_stmts(LFortran::Vec<LFortran::ASR::stmt_t*>&, unsigned long, LFortran::Python::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/python_ast.h", line 1805, in LFortran::Python::AST::BaseVisitor<LFortran::Python::BodyVisitor>::visit_stmt(LFortran::Python::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/python_ast.h", line 1687, in visit_stmt_t<LFortran::Python::BodyVisitor>()
    case stmtType::While: { v.visit_While((const While_t &)x); return; }
LFortranException: visit_While() not implemented
```
</p>
</details>

3. Using only `for` and not verifying for positive integers(without `if`)

<details>
<summary> Reference code </summary>
<p>

```py
def factorial(x: i32) -> i32:
    result: i32
    result = 1
    i: i32
    for i in range(1, x+1):
        result = result * i
    return result
```
</p>
</details>

<details>
<summary> AST </summary>

<p>

```py
(Module [
   (FunctionDef 
      factorial 
      ([] [
         (
            x 
            (Name 
               i32 
               Load) ())] [] [] [] [] []) [
      (AnnAssign 
         (Name 
            result 
            Store) 
         (Name 
            i32 
            Load) () 1) 
      (Assign [
         (Name 
            result 
            Store)] 
         (ConstantInt 1 ()) ()) 
      (AnnAssign 
         (Name 
            i 
            Store) 
         (Name 
            i32 
            Load) () 1) 
      (For 
         (Name 
            i 
            Store) 
         (Call 
            (Name 
               range 
               Load) [
            (ConstantInt 1 ()) 
            (BinOp 
               (Name 
                  x 
                  Load) 
               Add 
               (ConstantInt 1 ()))] []) [
         (Assign [
            (Name 
               result 
               Store)] 
            (BinOp 
               (Name 
                  result 
                  Load) 
               Mult 
               (Name 
                  i 
                  Load)) ())] [] ()) 
      (Return 
         (Name 
            result 
            Load))] [] 
      (Name 
         i32 
         Load) ())] [])

```
</p>
</details>

<details>
<summary> ASR </summary>
<p>

If I don't declare `i: i32` in the above reference code, then it gave `i is not declared` error.
```bash
semantic error: Only range(X) of one argument X supported as for loop iteration for now
 --> ser.txt:1:1
  |
1 | 0 0 1 0 9 factorial 0 1 1 x 1 26 3 i32 0 0 0 0 0 0 0 5 7 26 6 result 1 26 3 i32 0 0 1 5 1 26 6 result 1 20 1 0 0 7 26 1 i 1 26 3 i32 0 0 1 8 26 1 i 1 16 26 5 range 0 2 20 1 0 2 26 1 x 0 0 20 1 0 0 1 5 1 26 6 result 1 2 26 6 result 0 2 26 1 i 0 0 0 0 3 1 26 6 result 0 0 1 26 3 i32 0 0 0 
  | ^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).

```
</p>
</details>

**Comment by namannimmo10** [comment]
> LFortranException: visit_If() not implemented

This is included in https://gitlab.com/certik/lfortran/-/merge_requests/5

Also, I think the `int` and `float` annotation types should be supported:
```diff
diff --git a/src/lfortran/semantics/python_ast_to_asr.cpp b/src/lfortran/semantics/python_ast_to_asr.cpp
index 8255652f7..0dce45548 100644
--- a/src/lfortran/semantics/python_ast_to_asr.cpp
+++ b/src/lfortran/semantics/python_ast_to_asr.cpp
@@ -106,13 +106,13 @@ public:
         if (var_annotation == "i32") {
             type = LFortran::ASRUtils::TYPE(ASR::make_Integer_t(al, loc,
                 4, dims.p, dims.size()));
-        } else if (var_annotation == "i64") {
+        } else if (var_annotation == "i64" || var_annotation == "int") {
             type = LFortran::ASRUtils::TYPE(ASR::make_Integer_t(al, loc,
                 8, dims.p, dims.size()));
         } else if (var_annotation == "f32") {
             type = LFortran::ASRUtils::TYPE(ASR::make_Real_t(al, loc,
                 4, dims.p, dims.size()));
-        } else if (var_annotation == "f64") {
+        } else if (var_annotation == "f64" || var_annotation == "float") {
             type = LFortran::ASRUtils::TYPE(ASR::make_Real_t(al, loc,
                 8, dims.p, dims.size()));
```

**Comment by certik** [comment]
I think the second line `f64` being equal to `float` is fine, as `float` in Python always means 64 bit floating point. But the `int` in Python means arbitrary precision integer, so we should not identify that with `i64`, which is only 64 bit.

For consistency, it seems to me that using `i32`, `i64`, `f32` and `f64` makes sense. Rust uses the same convention.

**Comment by Smit-create** [comment]
All the versions of https://github.com/lcompilers/lpython/issues/2#issuecomment-1003380631 are working fine now.

**Comment by Smit-create** [comment]
I implemented the `gcd` function in the following way:
<details>
<summary> Code </summary>

<p>

```py
def gcd(a: i32, b: i32):
    temp: i32
    while b!=0:
        a = a % b
        temp = a
        a = b
        b = temp
    return a
```
</p>
</details>
<details>
<summary> AST </summary>

<p>

```bash
(Module [
   (FunctionDef 
      gcd 
      ([] [
         (
            a 
            (Name 
               i32 
               Load) ()) 
         (
            b 
            (Name 
               i32 
               Load) ())] [] [] [] [] []) [
      (AnnAssign 
         (Name 
            temp 
            Store) 
         (Name 
            i32 
            Load) () 1) 
      (While 
         (Compare 
            (Name 
               b 
               Load) 
            NotEq [
            (ConstantInt 0 ())]) [
         (Assign [
            (Name 
               a 
               Store)] 
            (BinOp 
               (Name 
                  a 
                  Load) 
               Mod 
               (Name 
                  b 
                  Load)) ()) 
         (Assign [
            (Name 
               temp 
               Store)] 
            (Name 
               a 
               Load) ()) 
         (Assign [
            (Name 
               a 
               Store)] 
            (Name 
               b 
               Load) ()) 
         (Assign [
            (Name 
               b 
               Store)] 
            (Name 
               temp 
               Load) ())] []) 
      (Return 
         (Name 
            a 
            Load))] [] () ())] [])

```
</p>
</details>

<details>
<summary> ASR </summary>

<p>

```bash
semantic error: Binary operator type not supported
 --> ser.txt:1:1
  |
1 | 0 0 1 0 3 gcd 0 2 1 a 1 26 3 i32 0 0 1 b 1 26 3 i32 0 0 0 0 0 0 0 3 7 26 4 temp 1 26 3 i32 0 0 1 10 15 26 1 b 0 1 1 20 0 0 4 5 1 26 1 a 1 2 26 1 a 0 5 26 1 b 0 0 5 1 26 4 temp 1 26 1 a 0 0 5 1 26 1 a 1 26 1 b 0 0 5 1 26 1 b 1 26 4 temp 0 0 0 3 1 26 1 a 0 0 0 0 0 
  | ^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).

```
</p>
</details>

ASR gives Binary operator not supported because of `%` (modulo operator). In python AST we have `Mod` as the operator but  in lfortran we  use `MODULO` function at compile time:
```cpp
static ASR::expr_t *eval_modulo(Allocator &al, const Location &loc, Vec<ASR::expr_t*> &args) {
        return eval_2args_ri(al, loc, args,
            &IntrinsicProcedures::lfortran_modulo,
            &IntrinsicProcedures::lfortran_modulo_i);
    }

```
How should we handle it in lpython?

**Comment by namannimmo10** [comment]
I think one way is by adding `Mod` in ASR.asdl:
```
binop = Add | Sub | Mul | Div | Pow | Mod
```
and considering the case of Modulo in `BinOp` thereafter -- works fine with that.

We could represent `a%b` as `a - b * floor(a / b)`, but we would need `math.floor` for that:
```python
>>> a = 45349534
>>> b = 45345
>>> import math
>>> a%b == a - b * math.floor(a/b)
True
>>> a = -1
>>> b = 500
>>> a%b == a - b * math.floor(a/b)
True
>>> a = 400
>>> b = 400
>>> a%b == a - b * math.floor(a/b)
True
>>> a = 400
>>> b = 38482370423
>>> a%b == a - b * math.floor(a/b)
True
```

**Comment by Smit-create** [comment]
> We could represent `a%b` as `a - b * floor(a / b)`, but we would need `math.floor` for that:

Well, that might be an option, but for speed purposes, I see we should directly use the `mod` operator. See the time differences:
```py
In [1]: a = 45349534

In [2]: b = 45345

In [3]: %timeit a%b
104 ns ± 1.35 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [4]: import math

In [5]: %timeit a - b * math.floor(a/b)
390 ns ± 3.39 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**Comment by Smit-create** [comment]
One more issue while implementing `pow` function:
<details>
<summary>Code</summary>
<p>

```py
def pow(a:i32, b:i32):
    return a**b

def check():
    a: i32
    a = pow(2, 2)
```
</p> 
</details>

<details>
<summary>AST</summary>
<p>

```bash
(Module [
   (FunctionDef 
      pow 
      ([] [
         (
            a 
            (Name 
               i32 
               Load) ()) 
         (
            b 
            (Name 
               i32 
               Load) ())] [] [] [] [] []) [
      (Return 
         (BinOp 
            (Name 
               a 
               Load) 
            Pow 
            (Name 
               b 
               Load)))] [] () ()) 
   (FunctionDef 
      check 
      ([] [] [] [] [] [] []) [
      (AnnAssign 
         (Name 
            a 
            Store) 
         (Name 
            i32 
            Load) () 1) 
      (Assign [
         (Name 
            a 
            Store)] 
         (Call 
            (Name 
               pow 
               Load) [
            (ConstantInt 2 ()) 
            (ConstantInt 2 ())] []) ())] [] () ())] [])

```
</p> 
</details>

<details>
<summary>ASR</summary>
<p>

```bash
Traceback (most recent call last):
  Binary file "/home/admin-pc/Smitlunagariya/lfortran/inst/bin/lfortran", in _start()
  File "/build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c", line 310, in __libc_start_main()
  File "/home/admin-pc/Smitlunagariya/lfortran/src/bin/lfortran.cpp", line 1504, in main()
    with_intrinsic_modules, compiler_options);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/bin/lfortran.cpp", line 616, in emit_python_asr()
    r = LFortran::Python::python_ast_to_asr(al, *ast, diagnostics);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/semantics/python_ast_to_asr.cpp", line 1024, in LFortran::Python::python_ast_to_asr(Allocator&, LFortran::Python::AST::ast_t&, LFortran::diag::Diagnostics&)
    LFORTRAN_ASSERT(asr_verify(*tu));
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/asr_verify.cpp", line 423, in LFortran::asr_verify(LFortran::ASR::TranslationUnit_t const&, bool)
    v.visit_TranslationUnit(unit);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/asr_verify.cpp", line 111, in LFortran::ASR::VerifyVisitor::visit_TranslationUnit(LFortran::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/asr.h", line 2069, in LFortran::ASR::BaseVisitor<LFortran::ASR::VerifyVisitor>::visit_symbol(LFortran::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/asr.h", line 1925, in visit_symbol_t<LFortran::ASR::VerifyVisitor>()
    case symbolType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/asr_verify.cpp", line 203, in LFortran::ASR::VerifyVisitor::visit_Subroutine(LFortran::ASR::Subroutine_t const&)
    visit_stmt(*x.m_body[i]);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/asr.h", line 2081, in LFortran::ASR::BaseVisitor<LFortran::ASR::VerifyVisitor>::visit_stmt(LFortran::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/asr.h", line 1943, in visit_stmt_t<LFortran::ASR::VerifyVisitor>()
    case stmtType::Assignment: { v.visit_Assignment((const Assignment_t &)x); return; }
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/asr.h", line 2243, in LFortran::ASR::BaseWalkVisitor<LFortran::ASR::VerifyVisitor>::visit_Assignment(LFortran::ASR::Assignment_t const&)
    self().visit_expr(*x.m_value);
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/asr.h", line 2109, in LFortran::ASR::BaseVisitor<LFortran::ASR::VerifyVisitor>::visit_expr(LFortran::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/asr.h", line 1981, in visit_expr_t<LFortran::ASR::VerifyVisitor>()
    case exprType::FunctionCall: { v.visit_FunctionCall((const FunctionCall_t &)x); return; }
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/asr_verify.cpp", line 384, in LFortran::ASR::VerifyVisitor::visit_FunctionCall(LFortran::ASR::FunctionCall_t const&)
    require(ASR::is_a<ASR::Function_t>(*fn),
  File "/home/admin-pc/Smitlunagariya/lfortran/src/lfortran/asr_verify.cpp", line 60, in LFortran::ASR::VerifyVisitor::require(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LFortran::Location const&)
    require(cond, msg);
LFortranException: ASR verify failed: 0:0: FunctionCall::m_name must be a Function

```
</p> 
</details>

**Comment by Smit-create** [comment]
> I implemented the `gcd` function in the following way:

This works fine on this patch: https://gitlab.com/certik/lfortran/-/merge_requests/28

<details>
<summary> ASR </summary>
<p>

```bash
(TranslationUnit 
   (SymbolTable 
      1 
      {
         gcd: 
            (Subroutine 
               (SymbolTable 
                  2 
                  {
                     a: 
                        (Variable 
                           2 
                           a 
                           In () () 
                           Default 
                           (Integer 4 []) 
                           Source 
                           Public 
                           Required .false.), 
                     b: 
                        (Variable 
                           2 
                           b 
                           In () () 
                           Default 
                           (Integer 4 []) 
                           Source 
                           Public 
                           Required .false.), 
                     temp: 
                        (Variable 
                           2 
                           temp 
                           Local () () 
                           Default 
                           (Integer 4 []) 
                           Source 
                           Public 
                           Required .false.)
                  }) 
               gcd [
               (Var 2 a) 
               (Var 2 b)] [
               (WhileLoop 
                  (Compare 
                     (Var 2 b) 
                     NotEq (ConstantInteger 0 
                     (Integer 4 [])) 
                     (Logical 4 []) () ()) [
                  (= 
                     (Var 2 a) 
                     (BinOp 
                        (Var 2 a) 
                        Mod 
                        (Var 2 b) 
                        (Integer 4 []) () ()) ()) 
                  (= 
                     (Var 2 temp) 
                     (Var 2 a) ()) 
                  (= 
                     (Var 2 a) 
                     (Var 2 b) ()) 
                  (= 
                     (Var 2 b) 
                     (Var 2 temp) ())]) 
               (Return)] 
               Source 
               Public 
               Implementation () .false. .false.)
      }) 
   [])

```
</p>
</details>

**Comment by namannimmo10** [comment]
@Smit-create, are you working on adding `math.gcd()` and `math.lcm()`? If not, I can complete them.
I think for now your patch looks good, but down the road, we should add support for an arbitrary number of arguments 

(See https://github.com/python/cpython/pull/18604).

**Comment by khairalanam** [comment]
Hello everyone!

Can I work on this issue?
