### ISSUE TITLE
Unimplemented `...` should print error, not throw

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#2001]
repro:

```python
def match_symbol() -> None:
    ...
```

passes CPython, but LPython throws:

```bash
/Users/brian/CLionProjects/lpython/src/bin/python /Users/brian/CLionProjects/lpython/lasr/LP-pycharm/lasr_lexer.py 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1844
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 783
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics, compiler_options,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7532
    auto res2 = body_visitor(al, lm, *ast_m, diagnostics, unit, main_module,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7485
    b.visit_Module(ast);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4620
    visit_stmt(*x.m_body[i]);
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1883
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1751
    case stmtType::FunctionDef: { v.visit_FunctionDef((const FunctionDef_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4727
    handle_fn(x, *f);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4709
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4580
    this->visit_stmt(*m_body[i]);
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1883
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1772
    case stmtType::Nonlocal: { v.visit_Nonlocal((const Nonlocal_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 6441
    this->visit_expr(*x.m_value);
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1910
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1807
    case exprType::ConstantComplex: { v.visit_ConstantComplex((const ConstantComplex_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1935
    void visit_ConstantEllipsis(const ConstantEllipsis_t & /* x */) { throw LCompilersException("visit_ConstantEllipsis() not implemented"); }
LCompilersException: visit_ConstantEllipsis() not implemented
```

**Comment by faze-geek** [comment]
@Thirumalai-Shaktivel I see the grammar for `...` is already added here - 
https://github.com/lcompilers/lpython/blob/62a217e683dde68581e7a38c0ed36fe17353b636/src/lpython/parser/semantics.h#L998

A diff like this seems enough here -
```
+++ b/src/lpython/semantics/python_ast_to_asr.cpp
@@ -6240,6 +6240,10 @@ public:

+    void visit_ConstantEllipsis(const AST::ConstantEllipsis_t &/*x*/) {
+        tmp = nullptr;
+    }
+
```
Kindly check it out once. I'll make a pr for it then.

**Comment by certik** [comment]
@faze-geek go ahead and make a PR with a test.
