### ISSUE TITLE
LPython throws on list construction; CPython passes it

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#2003]
repro: https://github.com/rebcabin/lpython/tree/brian-lasr/lasr/LP-pycharm/Issue2003

Offending code in `lasr_lexer.py`. comment out the assignment to `hexit_pattern` to pass LPython:

```python
lower_case_alpha_range : ReRange = ReRange(ord('a'), ord('z'))
upper_case_alpha_range : ReRange = ReRange(ord('A'), ord('Z'))
digit_range            : ReRange = ReRange(ord('0'), ord('9'))
octit_range            : ReRange = ReRange(ord('0'), ord('7'))
hexit_pattern : list[ReRange] = [digit_range,  ############# ATTENTION ############
                                 ReRange(ord('a'), ord('f')),
                                 ReRange(ord('A'), ord('F'))]
underscore             : ReRange = ReRange(ord('_'), ord('_'))
special_AT             : ReRange = ReRange(ord('@'), ord('@'))
special_TILDE          : ReRange = ReRange(ord('~'), ord('~'))
sym_first_pattern : list[ReRange] = \
    [underscore, lower_case_alpha_range, upper_case_alpha_range]

# Issue #1992
# sym_rest_pattern  : list[ReRange] = \
#     sym_first_pattern + [special_AT, special_TILDE]
sym_rest_pattern : list[ReRange] = \
    [underscore, lower_case_alpha_range, digit_range,
     upper_case_alpha_range, special_AT, special_TILDE]

```

Results of running:

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm/Issue2003)───────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s012)─┐
└─(10:38:18 on brian-lasr ✹ ✭)──> PYTHONPATH='../../../src/runtime/lpython' python lasr_lexer.py                                                          ──(Thu,Jun22)─┘
STRINGIO TEST
READ-SEEK-TELL-TEST
LEXER TEST
REGEX TEST
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm/Issue2003)───────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s012)─┐
└─(10:38:25 on brian-lasr ✹ ✭)──> ../../../src/bin/lpython -I. ./lasr_lexer.py                                                                            ──(Thu,Jun22)─┘
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1844
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 809
    res = fe.get_llvm3(*asr, pass_manager, diagnostics, infile);
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_evaluator.cpp", line 58
    run_fn, infile);
  File "/Users/brian/CLionProjects/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 8533
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 4869
  File "../libasr/asr.h", line 4845
  File "../libasr/asr.h", line 4870
  File "../libasr/asr.h", line 4585
  File "/Users/brian/CLionProjects/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 1359
    ASR::symbol_t *mod = x.m_global_scope->get_symbol(item);
  File "../libasr/asr.h", line 4872
  File "../libasr/asr.h", line 4593
  File "/Users/brian/CLionProjects/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 2940
    finish_module_init_function_prototype(x);
  File "/Users/brian/CLionProjects/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 4336
    visit_Function(*s);
  File "/Users/brian/CLionProjects/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 3941
    visit_procedures(x);
  File "/Users/brian/CLionProjects/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 4287
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4889
  File "../libasr/asr.h", line 4617
  File "/Users/brian/CLionProjects/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 4905
    is_assignment_target = true;
  File "../libasr/asr.h", line 4935
  File "../libasr/asr.h", line 4735
  File "/Users/brian/CLionProjects/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 2557
    LCOMPILERS_ASSERT(der_type_name.size() != 0);
AssertFailed: der_type_name.size() != 0
```

**Comment by rebcabin** [comment]
workaround:

```python
hex_af                 : ReRange = ReRange(ord('a'), ord('f'))
hex_AF                 : ReRange = ReRange(ord('A'), ord('F'))
hexit_pttern : list[ReRange] = [digit_range, hex_af, hex_AF]
# Issue2003
# hexit_pattern : list[ReRange] = [digit_range,
#                                  ReRange(ord('a'), ord('f')),
#                                  ReRange(ord('A'), ord('F'))]```

**Comment by Smit-create** [comment]
This might be a fix for it: https://github.com/lfortran/lfortran/pull/1858
