### ISSUE TITLE
Implement `int` with radices from strings

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#2004]
offending code; the last three produce error messages in LPython (it's ok, this is an enhancement request)

```python
    assert hex(1959) == '0x7a7'
    assert int(1959) == 1959
    assert int('1959') == 1959 ########## ATTENTION ###########
    assert int(hex(1959), base=16) == 1959
    assert int(oct(1959), base=8) == 1959
```

**Comment by rebcabin** [comment]
I make the first assert go away as follows. The last three produce error messages:

```python
    assert hex(1959) == '0x7a7'
    assert i32(1959) == 1959
    assert i32('1959') == 1959
    # assert int(hex(1959), base=16) == 1959
    # assert int(oct(1959), base=8) == 1959
```

**Comment by rebcabin** [comment]
These don't work in CPython with lpython import:

expr42.py:

```python
assert hex(1959) == '0x7a7'
assert oct(1959) == '0o3647'
assert i32(1959) == 1959
assert i32('1959', base=10) == 1959
# assert i32('1959') == 1959 # Issue 2004
assert i32(hex(1959), base=16) == 1959
assert i32(oct(1959), base=8) == 1959
```

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm)─────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s012)─┐
└─(11:16:53 on brian-lasr ✹ ✭)──> PYTHONPATH='../../src/runtime/lpython' python expr42.py                                                                 ──(Thu,Jun22)─┘
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/lasr/LP-pycharm/expr42.py", line 3, in <module>
    assert i32(1959) == 1959
NameError: name 'i32' is not defined
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm)─────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s012)─┐
└─(11:17:03 on brian-lasr ✹ ✭)──> ../../src/bin/lpython -I. ./expr42.py
```

**Comment by rebcabin** [comment]
sorry for all the edits; i'm done now :)

**Comment by rebcabin** [comment]
This issue is really two problems:

1. `i32('1959')` with no `base` should default to `base=10`
2. `i32('1959', base=...)` should work in CPython

**Comment by rebcabin** [comment]
my latest clarification:

```python
    assert hex(1959) == '0x7a7'
    assert oct(1959) == '0o3647'
    assert i32(1959) == 1959

    # Issue 2004 -- doesn't work in CPython
    # assert i32('1959', base=10) == 1959

    # Issue 2004 -- doesn't work in LPython
    # assert i32('1959') == 1959 # Issue 2004

    # Issue 2004 -- doesn't work in CPython
    # assert i32(hex(1959), base=16) == 1959

    # Issue 2004 -- doesn't work in CPython
    # assert i32(oct(1959), base=8) == 1959
```

**Comment by rebcabin** [comment]
Well, this whole thing has just stopped working for me altogether (I dunno, all I did was go to lunch!). Now getting nullptr!

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm)─────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s012)─┐
└─(15:18:44 on brian-lasr ✹ ✭)──> cat expr44.py                                                                                                       1 ↵ ──(Thu,Jun22)─┘
from lpython import i32
assert i32(hex(1959), base=16) == 1959
# assert i32('0x7a7', base=16) == 1959
# assert i32('1959', base=10) == 1959
```

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm)─────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s012)─┐
└─(15:18:38 on brian-lasr ✹ ✭)──> ../../src/bin/lpython -I. ./expr44.py                                                                               1 ↵ ──(Thu,Jun22)─┘
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1844
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 783
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics, compiler_options,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7532
    auto res2 = body_visitor(al, lm, *ast_m, diagnostics, unit, main_module,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7485
    b.visit_Module(ast);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4620
    visit_stmt(*x.m_body[i]);
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1883
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1767
    case stmtType::Try: { v.visit_Try((const Try_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 5109
    this->visit_expr(*x.m_test);
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1910
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1798
    case exprType::YieldFrom: { v.visit_YieldFrom((const YieldFrom_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 5971
    this->visit_expr(*x.m_left);
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1910
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1799
    case exprType::Compare: { v.visit_Compare((const Compare_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7450
    cast_helper(target_type, arg, x.base.base.loc, true);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1938
    return ;
  File "/Users/brian/CLionProjects/lpython/src/libasr/asr_utils.h", line 143
    return ASR::expr_type0(f);
  File "/Users/brian/CLionProjects/lpython/src/libasr/asr.h", line 47327
    LCOMPILERS_ASSERT(f != nullptr);
AssertFailed: f != nullptr
```

**Comment by rebcabin** [comment]
HEISENBUG!

sometimes works and sometimes throws. I checked in expr44.py which seems always to throw.

**Comment by certik** [comment]
Is this a blocker?

**Comment by rebcabin** [comment]
> Is this a blocker?

not a blocker. I'll always mark blockers in the title :)

**Comment by rebcabin** [comment]
Or, if you prefer, I'll make a 'BLOCKER' label.

**Comment by certik** [comment]
We have a "high priority" label that you can use.
