### ISSUE TITLE
CPython reports good error; LPython misses it

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#2008]
repro: https://github.com/rebcabin/lpython/tree/brian-lasr/lasr/LP-pycharm/Issue2008

The CPython error message points to the offending code on line 275 of `lasr_lexer.py`

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm/Issue2008)───────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s012)─┐
└─(16:30:37 on brian-lasr ✭)──> ls -la                                                                                                                1 ↵ ──(Thu,Jun22)─┘
total 48
drwxr-xr-x   5 brian  staff    160 Jun 22 16:30 .
drwxr-xr-x  37 brian  staff   1184 Jun 22 16:29 ..
drwxr-xr-x   3 brian  staff     96 Jun 22 16:30 __pycache__
-rw-r--r--   1 brian  staff  18673 Jun 22 16:29 lasr_lexer.py
-rw-r--r--   1 brian  staff   3031 Jun 22 16:29 lasr_stringio.py
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm/Issue2008)───────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s012)─┐
└─(16:30:46 on brian-lasr ✭)──> PYTHONPATH='../../../src/runtime/lpython' python lasr_lexer.py                                                            ──(Thu,Jun22)─┘
STRINGIO TEST
READ-SEEK-TELL-TEST
LEXER TEST
REGEX TEST
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/lasr/LP-pycharm/Issue2008/lasr_lexer.py", line 554, in <module>
    regex_test()
  File "/Users/brian/CLionProjects/lpython/lasr/LP-pycharm/Issue2008/lasr_lexer.py", line 332, in regex_test
    assert match_integer('4')
  File "/Users/brian/CLionProjects/lpython/lasr/LP-pycharm/Issue2008/lasr_lexer.py", line 275, in match_integer
    check_numerical_syntax(c, last, i, mxx)
UnboundLocalError: local variable 'i' referenced before assignment
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm/Issue2008)───────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s012)─┐
└─(16:30:49 on brian-lasr ✭)──> ../../../src/bin/lpython -I. ./lasr_lexer.py                                                                          1 ↵ ──(Thu,Jun22)─┘
STRINGIO TEST
READ-SEEK-TELL-TEST
LEXER TEST
REGEX TEST
```

**Comment by lightdrk** [comment]
Check your condition,  in starting of the function at 230 , conditions are not write that is the most possible cause , try declaring ' i ' outside the condition
