### ISSUE TITLE
CPython reports `assert` traceback, LPython does not (usability)

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#2009]
easy to repro. Here is a sample run

```bash
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm)─────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s012)─┐
└─(16:54:18 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython -I. lasr_lexer.py                                                               ──(Thu,Jun22)─┘
STRINGIO TEST
READ-SEEK-TELL-TEST
LEXER TEST
REGEX TEST
AssertionError
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm)─────────────────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s012)─┐
└─(16:57:47 on brian-lasr ✹ ✭)──> PYTHONPATH='../../src/runtime/lpython' python lasr_lexer.py                                                         1 ↵ ──(Thu,Jun22)─┘
STRINGIO TEST
READ-SEEK-TELL-TEST
LEXER TEST
REGEX TEST
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/lasr/LP-pycharm/lasr_lexer.py", line 581, in <module>
    regex_test()
  File "/Users/brian/CLionProjects/lpython/lasr/LP-pycharm/lasr_lexer.py", line 372, in regex_test
    assert cnvi('0B1111_0100_111', base=2) == 1959
AssertionError
```

**Comment by certik** [comment]
Try `lpython lasr_lexer.py -g --debug-with-line-column`, it should print a nice stacktrace like Python.

**Comment by rebcabin** [comment]
These options might not be mature, yet. I won't provide a repro (it's too big), just observe that I got an exception that debug information for type str is not done yet from supplying these options:

```bash
/Users/brian/CLionProjects/lpython/src/bin/python -g --debug-with-line-column /Users/brian/CLionProjects/lpython/lasr/LP-pycharm/lasr_lexer.py 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1844
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 809
    res = fe.get_llvm3(*asr, pass_manager, diagnostics, infile);
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_evaluator.cpp", line 58
    run_fn, infile);
  File "/Users/brian/CLionProjects/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 8533
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 4869
  File "../libasr/asr.h", line 4845
  File "../libasr/asr.h", line 4870
  File "../libasr/asr.h", line 4585
  File "/Users/brian/CLionProjects/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 1359
    ASR::symbol_t *mod = x.m_global_scope->get_symbol(item);
  File "../libasr/asr.h", line 4872
  File "../libasr/asr.h", line 4593
  File "/Users/brian/CLionProjects/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 2933
    instantiate_function(*v);
  File "/Users/brian/CLionProjects/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 3996
    debug_emit_function(x, SP);
  File "/Users/brian/CLionProjects/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 403
    get_type_debug_info(ASRUtils::expr_type(x.m_return_var),
  File "/Users/brian/CLionProjects/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 353
    default : throw LCompilersException("Debug information for the type: `"
LCompilersException: Debug information for the type: `str` is not yet implemented
```

**Comment by certik** [comment]
Yes, the debugging facility is not well tested yet.
