### ISSUE TITLE
Can't find variable for class initializers

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#2030]
repro :

```python
from lpython import dataclass

FOO : str = 'foo'

@dataclass
class bar:
    baz : str = FOO
```

run : 

```bash

LPYTHON

(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm/Issue2030)───────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s012)─┐
└─(16:44:54 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython -I. issue2030.py                                                          130 ↵ ──(Sun,Jun25)─┘
semantic error: Variable 'FOO' not declared
 --> issue2030.py:7:17
  |
7 |     baz : str = FOO
  |                 ^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).

# CPYTHON

(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm/Issue2030)───────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s012)─┐
└─(16:45:19 on brian-lasr ✹ ✭)──> PYTHONPATH='../../../src/runtime/lpython' python issue2030.py                                                       2 ↵ ──(Sun,Jun25)─┘
(lp) ┌─(~/CLionProjects/lpython/lasr/LP-pycharm/Issue2030)───────────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s01

**Comment by Smit-create** [comment]
This is because AnnAssign is skipped in SymbolTable visitor.

**Comment by certik** [comment]
@rebcabin if we allow the example you wrote above, then I think we should also allow:
```python
from dataclasses import dataclass

FOO : list[str] = ['foo', "bar"]

@dataclass
class bar:
    baz : list[str] = FOO

b = bar()
print(b)
```
But this is not allowed even in CPython:
```console
Traceback (most recent call last):
  File "/Users/ondrej/repos/lpython/src/libasr/a.py", line 6, in <module>
    class bar:
  File "/Users/ondrej/mambaforge/envs/lp/lib/python3.10/dataclasses.py", line 1185, in dataclass
    return wrap(cls)
  File "/Users/ondrej/mambaforge/envs/lp/lib/python3.10/dataclasses.py", line 1176, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/Users/ondrej/mambaforge/envs/lp/lib/python3.10/dataclasses.py", line 956, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
  File "/Users/ondrej/mambaforge/envs/lp/lib/python3.10/dataclasses.py", line 813, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'list'> for field baz is not allowed: use default_factory
```

What I recommend doing is to only allow compile time constants as initializers, at least for now. Let's get that done, then later we can see if we need to extend it. So the following:
```python
from lpython import dataclass

FOO : str = 'foo'

@dataclass
class bar:
    baz : str = FOO
```
Should give an error message. But you could do this:
```python
from lpython import dataclass

FOO : Const[str] = 'foo'

@dataclass
class bar:
    baz : str = FOO
```

**Comment by certik** [comment]
In C++, initializers inside a function act like an assignment, using the runtime current value of a variable, as can be checked by:
```c++
#include <iostream>

int main() {
    int y = 5;
    y = 6;
    int x = y + 5;
    std::cout << "x: " << x << std::endl;
    std::cout << "y: " << y << std::endl;
}
```
So this is consistent with how LPython handles it.
