### ISSUE TITLE
Compile assert with `dict[str, tuple[list[i32], str]]`

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#2037]
attempting a workaround for #2036 

offending code:

```python
from lpython import (i32, Union)

foo : dict[str, tuple[list[i32], str]]

foo = {'ttype': ([], 'dimensions'),
       'contents' : ([1, 2], '')}
```

run: 

```bash
/Users/brian/CLionProjects/lpython/src/bin/python /Users/brian/CLionProjects/lpython/lasr/LP-pycharm/issue2034.py 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 1844
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/Users/brian/CLionProjects/lpython/src/bin/lpython.cpp", line 783
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, *ast, diagnostics, compiler_options,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7536
    auto res2 = body_visitor(al, lm, *ast_m, diagnostics, unit, main_module,
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7489
    b.visit_Module(ast);
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4620
    visit_stmt(*x.m_body[i]);
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1883
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1755
    case stmtType::Delete: { v.visit_Delete((const Delete_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4929
    is_c_p_pointer_call = false;
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1910
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1789
    case exprType::IfExp: { v.visit_IfExp((const IfExp_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 5941
    visit_expr(*x.m_values[i]);
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1910
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/brian/CLionProjects/lpython/src/lpython/python_ast.h", line 1815
    case exprType::List: { v.visit_List((const List_t &)x); return; }
  File "/Users/brian/CLionProjects/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3236
    this->visit_expr(*x.m_elts[i]);
  File "/Users/brian/CLionProjects/lpython/src/libasr/asr_utils.h", line 34
    return ASR::down_cast<ASR::expr_t>(f);
  File "/Users/brian/CLionProjects/lpython/src/libasr/asr.h", line 40
    LCOMPILERS_ASSERT(f != nullptr);
AssertFailed: f != nullptr
```

**Comment by rebcabin** [comment]
Removing Blocker tag. See also #2038 

workaround : 

```python
@dataclass
class FullFormValue:
    list_i32 : list[i32]
    string   : str

foo : dict[str, FullFormValue]

ttype    : FullFormValue = FullFormValue([], 'dimensions')
contents : FullFormValue = FullFormValue([1, 2], '')

foo = {'ttype'   : ttype,
       'contents': contents}
```

**Comment by Smit-create** [comment]
Yeah, you're right. Empty Lists are a bit hackish in `lpython`. We need to find a robust way to handle them.
