### ISSUE TITLE
C backend bug: ~ (not) operation

### ISSUE THREAD

**Issue by ronnuriel** [lcompilers/lpython#2054]
Hey, not op seems to be generated wrong:
```
def foo(grp: u16) -> u16:
    i: u16 = ~(u16(grp))

    return i


def foo2() -> u16:
    i: u16 = ~(u16(0xffff))

    return i

def foo3() -> u16:
    i: u16 = ~(u16(0xffff))

    return ~i

assert foo(u16(0)) == u16(0xffff), foo(u16(0))
assert foo(u16(0xffff)) == u16(0), foo(u16(0xffff))
assert foo2() == u16(0), foo2()
assert foo3() == u16(0xffff), foo3()
```

output:
```
#include <inttypes.h>

#include <stdlib.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <lfortran_intrinsics.h>


// Implementations
uint16_t foo(uint16_t grp)
{
    uint16_t _lpython_return_variable;
    uint16_t i;
    i = grp;
    _lpython_return_variable = i;
    return _lpython_return_variable;
}

uint16_t foo2()
{
    uint16_t _lpython_return_variable;
    uint16_t i;
    i = (uint16_t)(65535);
    _lpython_return_variable = i;
    return _lpython_return_variable;
}

uint16_t foo3()
{
    uint16_t _lpython_return_variable;
    uint16_t i;
    i = (uint16_t)(65535);
    _lpython_return_variable = i;
    return _lpython_return_variable;
}

void _lpython_main_program()
{
    ASSERT_MSG(foo((uint16_t)(0)) == (uint16_t)(65535), foo((uint16_t)(0)));
    ASSERT_MSG(foo((uint16_t)(65535)) == (uint16_t)(0), foo((uint16_t)(65535)));
    ASSERT_MSG(foo2() == (uint16_t)(0), foo2());
    ASSERT_MSG(foo3() == (uint16_t)(65535), foo3());
}

int main(int argc, char* argv[])
{
    _lpython_set_argv(argc, argv);
    _lpython_main_program();
    return 0;
}
```

Please add them to Lpython tests

**Comment by certik** [comment]
The first three asserts fail in CPython also, so that should not work in LPython. The last one succeeds in CPython but fails in LPython, here is a minimal test:
```python
from lpython import u16

def foo(grp: u16) -> u16:
    i: u16 = ~(u16(grp))
    return i


def foo2() -> u16:
    i: u16 = ~(u16(0xffff))
    return i

def foo3() -> u16:
    i: u16 = ~(u16(0xffff))
    return ~i

#assert foo(u16(0)) == u16(0xffff), foo(u16(0))
#assert foo(u16(0xffff)) == u16(0), foo(u16(0xffff))
#assert foo2() == u16(0), foo2()
assert foo3() == u16(0xffff), foo3()
```
I am getting:
```console
$ lpython expr_17.py 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 1844
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir,
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 809
    res = fe.get_llvm3(*asr, pass_manager, diagnostics, infile);
  File "/Users/ondrej/repos/lpython/src/lpython/python_evaluator.cpp", line 58
    run_fn, infile);
  File "/Users/ondrej/repos/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 8561
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "../libasr/asr.h", line 4869
  File "../libasr/asr.h", line 4845
  File "../libasr/asr.h", line 4870
  File "../libasr/asr.h", line 4584
  File "/Users/ondrej/repos/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 1359
    ASR::symbol_t *mod = x.m_global_scope->get_symbol(item);
  File "../libasr/asr.h", line 4872
  File "../libasr/asr.h", line 4593
  File "/Users/ondrej/repos/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 2964
    finish_module_init_function_prototype(x);
  File "/Users/ondrej/repos/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 4359
    if (ASRUtils::get_FunctionType(s)->n_type_params == 0) {
  File "/Users/ondrej/repos/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 3965
    visit_procedures(x);
  File "/Users/ondrej/repos/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 4311
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4889
  File "../libasr/asr.h", line 4642
  File "/Users/ondrej/repos/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 6353
    llvm_utils->create_if_else(tmp, []() {}, [=]() {
  File "../libasr/codegen/llvm_utils.h", line 179
  File "/Users/ondrej/repos/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 6361
    if (x.m_msg) {
  File "../libasr/asr.h", line 41
AssertFailed: is_a<T>(*f)
$ lpython --show-c expr_17.py
#include <inttypes.h>

#include <stdlib.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <lfortran_intrinsics.h>


// Implementations
uint16_t foo3()
{
    uint16_t _lpython_return_variable;
    uint16_t i;
    i = (uint16_t)(65535);
    _lpython_return_variable = i;
    return _lpython_return_variable;
}

void _lpython_main_program()
{
    ASSERT_MSG(foo3() == (uint16_t)(65535), foo3());
}

int main(int argc, char* argv[])
{
    _lpython_set_argv(argc, argv);
    _lpython_main_program();
    return 0;
}
```

**Comment by ronnuriel** [comment]
@certik Cpython failed because Lpython type u16 is not casting to u16:

```
np.uint16(-1) -> 0xffff
u16(-1) -> -1
```

**Comment by certik** [comment]
I see --- it's a double bug (both in our lpython.py for CPython and in LPython).

Thank for this report, we'll fix it all.
