### ISSUE TITLE
Bug: Casting u32 to u16

### ISSUE THREAD

**Issue by ronnuriel** [lcompilers/lpython#2097]
Cannot cast u32 to u16
```
x : u32 = u32(0)
y: u16 = u16(x)
```
Error:
```
semantic error: Type mismatch in annotation-assignment, the types must be compatible
 --> /Users/ronnuriel/Desktop/testlpython.py:9:1
  |
9 | y: u16 = u16(x)
  | ^            ^ type mismatch ('u16' and 'u32')

```

The following works:
```
x : i32 = i32(0)
y: i16 = i16(x)
```

**Comment by ronnuriel** [comment]
I think that the bug might be under:
`python_ast_to_asr.cpp`

need to add a pair: 
```
    // Data structure which contains casting rules for non-equal
    // intrinsic types defined in ASR
    const std::map<std::pair<ASR::ttypeType, ASR::ttypeType>, ASR::cast_kindType>& type_rules = {
```

**Comment by certik** [comment]
Try the latest master I think it might already be fixed. If you do this at the global scope I get:
```
$ lpython a.py 
code generation error: Variable type not supported 1
 --> a.py:1:1
  |
1 | x : u32 = u32(0)
  | ^^^^^^^^^^^^^^^^ 
```
The global scope is a little fragile as it gets transformed internally into functions. But If you do this:
```python
def f():
    x : u32 = u32(0)
    y: u16 = u16(x)
    print(x, y)

f()
```
Then it works:
```console
$ lpython a.py
0 0
```

**Comment by Shaikh-Ubaid** [comment]
`lpython` works, but `CPython` seems to fail:

```bash
$ cat examples/expr2.py 
from lpython import u16, u32

def f():
    x : u32 = u32(0)
    y: u16 = u16(x)
    print(x, y)

f()
$ python examples/expr2.py           
Traceback (most recent call last):
  File "/Users/ubaid/Desktop/OpenSource/lpython/examples/expr2.py", line 8, in <module>
    f()
  File "/Users/ubaid/Desktop/OpenSource/lpython/examples/expr2.py", line 5, in f
    y: u16 = u16(x)
  File "/Users/ubaid/Desktop/OpenSource/lpython/src/runtime/lpython/lpython.py", line 193, in __call__
    return self._convert(arg)
  File "/Users/ubaid/Desktop/OpenSource/lpython/src/runtime/lpython/lpython.py", line 169, in <lambda>
    "u16": lambda x: UnsignedInteger(16, x),
  File "/Users/ubaid/Desktop/OpenSource/lpython/src/runtime/lpython/lpython.py", line 21, in __init__
    raise ValueError(f"Bit width mismatch: {bit_width} vs {value.bit_width}")
ValueError: Bit width mismatch: 16 vs 32
```

Fixed here https://github.com/lcompilers/lpython/pull/2098.
