### ISSUE TITLE
ASR verify failure

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#2141]
```
ASR verify pass error: ASR verify: Array type in pointer must have deferred shape
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 1767
    return emit_c(arg_file, runtime_library_dir, lpython_pass_manager,
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 333
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, nullptr, *ast, diagnostics, compiler_options, true, "", infile);
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7684
    throw LCompilersException("Verify failed");
LCompilersException: Verify failed
```

**Comment by certik** [comment]
Here is a minimal reproducible example:
```python
from lpython import i16, i32, CPtr, c_p_pointer, Pointer   
from numpy import array


def initialize_A(n: i32, a: CPtr) -> None:
    A: Pointer[i16[n]] = c_p_pointer(a, i16[:], array([n]))
    i: i32
    for i in range(n):
        A[i] = i16(i);  
```
This gives:
```console
$ lpython --show-asr a.py 
ASR verify pass error: ASR verify: Array type in pointer must have deferred shape
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 1760
    return emit_asr(arg_file, lpython_pass_manager, runtime_library_dir,
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 233
    r = LCompilers::LPython::python_ast_to_asr(al, lm, nullptr, *ast, diagnostics,
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 7684
    throw LCompilersException("Verify failed");
LCompilersException: Verify failed
```
The fix is to use `Pointer[i16[:]]`, which is the right approach.

The bug is that LPython should give an actual compiler errormessage, not a verify failure.

Another bug is that a verify failure should still show like an error message, just like in LFortran. Given this, it's not a blocker anymore.

**Comment by certik** [comment]
Another issue with this:

* this only manifests in Debug build of Lpython that runs ASR verify, but conda-forge LPython is build in Release mode which does not run verify, so I didn't see this bug.

Solution: add a flag to `lpython` to run verify (even in Release mode), this flag is off by default (for performance in Release mode). The debug mode would always run verify.

**Comment by certik** [comment]
Of this issue, the highest priority is to report a regular error message for usage like this:
```python
    A: Pointer[i16[n*m]] = c_p_pointer(a, i16[:], array([n*m]))
```
Which currently gets unnoticed in Release mode, which is a mistake, especially since this used to be allowed. Must not compile.
