### ISSUE TITLE
lpython compiler fails when dereferencing a pointer

### ISSUE THREAD

**Issue by emoise-gsi** [lcompilers/lpython#2165]
Fails on master branch, commit: 71d654a9fd4e5e427ed98be3b73ccf39cc76e1bb

The following code does not compile:

**dereference_bug.py**
```
from lpython import Pointer, c_p_pointer, ccallback, CPtr, u16, i32

@ccallback
def foo(p_void : CPtr, idx : i32) -> None:
    p_u16 : Pointer[u16] = c_p_pointer(p_void, u16)
    val : u16 = p_u16[idx]
```
compilation command:
**lpython dereference_bug.py --show-c**

Produces the following error:
ASR verify pass error: ASR verify: The variable in ArrayItem must be an array, not a scalar
Internal Compiler Error: Unhandled exception
BFD: DWARF error: section .debug_info is larger than its filesize! (0x93ef57 vs 0x530ea0)
Traceback (most recent call last):
  Binary file "/home/emoise/lpython/src/bin/lpython", in _start()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_start_main()
  File "/home/emoise/lpython/src/bin/lpython.cpp", line 1788, in ??
    return emit_c(arg_file, runtime_library_dir, lpython_pass_manager,
  File "/home/emoise/lpython/src/bin/lpython.cpp", line 339, in ??
    r1 = LCompilers::LPython::python_ast_to_asr(al, lm, nullptr, *ast, diagnostics, compiler_options, true, "__main__", infile);
LCompilersException: Verify failed

Note that if we comment out the last line, i.e.

```
from lpython import Pointer, c_p_pointer, ccallback, CPtr, u16, i32

@ccallback
def foo(p_void : CPtr, idx : i32) -> None:
    p_u16 : Pointer[u16] = c_p_pointer(p_void, u16)
    # val : u16 = p_u16[idx]
```
The compilation succeeds and produces the following valid c code

```
#include <inttypes.h>

#include <stdlib.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <lfortran_intrinsics.h>


// Implementations
void foo(void* p_void, int32_t idx)
{
    uint16_t * p_u16;
    p_u16 = (uint16_t*) p_void;
}

int main(int argc, char* argv[])
{
    _lpython_set_argv(argc, argv);
    return 0;
}
```

**Comment by emoise-gsi** [comment]
Not a blocker, I can work around this

**Comment by Shaikh-Ubaid** [comment]
This seems to work with the following diff (We declared it as an array):
```bash
$ git diff
diff --git a/examples/expr2.py b/examples/expr2.py
index 696a9a9c1..7d9438b09 100644
--- a/examples/expr2.py
+++ b/examples/expr2.py
@@ -1,6 +1,7 @@
 from lpython import Pointer, c_p_pointer, ccallback, CPtr, u16, i32
+from numpy import array
 
 @ccallback
 def foo(p_void : CPtr, idx : i32) -> None:
-    p_u16 : Pointer[u16] = c_p_pointer(p_void, u16)
-    # val : u16 = p_u16[idx]
+    p_u16 : Pointer[u16[:]] = c_p_pointer(p_void, u16[:], array([1]))
+    val : u16 = p_u16[idx]
```
```bash
$ cat examples/expr2.py    
from lpython import Pointer, c_p_pointer, ccallback, CPtr, u16, i32
from numpy import array

@ccallback
def foo(p_void : CPtr, idx : i32) -> None:
    p_u16 : Pointer[u16[:]] = c_p_pointer(p_void, u16[:], array([1]))
    val : u16 = p_u16[idx]
$ lpython examples/expr2.py
$ lpython examples/expr2.py --backend c
$ 
```

**Comment by certik** [comment]
@emoise-gsi you have to create an array if you want to index it, so the `Pointer[u16[:]]` creates a pointer to an array of u16 elements and then you can index into it. And you use the `c_p_pointer` construct to create that array and the `array([1])` part in @Shaikh-Ubaid's comment above is the dimension of the array. We currently do not check it, but we will eventually. If you know the dimension, you should set it correctly. If you don't know it, you can set some large number (and obviously it can segfault if you index out of the allocated memory from C).

**Comment by emoise-gsi** [comment]
Thanks. It works for u16 (and I assume for other "built-in" types). How about user defined types? For example, test.py:
```
from lpython import Pointer, c_p_pointer, CPtr, u16, ccallable, packed, dataclass, empty_c_void_p
from numpy import array

@ccallable
@packed
@dataclass
class ab:
    a: u16
    b: u16

x : CPtr = empty_c_void_p()
p_ab : Pointer[ab[:]] = c_p_pointer(x, ab[:], array([1]))
```
This compiles just fine but it breaks down in emulation mode:
(in lpython v0.18.3)
**$ PYTHONPATH=/home/emoise/lpython/src/runtime/lpython/ python /home/emoise/lpython/bug4/test.py** 
results in

Traceback (most recent call last):
  File "/home/emoise/lpython/bug4/test.py", line 12, in <module>
    p_ab : Pointer[ab[:]] = c_p_pointer(x, ab[:], array([1]))
TypeError: '_ctypes.PyCStructType' object is not subscriptable

**Comment by emoise-gsi** [comment]
I would also like to take the address of an element in in p_ab. For example:
`p : CPtr = some_func_to_take_address(p_ab[5])`

**Comment by certik** [comment]
Thanks @emoise-gsi for the bug reports / feature requests. We'll investigate.
