### ISSUE TITLE
Needs Implementation: Increment in Python

### ISSUE THREAD

**Issue by Abdullahjavednesar** [lcompilers/lpython#217]
Sample:
```
def main0():
    i:i64
    i = 1
    i+=1
    print(i)

main0()
```

Exception:
```
; ModuleID = 'LFortran'
source_filename = "LFortran"

@0 = private unnamed_addr constant [6 x i8] c"%lld\0A\00", align 1

define void @_lfortran_main_program() {
.entry:
  call void @main0()
  br label %return

return:                                           ; preds = %.entry
  ret void
}

define void @main0() {
.entry:
  %i = alloca i64, align 8
  store i64 1, i64* %i, align 4
  %0 = load i64, i64* %i, align 4
  %1 = trunc i64 %0 to i32
  %2 = add i32 %1, 1
  store i32 %2, i64* %i, align 4
  %3 = load i64, i64* %i, align 4
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @0, i32 0, i32 0), i64 %3)
  br label %return

return:                                           ; preds = %.entry
  ret void
}

declare void @_lfortran_printf(i8*, ...)

define i32 @main() {
.entry:
  call void @_lfortran_main_program()
  ret i32 0
}
Traceback (most recent call last):
  File "/Users/anesa00/owork/lpython/src/bin/lpython.cpp", line 1540
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir, compiler_options);
  File "/Users/anesa00/owork/lpython/src/bin/lpython.cpp", line 742
    res = fe.get_llvm3(*asr, diagnostics);
  File "/Users/anesa00/owork/lpython/src/lpython/fortran_evaluator.cpp", line 309
    if (res.ok) {
  File "/Users/anesa00/owork/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 4073
    diagnostics.diagnostics.push_back(diag::Diagnostic(msg,
code generation error: asr_to_llvm: module failed verification. Error:
Stored value type does not match pointer operand type!
  store i32 %2, i64* %i, align 4
 i64


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

**Comment by certik** [comment]
It looks like the ASR is wrong:
```
               (= 
                  (Var 2 i) 
                  (BinOp 
                     (ImplicitCast 
                        (Var 2 i) 
                        IntegerToInteger 
                        (Integer 4 []) ()) 
                     Add (ConstantInteger 1 
                     (Integer 4 [])) 
                     (Integer 4 []) () ()) ()) 
```
It's casting the integer from 64bit to 32bit, which is what then causes the LLVM failure. In the above case everything should stay 64bit.

Thanks for the report!
