### ISSUE TITLE
Ubuntu 22.04: it takes 3s to generate a stacktrace

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#2371]
```
$ time ../src/bin/lpython expr2.py --backend=wasm_x64  -o expr2.wasm
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/ondrej/repos/lpython/src/bin/lpython", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/ondrej/repos/lpython/src/bin/lpython.cpp", line 1857, in ??
    err = compile_to_binary_wasm_to_x86(arg_file, outfile,
  File "/home/ondrej/repos/lpython/src/bin/lpython.cpp", line 1088, in ??
    LCompilers::Result<int> res = LCompilers::wasm_to_x64(r3.result, al,  outfile, time_report, diagnostics);
  File "/home/ondrej/repos/lpython/src/libasr/codegen/wasm_to_x64.cpp", line 681, in LCompilers::wasm_to_x64(LCompilers::Vec<unsigned char>&, Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::diag::Diagnostics&)
    x64_visitor.gen_x64_bytes();
  File "/home/ondrej/repos/lpython/src/libasr/codegen/wasm_to_x64.cpp", line 608, in LCompilers::wasm::X64Visitor::gen_x64_bytes()
    decode_instructions();
  File "/home/ondrej/repos/lpython/src/libasr/../libasr/wasm_visitor.h", line 995, in LCompilers::WASM_INSTS_VISITOR::BaseWASMVisitor<LCompilers::wasm::X64Visitor>::decode_instructions()
    self().visit_I32Load(mem_align, mem_offset);
LCompilersException: visit_I32Load() not implemented

real	0m3,086s
user	0m2,766s
sys	0m0,320s
```
This is unacceptably slow. I think we need to use the same approach as we use on macOS, our own handling of these stacktraces using llvm-dwarf so that they are quick. If I remember well, these stacktraces used to be fast, but somehow they are now slow in Ubuntu.

**Comment by Pranavchiku** [comment]
> but somehow they are now slow in Ubuntu.

I faced this problem quite often in Ubuntu, sometimes it even takes more than 3 seconds.

**Comment by certik** [comment]
> I faced this problem quite often in Ubuntu, sometimes it even takes more than 3 seconds.

Yes, that's unusable.
