### ISSUE TITLE
Needs Implementation: floor division operator for float types

### ISSUE THREAD

**Issue by Abdullahjavednesar** [lcompilers/lpython#255]
Example:
```
def f():
    i: f64
    i = 300.27
    print(i//1.0)

f()
```
Error Stacktrace:
```
>>./src/bin/lpython integration_tests/test_math1.py --show-stacktrace
; ModuleID = 'LFortran'
source_filename = "LFortran"

@0 = private unnamed_addr constant [9 x i8] c"%23.17f\0A\00", align 1

define void @_lfortran_main_program() {
.entry:
  call void @f()
  br label %return

return:                                           ; preds = %.entry
  ret void
}

define void @f() {
.entry:
  %i = alloca double, align 8
  store double 3.002700e+02, double* %i, align 8
  %0 = load double, double* %i, align 8
  %1 = fptosi double %0 to i64
  %2 = fdiv i64 %1, 1
  %3 = fpext i64 %2 to double
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @0, i32 0, i32 0), double %3)
  br label %return

return:                                           ; preds = %.entry
  ret void
}

declare void @_lfortran_printf(i8*, ...)

define i32 @main() {
.entry:
  call void @_lfortran_main_program()
  ret i32 0
}
Traceback (most recent call last):
  File "/Users/anesa00/owork/lpython/src/bin/lpython.cpp", line 1540
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir, compiler_options);
  File "/Users/anesa00/owork/lpython/src/bin/lpython.cpp", line 742
    res = fe.get_llvm3(*asr, diagnostics);
  File "/Users/anesa00/owork/lpython/src/lpython/fortran_evaluator.cpp", line 309
    if (res.ok) {
  File "/Users/anesa00/owork/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 4073
    diagnostics.diagnostics.push_back(diag::Diagnostic(msg,
code generation error: asr_to_llvm: module failed verification. Error:
Floating-point arithmetic operators only work with floating-point types!
  %2 = fdiv i64 %1, 1
FPExt only operates on FP
  %3 = fpext i64 %2 to double



Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

**Comment by Smit-create** [comment]
The following diff should fix the issue:
```diff
diff --git a/src/lpython/semantics/python_ast_to_asr.cpp b/src/lpython/semantics/python_ast_to_asr.cpp
index f2857d8e2..53613abef 100644
--- a/src/lpython/semantics/python_ast_to_asr.cpp
+++ b/src/lpython/semantics/python_ast_to_asr.cpp
@@ -1410,11 +1410,17 @@ public:
                     left = ASR::down_cast<ASR::expr_t>(ASR::make_ImplicitCast_t(
                         al, left->base.loc, left, ASR::cast_kindType::RealToInteger, dest_type,
                         value));
+                    left = ASR::down_cast<ASR::expr_t>(ASR::make_ImplicitCast_t(
+                        al, left->base.loc, left, ASR::cast_kindType::IntegerToReal, dest_type,
+                        value));
                 }
                 if (ASRUtils::is_real(*right_type)) {
                     right = ASR::down_cast<ASR::expr_t>(ASR::make_ImplicitCast_t(
                         al, right->base.loc, right, ASR::cast_kindType::RealToInteger, dest_type,
                         value));
+                    right = ASR::down_cast<ASR::expr_t>(ASR::make_ImplicitCast_t(
+                        al, right->base.loc, right, ASR::cast_kindType::IntegerToReal, dest_type,
+                        value));
                 }
 
             } else { // real divison in python using (`/`)
```
But I'm still not sure how we can initiate to call integer division in llvm instead of `fdiv` in this case.

**Comment by Abdullahjavednesar** [comment]
@Smit-create thanks for fix suggestion. BTW how did you trace back to find the root cause?
