### ISSUE TITLE
The Windows tests fail, but the CI passes

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#2624]
https://github.com/lcompilers/lpython/actions/runs/8403614204/job/23014303486#step:13:1875

**Comment by certik** [comment]
The same error happens in LFortran also. However, it seems it might be some bug in deallocation in xonsh, not necessarily meaning that our LPython tests are failing.
```
Exception ignored in: <function _removeHandlerRef at 0x000001E4706F9EA0>
Traceback (most recent call last):
  File "C:\Miniconda\envs\test\lib\logging\__init__.py", line 836, in _removeHandlerRef
  File "C:\Miniconda\envs\test\lib\site-packages\xonsh\tracer.py", line 87, in trace
TypeError: 'NoneType' object is not callable
```

**Comment by Shaikh-Ubaid** [comment]
I think it is related to multi-processing. Shall we try running tests on windows serially?
