### ISSUE TITLE
Implement `ConstantArray` visitor 

### ISSUE THREAD

**Issue by namannimmo10** [lcompilers/lpython#270]
Before we make these NumPy functions work on arrays, we need `np.array`:
```diff
diff --git a/integration_tests/test_numpy_02.py b/integration_tests/test_numpy_02.py
index 656da182..2a49bd9c 100644
--- a/integration_tests/test_numpy_02.py
+++ b/integration_tests/test_numpy_02.py
@@ -125,6 +125,10 @@ def linspace(start: f64, stop: f64, num: i32) -> f64[num]:
         A[i] = start + (stop-start)*i/(num-1)
     return A

+def array(a: i32[:], n: i32) -> i32[n]:
+    A: i32[n]
+    return A
+
 def test_zeros():
     a: f64[4]
     a = zeros(4)
@@ -223,6 +227,11 @@ def test_linspace():
     assert abs(a[2] - 5.0) < eps
     assert abs(a[3] - 7.0) < eps

+def test_array():
+    a: i32[3]
+    a = array([4, 5, 6], 3)
+    assert a[0] == 4
+
 def check():
     test_zeros()
     test_ones()
@@ -231,5 +240,6 @@ def check():
     test_exp()
     test_fabs()
     test_linspace()
+    test_array()

 check()
```
```
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/namannimmo/Applications/oss/lpython/src/bin/lpython.cpp", line 745
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir, compiler_options);
  File "/Users/namannimmo/Applications/oss/lpython/src/bin/lpython.cpp", line 262
    res = fe.get_llvm3(*asr, diagnostics);
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/fortran_evaluator.cpp", line 57
    run_fn);
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 4051
    v.nested_func_types = pass_find_nested_vars(asr, context,
  File "../libasr/asr.h", line 2276
  File "../libasr/asr.h", line 2254
  File "../libasr/asr.h", line 2277
  File "../libasr/asr.h", line 2114
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 890
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 2279
  File "../libasr/asr.h", line 2124
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 1964
    visit_procedures(x);
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 2037
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 2291
  File "../libasr/asr.h", line 2165
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 3883
    std::vector<llvm::Value *> args2 = convert_call_args(x, m_name);
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 3743
    this->visit_expr_wrapper(x.m_args[i]);
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 2489
    this->visit_expr(*x);
  File "../libasr/asr.h", line 2321
  File "../libasr/asr.h", line 2186
  File "../libasr/asr.h", line 2332
LFortranException: visit_ConstantArray() not implemented
Command '../src/bin/lpython test_numpy_02.py -o tmp/test_numpy_02' failed
```

_Originally posted by @namannimmo10 in https://github.com/lcompilers/lpython/issues/263#issuecomment-1073119235_

**Comment by certik** [comment]
Also this will not work with CPython:
```
def array(a: i32[:], n: i32) -> i32[n]:
    A: i32[n]
    return A
```
Because the `A: i32[n]` annotation is ignored, so `return A` will give a runtime error. The `array` function as defined would be implemented by:
```
def array(a: i32[:], n: i32) -> i32[n]:
    return a
```
But the main utility is to call it on lists. With our current design to treat lists effectively as arrays, we don't even need the `array` function.  For numerical types like lists of `[[1, 2], [2, 3], [4, 5]]`, those can be converted to arrays automatically. 

Lists and NumPy arrays have slightly different operations on them, such as for lists:
```
>>> [1, 2] + [2, 3]
[1, 2, 2, 3]
```
But for arrays:
```
In [3]: array([1, 2]) + array([2, 3])
Out[3]: array([3, 5])
```
Both operations can be represented in ASR, but I wonder if we need to store some metadata with the array noting that it is actually a "list" in Python, so that the LPython frontend can interpret the operations like "+" correctly.

Then there is special semantics with creating a function that accepts a list, such as `array`, we need some way to specify that.

It almost seems that the cleanest solution is to actually represent a list in ASR as a dedicated type. It could differ from a multidimensional array in that it could hold "allocatable arrays" as elements, thus it could hold allocatable strings and arrays, and thus represent different lengths for each element. In that case, list is effectively a container, while array is not.

**Comment by namannimmo10** [comment]
@certik -- will you move the LLVM backend code from LFortran to LPython soon?  We can close this, and also start implementing NumPy functions returning arrays.

**Comment by certik** [comment]
Done in #323.
