### ISSUE TITLE
Floor division giving incorrect results

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#318]
Runtime:
```console
$ cat a.py 
def f():
    x: i32
    x = 5
    print(x//2)
    print(-x//2)

f()
$ lpython a.py && ./a.out 
2
2147483645
$ python a.py 
2
-3
```
Compile time:
```console
$ cat a.py 
def f():
    print(5//2)
    print(-5//2)

f()
$ lpython a.py && ./a.out
2
-2
$ python a.py            
2
-3
```

Both are wrong for the negative numbers compared to the reference CPython result.

**Comment by certik** [comment]
The compile time value is computed by:
```c++
            if (ASRUtils::is_integer(*dest_type)) {
                int64_t left_value = ASR::down_cast<ASR::ConstantInteger_t>(
                                                    ASRUtils::expr_value(left))->m_n;
                int64_t right_value = ASR::down_cast<ASR::ConstantInteger_t>(
                                                    ASRUtils::expr_value(right))->m_n;
                int64_t result;
                switch (op) {
                    case (ASR::binopType::Add): { result = left_value + right_value; break; }
                    case (ASR::binopType::Sub): { result = left_value - right_value; break; }
                    case (ASR::binopType::Mul): { result = left_value * right_value; break; }
                    case (ASR::binopType::Div): { result = left_value / right_value; break; }
                    case (ASR::binopType::Pow): { result = std::pow(left_value, right_value); break; }
                    default: { LFORTRAN_ASSERT(false); } // should never happen
                }
                value = ASR::down_cast<ASR::expr_t>(ASR::make_ConstantInteger_t(
                    al, loc, result, dest_type));
            }
```
Which looks correct. I wonder if integer division in C gives different results than the `//` operator in Python.

**Comment by certik** [comment]
This patch makes the compile time and runtime behavior consistent:
```diff
--- a/src/libasr/codegen/asr_to_llvm.cpp
+++ b/src/libasr/codegen/asr_to_llvm.cpp
@@ -2848,7 +2848,7 @@ public:
                     break;
                 };
                 case ASR::binopType::Div: {
-                    tmp = builder->CreateUDiv(left_val, right_val);
+                    tmp = builder->CreateSDiv(left_val, right_val);
                     break;
                 };
                 case ASR::binopType::Pow: {

```
But now both return:
```
2
-2
```
So the integer division behaves differently for negative values...

So it seems we'll have to implement this using a function call even for integers. I didn't realize this.

**Comment by certik** [comment]
I checked C, Fortran and LLVM and they all return (-5/2 == -2), and it doesn't matter how you put the parenthesis in the expression, so: -5/2 = (-5)/2 = -(5/2) = -2.

Python, on the other hand, behaves like this: -5/2 = -3 = (-5)/2, but -(5/2) = -2.

So I think we need to create our own function for division of integers that returns -3.

**Comment by certik** [comment]
Finally, this also fails, but differently:
```console
$ cat a.py 
def f():
    print(5.0//2)
    print(-5.0//2)

f()
$ lpython a.py
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 799
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir, compiler_options);
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 291
    r1 = LFortran::LPython::python_ast_to_asr(al, *ast, diagnostics, true,
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2727
    LFORTRAN_ASSERT(asr_verify(*tu));
  File "/Users/ondrej/repos/lpython/src/libasr/asr_verify.cpp", line 491
    v.visit_TranslationUnit(unit);
  File "/Users/ondrej/repos/lpython/src/libasr/asr_verify.cpp", line 110
    for (auto &a : x.m_global_scope->scope) {
  File "../libasr/asr.h", line 2398
  File "../libasr/asr.h", line 2240
  File "/Users/ondrej/repos/lpython/src/libasr/asr_verify.cpp", line 208
    visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 2410
  File "../libasr/asr.h", line 2272
  File "../libasr/asr.h", line 2651
  File "../libasr/asr.h", line 2443
  File "../libasr/asr.h", line 2303
  File "/Users/ondrej/repos/lpython/src/libasr/asr_verify.cpp", line 447
    x.base.base.loc);
  File "/Users/ondrej/repos/lpython/src/libasr/asr_verify.cpp", line 60
    require(cond, msg);
  File "/Users/ondrej/repos/lpython/src/libasr/asr_verify.cpp", line 49
    throw LFortranException("ASR verify failed: " + error_msg);
LFortranException: ASR verify failed: 19:24: FunctionCall::m_name `_lpython_floordiv` cannot point outside of its symbol table
```
So it looks like there is quite a lot of bugs to fix here. :)

**Comment by Smit-create** [comment]
> So the `_lpython_builtin_floordiv` must be implemented both for floating point and for integers.

Yeah, that would probably fix this issue.

**Comment by Smit-create** [comment]
> So the `_lpython_builtin_floordiv` must be implemented both for floating point and for integers.

Yeah, that would probably fix this issue.

> So it looks like there is quite a lot of bugs to fix here. :)

Yeah, seems like some `symtab` issue. Will have a look at it.
