### ISSUE TITLE
New tokenizer fails when there are multiple indentations

### ISSUE THREAD

**Issue by akshanshbhatt** [lcompilers/lpython#358]
```py
class Test:
    def foo(a):
        if a == 'foo':
            return 'foo'
        return 'bar'
```

This code, when run with lpython binary, gives an error when I pass `--show-tokens` flag :

```sh
❯ src/bin/lpython --show-tokens examples/test_file.py
Traceback (most recent call last):
  File "/Users/akshansh/Documents/GitHub/lpython/src/bin/lpython.cpp", line 749
    return emit_tokens(arg_file, true, compiler_options);
  File "/Users/akshansh/Documents/GitHub/lpython/src/bin/lpython.cpp", line 92
    auto res = LFortran::tokens(al, input, diagnostics, &stypes, &locations);
  File "tokenizer.re", line 557
  File "tokenizer.re", line 151
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803414c3
Segfault: Signal SIGSEGV (segmentation fault) received
```

Python's tokenizer, on the other hand, gives this output :

```sh
❯ python -m tokenize examples/test_file.py
0,0-0,0:            ENCODING       'utf-8'
1,0-1,5:            NAME           'class'
1,6-1,10:           NAME           'Test'
1,10-1,11:          OP             ':'
1,11-1,12:          NEWLINE        '\n'
2,0-2,4:            INDENT         '    '
2,4-2,7:            NAME           'def'
2,8-2,11:           NAME           'foo'
2,11-2,12:          OP             '('
2,12-2,13:          NAME           'a'
2,13-2,14:          OP             ')'
2,14-2,15:          OP             ':'
2,15-2,16:          NEWLINE        '\n'
3,0-3,8:            INDENT         '        '
3,8-3,10:           NAME           'if'
3,11-3,12:          NAME           'a'
3,13-3,15:          OP             '=='
3,16-3,21:          STRING         "'foo'"
3,21-3,22:          OP             ':'
3,22-3,23:          NEWLINE        '\n'
4,0-4,12:           INDENT         '            '
4,12-4,18:          NAME           'return'
4,19-4,24:          STRING         "'foo'"
4,24-4,25:          NEWLINE        '\n'
5,8-5,8:            DEDENT         ''
5,8-5,14:           NAME           'return'
5,15-5,20:          STRING         "'bar'"
5,20-5,21:          NEWLINE        '\n'
6,0-6,0:            DEDENT         ''
6,0-6,0:            DEDENT         ''
6,0-6,0:            ENDMARKER      ''
```

How can I debug it and find the cause? The error message isn't giving any insight into the problem.
I am willing to fix it.

**Comment by certik** [comment]
To debug this, open the line `File "tokenizer.re", line 151` and see what is going on. You can also run it through a debugger like `lldb`. There is probably a bug there that needs to be fixed.
