### ISSUE TITLE
Raise error if a local var is referenced before assignment

### ISSUE THREAD

**Issue by namannimmo10** [lcompilers/lpython#413]
For this code:
```python
x: i32
x = 10

def main0():
  x += 10
  print(x)


main0()
```
LPython prints `20`.
And CPython gives,
```console
$ python t.py
Traceback (most recent call last):
  File "/Users/namannimmo/Applications/oss/lpython/t.py", line 9, in <module>
    main0()
  File "/Users/namannimmo/Applications/oss/lpython/t.py", line 5, in main0
    x += 10
UnboundLocalError: local variable 'x' referenced before assignment
```

**Comment by rebcabin** [comment]
What about the following, with both compilers?

x: 132
x = 10

def main0():
  global x  # <~~~ only difference
  x += 10
  print(x)
