### ISSUE TITLE
Get run_tests.py working on Windows

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#43]
The current error is (https://github.com/lcompilers/lpython/runs/4854302427?check_suite_focus=true):
```
Traceback (most recent call last):
TEST: doconcurrentloop_01.py
  File "D:\a\lpython\lpython\run_tests.py", line 136, in <module>
    * ast    The JSON metadata differs against reference results
    main()
Reference JSON: tests\reference\ast-doconcurrentloop_01-ed7017b.json
  File "D:\a\lpython\lpython\run_tests.py", line 70, in main
Output JSON:    tests\output\ast-doconcurrentloop_01-ed7017b.json
    run_test("ast", "lpython --show-ast --no-color {infile} -o {outfile}",
Omitting 8 identical items
  File "D:\a\lpython\lpython\compiler_tester\tester.py", line 273, in run_test
Differing items:
    raise RunException("The reference result differs")
{'infile_hash': '1876de8c07abafd35379956fc2dd60ce2572da93cb2c4be90ee1f501'} != {'infile_hash': 'c3efb3a1f583c1cc5f973f560369378d784bf5df6fcace9962624266'}
compiler_tester.tester.RunException: The reference result differs
{'infile': 'tests\\doconcurrentloop_01.py'} != {'infile': 'tests/doconcurrentloop_01.py'}
{'stdout_hash': 'e3f4e27718c6733b68c6d7c395aa3fa8f0309bf02429b402b335efd4'} != {'stdout_hash': 'c13b7d1e89b1f88facf2326435b8d77a42955ac7a3f1e9870362e133'}
Diff against: tests\reference\ast-doconcurrentloop_01-ed7017b.stdout
```

**Comment by Shaikh-Ubaid** [comment]
I am trying to build `lpython` using the same instructions for `lfortran` given in the **Build From Git** section of https://docs.lfortran.org/installation/

On executing the last step `./run_tests.py`, I am receiving the following differing reference results error. Is the testing not implemented yet on Ubuntu or am I missing something?

**Operating System**: Ubuntu 20.04

```
ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/Desktop/GSoC/lpython$ ./run_tests.py 
TEST: doconcurrentloop_01.py
    * ast    The JSON metadata differs against reference results
Reference JSON: tests/reference/ast-doconcurrentloop_01-ed7017b.json
Output JSON:    tests/output/ast-doconcurrentloop_01-ed7017b.json
Omitting 6 identical items
Differing items:
{'stderr': 'ast-doconcurrentloop_01-ed7017b.stderr'} != {'stderr': None}
{'returncode': 1} != {'returncode': 0}
{'stderr_hash': '639a9ffe5a23f23965284099ef3009cbcffc11dc0a6015e08279f74e'} != {'stderr_hash': None}
{'stdout': None} != {'stdout': 'ast-doconcurrentloop_01-ed7017b.stdout'}
{'stdout_hash': None} != {'stdout_hash': 'c094717f0ec2f4766a1692441880820140edd25e35bc52a58ff64196'}
No reference stderr output exists. Stderr:
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LFortranException: Unknown type in deserialize_node()
Traceback (most recent call last):
  File "/home/ubaid/Desktop/GSoC/lpython/./run_tests.py", line 96, in <module>
    main()
  File "/home/ubaid/Desktop/GSoC/lpython/./run_tests.py", line 66, in main
    run_test("ast", "lpython --show-ast --no-color {infile} -o {outfile}",
  File "/home/ubaid/Desktop/GSoC/lpython/compiler_tester/tester.py", line 273, in run_test
    raise RunException("The reference result differs")
compiler_tester.tester.RunException: The reference result differs
```

**Comment by Shaikh-Ubaid** [comment]
Contents of `ast-doconcurrentloop_01-ed7017b.stderr`:
```
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LFortranException: Unknown type in deserialize_node()
```

**Comment by Shaikh-Ubaid** [comment]
I followed the steps given in the `lpython` [readme](https://github.com/lcompilers/lpython#compile-lpython) and I was able to build.
Also, `ctest`, `./run_tests.py` and `./integration_tests/run_tests.py` ran successfully.
