### ISSUE TITLE
Make string indexing work for constant values

### ISSUE THREAD

**Issue by namannimmo10** [lcompilers/lpython#454]
```python
def main():
  print("abc"[2])

main()
```
```console
% python t.py
c
% lpython t.py
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/namannimmo/Applications/oss/lpython/src/bin/lpython.cpp", line 833
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir, compiler_options, time_report);
  File "/Users/namannimmo/Applications/oss/lpython/src/bin/lpython.cpp", line 313
    r1 = LFortran::LPython::python_ast_to_asr(al, *ast, diagnostics, true,
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3181
    auto res2 = body_visitor(al, *ast_m, diagnostics, unit, main_module,
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3117
    b.visit_Module(ast);
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1922
    visit_stmt(*x.m_body[i]);
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/python_ast.h", line 1826
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/python_ast.h", line 1697
    case stmtType::FunctionDef: { v.visit_FunctionDef((const FunctionDef_t &)x); return; }
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1949
    handle_fn(x, *ASR::down_cast<ASR::Subroutine_t>(t));
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1940
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1897
    this->visit_stmt(*m_body[i]);
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/python_ast.h", line 1826
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/python_ast.h", line 1718
    case stmtType::Nonlocal: { v.visit_Nonlocal((const Nonlocal_t &)x); return; }
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2756
    visit_expr(*c->m_args[i]);
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/python_ast.h", line 1853
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/python_ast.h", line 1754
    case exprType::Attribute: { v.visit_Attribute((const Attribute_t &)x); return; }
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1473
    ai.m_right = nullptr;
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/asr.h", line 40
    LFORTRAN_ASSERT(is_a<T>(*f));
AssertFailed: is_a<T>(*f)
```

**Comment by faze-geek** [comment]
Strange that below function works -
```
def main():
  a : str
  a = "abc"
  print(a[2])

main()

(lp) anurag-3:lpython user$ ./src/bin/lpython try.py
(lp) anurag-3:lpython user$ ./a.out
c
```
But the function shown in the issue gives the error as mentioned . It fails in ast to asr transition - 
```
(lp) anurag-3:lpython user$ ./src/bin/lpython try.py --show-asr --indent
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/user/lpython/src/bin/lpython.cpp", line 827
    return emit_asr(arg_file, runtime_library_dir,
  File "/Users/user/lpython/src/bin/lpython.cpp", line 170
    std::cerr << diagnostics.render(input, lm, compiler_options);
  File "/Users/user/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3272
    if (res2.ok) {
  File "/Users/user/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3206
    b.visit_Module(ast);
  File "/Users/user/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2004
    visit_stmt(*x.m_body[i]);
  File "/Users/user/lpython/src/lpython/python_ast.h", line 1862
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/user/lpython/src/lpython/python_ast.h", line 1731
    case stmtType::FunctionDef: { v.visit_FunctionDef((const FunctionDef_t &)x); return; }
  File "/Users/user/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2032
    } else if (ASR::is_a<ASR::Function_t>(*t)) {
  File "/Users/user/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2022
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/user/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1979
    this->visit_stmt(*m_body[i]);
  File "/Users/user/lpython/src/lpython/python_ast.h", line 1862
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/user/lpython/src/lpython/python_ast.h", line 1753
    case stmtType::Expr: { v.visit_Expr((const Expr_t &)x); return; }
  File "/Users/user/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2837
    visit_expr(*c->m_args[i]);
  File "/Users/user/lpython/src/lpython/python_ast.h", line 1889
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/Users/user/lpython/src/lpython/python_ast.h", line 1791
    case exprType::Subscript: { v.visit_Subscript((const Subscript_t &)x); return; }
  File "/Users/user/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1510
    ASR::symbol_t *s = ASR::down_cast<ASR::Var_t>(value)->m_v;
  File "/Users/user/lpython/src/libasr/asr.h", line 40
    LFORTRAN_ASSERT(is_a<T>(*f));
AssertFailed: is_a<T>(*f)
```
