### ISSUE TITLE
Unsupported type annotation: list

### ISSUE THREAD

**Issue by Aasthaengg** [lcompilers/lpython#455]
I have implemented functions for `math.py` which work when running with `PYTHONPATH=src/runtime/ltypes python3 src/runtime/math.py` but give `Unsupported type annotation: list` when running with `./src/bin/lpython src/runtime/math.py -o output && ./output`. 

Here's the sample `fsum()` function implementation. 

```
def fsum(data: list) -> f64:
    """
    Sum of the elements of `data`.
    """
    sum: f64
    sum = 0.0

    i: i32
    for i in range(len(data)):
        sum += data[i]
    return sum
```

**Comment by certik** [comment]
Thanks for reporting this. Let's fix that.

**Comment by namannimmo10** [comment]
Yes, we need to add `list` as a supported type annotation, so that we can create an empty list like this:
```console
(lp) namannimmo@srf lpython % cat t.py
def main():
  l: list
  l = []
  print(l)

main()

(lp) namannimmo@srf lpython % lpython t.py
semantic error: Unsupported type annotation: list
 --> t.py:2:3
  |
2 |   l: list
  |   ^^^^^^^ 

(lp) namannimmo@srf lpython % python t.py
[]
```

**Comment by namannimmo10** [comment]
In your implementation of `fsum`, `list[f64]` can be used.

**Comment by Smit-create** [comment]
> Yes, we need to add `list` as a supported type annotation, so that we can create an empty list like this:

I don't think that's appropriate. In LPython we have everything with strict type notation. And just adding `list` annotation for creating an empty list does not seem to be useful since that won't have any lifeline in code as it won't perform any operations (neither we support `list` to `list[anytype]` conversion).

**Comment by czgdp1807** [comment]
@Aasthaengg Have you tried using `list[f64]` instead of just `list`? What's the output of that?

**Comment by certik** [comment]
Yes, `list` must specify the type of the elements, such as `list[i32]`, or `list[list[f64]]`. Just `list` could be a shortcut for `list[any]`, for a runtime dynamic type (each element a different type), but I would tackle this much later, if at all, for now let's focus on static types.

**Comment by Aasthaengg** [comment]
@czgdp1807 I still get `semantic error: Unsupported type annotation: list` when I make the argument as `list[f64]`

Here's the modified snippet - 
```
def fsum(data: list[f64]) -> f64:
    """
    Sum of the elements of `data`.
    """
    sum: f64
    sum = 0.0

    i: i32
    for i in range(len(data)):
        sum += data[i]
    return sum
```

**Comment by Smit-create** [comment]
> I still get `semantic error: Unsupported type annotation: list` when I make the argument as `list[f64]`

Please check again on the latest `main` branch. This was fixed in #493

**Comment by Aasthaengg** [comment]
> > I still get `semantic error: Unsupported type annotation: list` when I make the argument as `list[f64]`
> 
> Please check again on the latest `main` branch. This was fixed in #493

Alright, rebuilding it now.

**Comment by Aasthaengg** [comment]
> > I still get `semantic error: Unsupported type annotation: list` when I make the argument as `list[f64]`
> 
> Please check again on the latest `main` branch. This was fixed in #493

Internal Compiler Error: Unhandled exception
BFD: DWARF error: section .debug_info is larger than its filesize! (0x5b4757 vs 0x429c68)
BFD: DWARF error: section .debug_info is larger than its filesize! (0x5b4757 vs 0x429c68)
Traceback (most recent call last):
  Binary file "/home/kn1ght/lpython/lpython_personal/src/bin/lpython", in _start()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_start_main()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_init_first()
  File "/home/kn1ght/lpython/lpython_personal/src/bin/lpython.cpp", line 833, in ??
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir, compiler_options, time_report);
  File "/home/kn1ght/lpython/lpython_personal/src/bin/lpython.cpp", line 332, in ??
    res = fe.get_llvm3(*asr, diagnostics);
  File "/home/kn1ght/lpython/lpython_personal/src/lpython/python_evaluator.cpp", line 57, in LFortran::PythonCompiler::get_llvm3(LFortran::ASR::TranslationUnit_t&, LFortran::diag::Diagnostics&)
    run_fn);
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/codegen/asr_to_llvm.cpp", line 4549, in LFortran::asr_to_llvm(LFortran::ASR::TranslationUnit_t&, LFortran::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LFortran::Platform, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/../libasr/asr.h", line 3016, in LFortran::ASR::BaseVisitor<LFortran::ASRToLLVMVisitor>::visit_asr(LFortran::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/../libasr/asr.h", line 2994, in ??
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/../libasr/asr.h", line 3017, in LFortran::ASR::BaseVisitor<LFortran::ASRToLLVMVisitor>::visit_unit(LFortran::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/../libasr/asr.h", line 2824, in ??
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/codegen/asr_to_llvm.cpp", line 983, in LFortran::ASRToLLVMVisitor::visit_TranslationUnit(LFortran::ASR::TranslationUnit_t const&)
    visit_Function(*ASR::down_cast<ASR::Function_t>(item.second));
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/codegen/asr_to_llvm.cpp", line 2102, in LFortran::ASRToLLVMVisitor::visit_Function(LFortran::ASR::Function_t const&)
    instantiate_function(x);
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/codegen/asr_to_llvm.cpp", line 2203, in LFortran::ASRToLLVMVisitor::instantiate_function(LFortran::ASR::Function_t const&)
    llvm::FunctionType* function_type = get_function_type(x);
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/codegen/asr_to_llvm.cpp", line 2306, in LFortran::ASRToLLVMVisitor::get_function_type(LFortran::ASR::Function_t const&)
    std::vector<llvm::Type*> args = convert_args(x);
AssertFailed: false

**Comment by Aasthaengg** [comment]
> > I still get `semantic error: Unsupported type annotation: list` when I make the argument as `list[f64]`
> 
> Please check again on the latest `main` branch. This was fixed in #493

```
Internal Compiler Error: Unhandled exception
BFD: DWARF error: section .debug_info is larger than its filesize! (0x5b4757 vs 0x429c68)
BFD: DWARF error: section .debug_info is larger than its filesize! (0x5b4757 vs 0x429c68)
Traceback (most recent call last):
  Binary file "/home/kn1ght/lpython/lpython_personal/src/bin/lpython", in _start()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_start_main()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_init_first()
  File "/home/kn1ght/lpython/lpython_personal/src/bin/lpython.cpp", line 833, in ??
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir, compiler_options, time_report);
  File "/home/kn1ght/lpython/lpython_personal/src/bin/lpython.cpp", line 332, in ??
    res = fe.get_llvm3(*asr, diagnostics);
  File "/home/kn1ght/lpython/lpython_personal/src/lpython/python_evaluator.cpp", line 57, in LFortran::PythonCompiler::get_llvm3(LFortran::ASR::TranslationUnit_t&, LFortran::diag::Diagnostics&)
    run_fn);
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/codegen/asr_to_llvm.cpp", line 4549, in LFortran::asr_to_llvm(LFortran::ASR::TranslationUnit_t&, LFortran::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LFortran::Platform, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/../libasr/asr.h", line 3016, in LFortran::ASR::BaseVisitor<LFortran::ASRToLLVMVisitor>::visit_asr(LFortran::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/../libasr/asr.h", line 2994, in ??
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/../libasr/asr.h", line 3017, in LFortran::ASR::BaseVisitor<LFortran::ASRToLLVMVisitor>::visit_unit(LFortran::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/../libasr/asr.h", line 2824, in ??
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/codegen/asr_to_llvm.cpp", line 983, in LFortran::ASRToLLVMVisitor::visit_TranslationUnit(LFortran::ASR::TranslationUnit_t const&)
    visit_Function(*ASR::down_cast<ASR::Function_t>(item.second));
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/codegen/asr_to_llvm.cpp", line 2102, in LFortran::ASRToLLVMVisitor::visit_Function(LFortran::ASR::Function_t const&)
    instantiate_function(x);
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/codegen/asr_to_llvm.cpp", line 2203, in LFortran::ASRToLLVMVisitor::instantiate_function(LFortran::ASR::Function_t const&)
    llvm::FunctionType* function_type = get_function_type(x);
  File "/home/kn1ght/lpython/lpython_personal/src/libasr/codegen/asr_to_llvm.cpp", line 2306, in LFortran::ASRToLLVMVisitor::get_function_type(LFortran::ASR::Function_t const&)
    std::vector<llvm::Type*> args = convert_args(x);
AssertFailed: false
```

**Comment by Smit-create** [comment]
Ah, I was talking just about `--show-asr`. LLVM backend doesn't support the `list` yet.

**Comment by certik** [comment]
Thanks @Smit-create for fixing it. This now works for `lpython --show-asr`:
```python
def fsum(data: list[f64]) -> f64:
    """
    Sum of the elements of `data`.
    """
    sum: f64
    sum = 0.0

    i: i32
    for i in range(len(data)):
        sum += data[i]
    return sum

x: list[f64] = [1.0]
x.append(4.0)
print(fsum(x))
```
We now have to get it working for `lpython --show-llvm`.
