### ISSUE TITLE
Casting string to int type in Lpython

### ISSUE THREAD

**Issue by faze-geek** [lcompilers/lpython#582]
Does Lpython have a separate implementation of string to integer in any of the builtin.py files ? It seems to support this but is only paritally correct. 
```
print(int('10'))
(lp) anurag-3:lpython user$ python try.py
10
(lp) anurag-3:lpython user$ ./src/bin/lpython try.py
(lp) anurag-3:lpython user$ ./a.out
10
```

```
print(int('abc'))
(lp) anurag-3:lpython user$ python try.py
Traceback (most recent call last):
  File "/Users/user/lpython/try.py", line 2, in <module>
    print(int('abc'))
ValueError: invalid literal for int() with base 10: 'abc'
(lp) anurag-3:lpython user$ ./src/bin/lpython try.py
(lp) anurag-3:lpython user$ ./a.out
0    # Deserves a sematic error I guess !
```

**Comment by namannimmo10** [comment]
Thanks for opening an issue.

`'abc'` is a compile-time (constant value) and we handle this here:

https://github.com/lcompilers/lpython/blob/000194e93e804b73db8fbd05a9a6731d961344e7/src/lpython/semantics/python_ast_to_asr.cpp#L3040-L3047

Now we could use `std::stoi()` instead of `std::atoi()`, but that will give an `Unknown Exception`.

**Comment by namannimmo10** [comment]
OK, I see one way out:
```diff
(lp) namannimmo@srf lpython % gd
diff --git a/src/lpython/semantics/python_ast_to_asr.cpp b/src/lpython/semantics/python_ast_to_asr.cpp
index f2d498163..8cb9a74cb 100644
--- a/src/lpython/semantics/python_ast_to_asr.cpp
+++ b/src/lpython/semantics/python_ast_to_asr.cpp
@@ -3041,8 +3041,14 @@ public:
             if (ASRUtils::expr_value(arg) != nullptr) {
                 char *c = ASR::down_cast<ASR::StringConstant_t>(
                                     ASRUtils::expr_value(arg))->m_s;
+                int ival = 0;
+                try {
+                    ival = std::stoi(c);
+                } catch (...) {
+                    throw SemanticError("invalid literal for int() with base 10: '"+ std::string(c) + "'", arg->base.loc);
+                }
                 return (ASR::asr_t *)ASR::down_cast<ASR::expr_t>(ASR::make_IntegerConstant_t(al,
-                                loc, std::atoi(c), to_type));
+                                loc, ival, to_type));
             }
             // TODO: make int() work for non-constant strings
         } else if (ASRUtils::is_logical(*type)) {
```

**Comment by namannimmo10** [comment]
Yeah, I guess this works:
```console
(lp) namannimmo@srf lpython % cat t.py
def main():
  print(int("abc"))

main()
(lp) namannimmo@srf lpython % lpython t.py && ./a.out 
semantic error: invalid literal for int() with base 10: 'abc'
 --> t.py:2:13
  |
2 |   print(int("abc"))
  |             ^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
(lp) namannimmo@srf lpython % python t.py
Traceback (most recent call last):
  File "/Users/namannimmo/Applications/oss/lpython/t.py", line 4, in <module>
    main()
  File "/Users/namannimmo/Applications/oss/lpython/t.py", line 2, in main
    print(int("abc"))
ValueError: invalid literal for int() with base 10: 'abc'
```

**Comment by namannimmo10** [comment]
@faze-geek -- if you want, you can go ahead and submit a PR. Thanks.

**Comment by faze-geek** [comment]
> Yeah, I guess this works:
> 
Thanks for the response !
Okay, I'll test the changes locally and then attempt a pull request soon .

**Comment by faze-geek** [comment]
> Thanks for the response ! Okay, I'll test the changes locally and then attempt a pull request soon .

@namannimmo10 
Just using `std::stoi()` wouldnt handle edge cases like `int("3.14")` or `int("3abc")` , so I added a switch case routine to check for `"." ` and characters not in range `['0' ,'9']`. Could you look into it ? Also I havent added tests as of now . What would be a suitable location to add relevant tests for the changes .
