### ISSUE TITLE
run_tests.py fail on new Mac M1 Max laptop

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#627]
I pulled a fresh copy of "main" branch and got the following errors

```
(lp) (belex-venv) ┌─(~/Documents/GitHub/LCompilers/lpython)───────────────────────────────────────────────────────────────────────────────────────────(brian@Golf37:s004)─┐
└─(22:19:27 on main ✭)──> ./run_tests.py                                                                                            127 ↵ ──(Sat,Jun18)─┘
TEST: doconcurrentloop_01.py
    * ast    The JSON metadata differs against reference results
Reference JSON: tests/reference/ast-doconcurrentloop_01-ed7017b.json
Output JSON:    tests/output/ast-doconcurrentloop_01-ed7017b.json
Omitting 6 identical items
Differing items:
{'stdout_hash': None} != {'stdout_hash': '9bb84ccfc923d9d994d354fe887fd916995a7ac27eccf37cab76c2fd'}
{'stderr_hash': 'ce57975ab1feac6fd1c4f57e01aa528e56eceef5f05e9da33c0e01b4'} != {'stderr_hash': None}
{'returncode': 1} != {'returncode': 0}
{'stderr': 'ast-doconcurrentloop_01-ed7017b.stderr'} != {'stderr': None}
{'stdout': None} != {'stdout': 'ast-doconcurrentloop_01-ed7017b.stdout'}
No reference stderr output exists. Stderr:
Traceback (most recent call last):
  File "$DIR/src/bin/../runtime/lpython_parser.py", line 6, in <module>
    filename_out = sys.argv[2]
IndexError: list index out of range
The command 'python $DIR/src/bin/../runtime/lpython_parser.py tests/doconcurrentloop_01.py' failed.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/brian/Dropbox/Mac/Documents/LCompilers/lpython/src/bin/lpython.cpp", line 752
  File "/Users/brian/Dropbox/Mac/Documents/LCompilers/lpython/src/bin/lpython.cpp", line 132
AssertFailed: diagnostics.has_error()
Traceback (most recent call last):
  File "/Users/brian/Dropbox/Mac/Documents/GitHub/LCompilers/lpython/./run_tests.py", line 107, in <module>
    main()
  File "/Users/brian/Dropbox/Mac/Documents/GitHub/LCompilers/lpython/./run_tests.py", line 65, in main
    run_test("ast", "lpython --show-ast --no-color {infile} -o {outfile}",
  File "/Users/brian/Dropbox/Mac/Documents/GitHub/LCompilers/lpython/compiler_tester/tester.py", line 273, in run_test
    raise RunException("The reference result differs")
compiler_tester.tester.RunException: The reference result differs
```

**Comment by rebcabin** [comment]
I corrected a build error. No Issue
