### ISSUE TITLE
Enable function to be called from another function

### ISSUE THREAD

**Issue by Smit-create** [lcompilers/lpython#78]
Reference code:
```py
def test(a:i32, b:i32):
    return a**b

def check():
    a: i32
    a = test(2, 2)
```

<details>
<summary> AST </summary>
<p>

```bash
(Module [
   (FunctionDef 
      test 
      ([] [
         (
            a 
            (Name 
               i32 
               Load) ()) 
         (
            b 
            (Name 
               i32 
               Load) ())] [] [] [] [] []) [
      (Return 
         (BinOp 
            (Name 
               a 
               Load) 
            Pow 
            (Name 
               b 
               Load)))] [] () ()) 
   (FunctionDef 
      check 
      ([] [] [] [] [] [] []) [
      (AnnAssign 
         (Name 
            a 
            Store) 
         (Name 
            i32 
            Load) () 1) 
      (Assign [
         (Name 
            a 
            Store)] 
         (Call 
            (Name 
               test 
               Load) [
            (ConstantInt 2 ()) 
            (ConstantInt 2 ())] []) ())] [] () ())] [])
```

</p>
</details>

<details>
<summary> ASR </summary>
<p>

```bash
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/admin-pc/Smitlunagariya/lpython/src/bin/lpython", in _start()
  File "/build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c", line 310, in __libc_start_main()
  File "/home/admin-pc/Smitlunagariya/lpython/src/bin/lpython.cpp", line 1485, in main()
    with_intrinsic_modules, compiler_options);
  File "/home/admin-pc/Smitlunagariya/lpython/src/bin/lpython.cpp", line 561, in emit_asr()
    r = LFortran::Python::python_ast_to_asr(al, *ast, diagnostics);
  File "/home/admin-pc/Smitlunagariya/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1664, in LFortran::Python::python_ast_to_asr(Allocator&, LFortran::Python::AST::ast_t&, LFortran::diag::Diagnostics&)
    auto res2 = body_visitor(al, *ast_m, diagnostics, unit);
  File "/home/admin-pc/Smitlunagariya/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1620, in LFortran::Python::body_visitor(Allocator&, LFortran::Python::AST::Module_t const&, LFortran::diag::Diagnostics&, LFortran::ASR::asr_t*)
    b.visit_Module(ast);
  File "/home/admin-pc/Smitlunagariya/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 397, in LFortran::Python::BodyVisitor::visit_Module(LFortran::Python::AST::Module_t const&)
    visit_stmt(*x.m_body[i]);
  File "/home/admin-pc/Smitlunagariya/lpython/src/libasr/../lpython/python_ast.h", line 1827, in LFortran::Python::AST::BaseVisitor<LFortran::Python::BodyVisitor>::visit_stmt(LFortran::Python::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/admin-pc/Smitlunagariya/lpython/src/libasr/../lpython/python_ast.h", line 1698, in visit_stmt_t<LFortran::Python::BodyVisitor>()
    case stmtType::FunctionDef: { v.visit_FunctionDef((const FunctionDef_t &)x); return; }
  File "/home/admin-pc/Smitlunagariya/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 422, in LFortran::Python::BodyVisitor::visit_FunctionDef(LFortran::Python::AST::FunctionDef_t const&)
    handle_fn(x, *ASR::down_cast<ASR::Subroutine_t>(t));
  File "/home/admin-pc/Smitlunagariya/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 413, in void LFortran::Python::BodyVisitor::handle_fn<LFortran::ASR::Subroutine_t>(LFortran::Python::AST::FunctionDef_t const&, LFortran::ASR::Subroutine_t&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/admin-pc/Smitlunagariya/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 377, in LFortran::Python::BodyVisitor::transform_stmts(LFortran::Vec<LFortran::ASR::stmt_t*>&, unsigned long, LFortran::Python::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/admin-pc/Smitlunagariya/lpython/src/libasr/../lpython/python_ast.h", line 1827, in LFortran::Python::AST::BaseVisitor<LFortran::Python::BodyVisitor>::visit_stmt(LFortran::Python::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/admin-pc/Smitlunagariya/lpython/src/libasr/../lpython/python_ast.h", line 1701, in visit_stmt_t<LFortran::Python::BodyVisitor>()
    case stmtType::Return: { v.visit_Return((const Return_t &)x); return; }
AssertFailed: current_scope->scope.find(return_var_name) != current_scope->scope.end()
```

</p>
</details>

**Comment by Smit-create** [comment]
Oops, these work fine after we implement a function in ASR. Just forgot to specify the return type of `test` in the reference code above.

**Comment by certik** [comment]
Yes. And thanks for adding a nice error message. Once we have location information, the errors will look beautiful, and we'll make sure LPython gives excellent error messages.
