### ISSUE TITLE
[Old] Type comment Issue

### ISSUE THREAD

**Issue by Thirumalai-Shaktivel** [lcompilers/lpython#788]
```py
def _256Bit(NBitBase):  # type: ignore[misc]
    pass
```
Error:
```py
$ lpython --show-ast examples/expr2.py --tree
Traceback (most recent call last):
  File "/home/thirumalai/Open_Source/lpython/src/bin/../runtime/lpython_parser.py", line 110, in <module>
    a2 = v.visit(a)
  File "/home/thirumalai/conda_root/envs/lf/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/home/thirumalai/Open_Source/lpython/src/bin/../runtime/lpython_parser.py", line 77, in generic_visit
    new_list.append(self.visit(item))
  File "/home/thirumalai/conda_root/envs/lf/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/home/thirumalai/Open_Source/lpython/src/bin/../runtime/lpython_parser.py", line 100, in generic_visit
    new_node.first = linecol_to_pos(node.lineno, node.col_offset+1, newlines)
AttributeError: 'TypeIgnore' object has no attribute 'col_offset'
The command 'python /home/thirumalai/Open_Source/lpython/src/bin/../runtime/lpython_parser.py examples/expr2.py examples/expr2.py62D3531' failed.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/thirumalai/Open_Source/lpython/src/bin/lpython", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/thirumalai/Open_Source/lpython/src/bin/lpython.cpp", line 827, in ??
    return emit_ast(arg_file, runtime_library_dir, compiler_options);
AssertFailed: diagnostics.has_error()
```

**Comment by akshanshbhatt** [comment]
```py
$ python3.11 -m ast examples/expr2.py
Module(
   body=[
      FunctionDef(
         name='_256Bit',
         args=arguments(
            posonlyargs=[],
            args=[
               arg(arg='NBitBase')],
            kwonlyargs=[],
            kw_defaults=[],
            defaults=[]),
         body=[
            Pass()],
         decorator_list=[])],
   type_ignores=[
      TypeIgnore(lineno=1, tag='[misc]')])
```

It seems like we don't have support for serializing `type_ignores` in the old parser. In the new parser, too, we need to add support for `type_ignores`. They are different from `type-comments` because they can be used in any context (unlike type comments, which work on only specific contexts like `for-loops`, `function defs`, etc.). The native CPython AST module generates the `type_ignores` node by default for every program, even for an empty file -

```py
$ python3.11 -m ast examples/expr2.py
Module(body=[], type_ignores=[])
```
