### ISSUE TITLE
segfault in visit_AnnAssignUtil for `a: list[i32] = []`

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#859]
I want to test another benchmark (https://lemire.me/blog/2012/06/20/do-not-waste-time-with-stl-vectors/):
```python
from ltypes import i32

def test_list(n: i32) -> i32:
    a: list[i32] = []
    i: i32
    for i in range(n):
        a.append(i)
    sum: i32 = 0
    for i in range(n):
        sum += a[i]
    return sum

print(test_list(101))
```
Currently it fails with:
```console
$ lpython --new-parser b.py                                     
Traceback (most recent call last):
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 883
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir, lpython_pass_manager, compiler_options, time_report);
  File "/Users/ondrej/repos/lpython/src/bin/lpython.cpp", line 349
    r1 = LFortran::LPython::python_ast_to_asr(al, *ast, diagnostics, true,
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4169
    auto res2 = body_visitor(al, *ast_m, diagnostics, unit, main_module,
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4096
    b.visit_Module(ast);
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2432
    visit_stmt(*x.m_body[i]);
  File "/Users/ondrej/repos/lpython/src/lpython/python_ast.h", line 1882
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/ondrej/repos/lpython/src/lpython/python_ast.h", line 1750
    case stmtType::FunctionDef: { v.visit_FunctionDef((const FunctionDef_t &)x); return; }
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2461
    ASR::Function_t *f = ASR::down_cast<ASR::Function_t>(t);
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2450
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2407
    this->visit_stmt(*m_body[i]);
  File "/Users/ondrej/repos/lpython/src/lpython/python_ast.h", line 1882
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/ondrej/repos/lpython/src/lpython/python_ast.h", line 1756
    case stmtType::AugAssign: { v.visit_AugAssign((const AugAssign_t &)x); return; }
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2511
    visit_AnnAssignUtil(x, var_name);
  File "/Users/ondrej/repos/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 1339
    if (!ASRUtils::check_equal_type(type, ASRUtils::expr_type(value))) {
  File "/Users/ondrej/repos/lpython/src/libasr/asr_utils.h", line 1277
    y = ASR::down_cast<ASR::List_t>(y)->m_type;
  File "/Users/ondrej/repos/lpython/src/libasr/asr_utils.h", line 1270
    if( ASR::is_a<ASR::Pointer_t>(*x) ||
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803244e3
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by certik** [comment]
The issue is `a: list[i32] = []`.

**Comment by czgdp1807** [comment]
Ah! yes. A corner case. Will fix this. I think you can anyways work around it simply for now. Let me know if you can't, I will move it up in my priority list then.

**Comment by certik** [comment]
Yes, we worked around it like this: #860

**Comment by czgdp1807** [comment]
Cool. Will fix it later then.
