### ISSUE TITLE
`str` casting problems with bool, str

### ISSUE THREAD

**Issue by Abdelrahman-Kh-Fouad** [lcompilers/lpython#881]
Related to #797 , #856  
```bash 
$cat a.py
def f():
    f: bool
    f = True
    assert str(f) == "True"
    assert str(True) == "True"

f()
```
 with above example everything goes well.
but when we remove any statement that contains `if\else` some functions like `print` and located before `str(True)`, the error appear(the same one i posted on zulip):
```bash
$ cat a.py
def f():
    f: bool
    f = True
    assert str(True) == "True"
f()
```
or 

```bash
$ cat a.py
def f():
    f: bool
    f = True
    assert str(True) == "True"
    assert str(f) == "True"
f()
```

**Comment by Abdelrahman-Kh-Fouad** [comment]
error:
```bash
$ ./src/bin/lpython -o out a.py
BFD: DWARF error: section .debug_info is larger than its filesize! (0x5b4757 vs 0x429c68)
BFD: DWARF error: section .debug_info is larger than its filesize! (0x5b4757 vs 0x429c68)
BFD: DWARF error: section .debug_info is larger than its filesize! (0x5b4757 vs 0x429c68)
Traceback (most recent call last):
  Binary file "/home/abdelrahmankh/Gsoc/lpython/src/bin/lpython", in _start()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_start_main()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_init_first()
  File "/home/abdelrahmankh/Gsoc/lpython/src/bin/lpython.cpp", line 883, in ??
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir, lpython_pass_manager, compiler_options, time_report);
  File "/home/abdelrahmankh/Gsoc/lpython/src/bin/lpython.cpp", line 368, in ??
    res = fe.get_llvm3(*asr, pass_manager, diagnostics);
  File "/home/abdelrahmankh/Gsoc/lpython/src/lpython/python_evaluator.cpp", line 58, in LFortran::PythonCompiler::get_llvm3(LFortran::ASR::TranslationUnit_t&, LCompilers::PassManager&, LFortran::diag::Diagnostics&)
    run_fn);
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 5226, in LFortran::asr_to_llvm(LFortran::ASR::TranslationUnit_t&, LFortran::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LFortran::Platform, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, run_fn, false);
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/pass/pass_manager.h", line 239, in LCompilers::PassManager::apply_passes(Allocator&, LFortran::ASR::TranslationUnit_t*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)
    _apply_passes(al, asr, _passes, run_fun, always_run);
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/pass/pass_manager.h", line 100, in LCompilers::PassManager::_apply_passes(Allocator&, LFortran::ASR::TranslationUnit_t*, std::vector<LCompilers::ASRPass, std::allocator<LCompilers::ASRPass> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool)
    LFortran::pass_replace_array_op(al, *asr, LFortran::get_runtime_library_dir());
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/pass/array_op.cpp", line 819, in LFortran::pass_replace_array_op(Allocator&, LFortran::ASR::TranslationUnit_t&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_TranslationUnit(unit);
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/pass/array_op.cpp", line 167, in LFortran::ArrayOpVisitor::visit_TranslationUnit(LFortran::ASR::TranslationUnit_t const&)
    this->visit_symbol(*item.second);
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/../libasr/asr.h", line 3624, in LFortran::ASR::BaseVisitor<LFortran::ArrayOpVisitor>::visit_symbol(LFortran::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/../libasr/asr.h", line 3414, in ??
    case symbolType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/../libasr/pass/pass_utils.h", line 153, in LFortran::PassUtils::PassVisitor<LFortran::ArrayOpVisitor>::visit_Subroutine(LFortran::ASR::Subroutine_t const&)
    transform_stmts(xx.m_body, xx.n_body);
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/../libasr/pass/pass_utils.h", line 105, in LFortran::PassUtils::PassVisitor<LFortran::ArrayOpVisitor>::transform_stmts(LFortran::ASR::stmt_t**&, unsigned long&)
    self().visit_stmt(*m_body[i]);
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/../libasr/asr.h", line 3638, in LFortran::ASR::BaseVisitor<LFortran::ArrayOpVisitor>::visit_stmt(LFortran::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/../libasr/asr.h", line 3448, in ??
    case stmtType::Print: { v.visit_Print((const Print_t &)x); return; }
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/../libasr/asr.h", line 3948, in LFortran::ASR::BaseWalkVisitor<LFortran::ArrayOpVisitor>::visit_Print(LFortran::ASR::Print_t const&)
    self().visit_expr(*x.m_values[i]);
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/../libasr/asr.h", line 3680, in LFortran::ASR::BaseVisitor<LFortran::ArrayOpVisitor>::visit_expr(LFortran::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/../libasr/asr.h", line 3533, in ??
    case exprType::Cast: { v.visit_Cast((const Cast_t &)x); return; }
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/pass/array_op.cpp", line 353, in LFortran::ArrayOpVisitor::visit_Cast(LFortran::ASR::Cast_t const&)
    if( PassUtils::is_array(tmp_val) ) {
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/pass/pass_utils.cpp", line 155, in LFortran::PassUtils::is_array(LFortran::ASR::expr_t*)
    return get_rank(x) > 0;
  File "/home/abdelrahmankh/Gsoc/lpython/src/libasr/pass/pass_utils.cpp", line 141, in LFortran::PassUtils::get_rank(LFortran::ASR::expr_t*)
    if( x->type == ASR::exprType::Var ) {
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __sigaction()
Segfault: Signal SIGSEGV (segmentation fault) received
```

**Comment by Smit-create** [comment]
This seems to be fixed now. Does this work fine for you?

**Comment by Abdelrahman-Kh-Fouad** [comment]
> This seems to be fixed now. Does this work fine for you?

yes, it works with me.
