### ISSUE TITLE
Add printing support for list, tuple, set, and dict 

### ISSUE THREAD

**Issue by namannimmo10** [lcompilers/lpython#882]
```console
(lp) namannimmo@srf lpython % cat t.py
def f():
    l: list[str]
    l = ['a', 'b', 'c']
    print(l)


f()
(lp) namannimmo@srf lpython % lpython t.py && ./a.out 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/namannimmo/Applications/oss/lpython/src/bin/lpython.cpp", line 1081
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir, lpython_pass_manager, compiler_options, time_report);
  File "/Users/namannimmo/Applications/oss/lpython/src/bin/lpython.cpp", line 559
    res = fe.get_llvm3(*asr, pass_manager, diagnostics);
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/python_evaluator.cpp", line 57
    e->get_context(), al, lpm, compiler_options.platform,
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 5464
    v.nested_func_types = pass_find_nested_vars(asr, context,
  File "../libasr/asr.h", line 3691
  File "../libasr/asr.h", line 3669
  File "../libasr/asr.h", line 3692
  File "../libasr/asr.h", line 3470
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 1068
    visit_symbol(*item.second);
  File "../libasr/asr.h", line 3694
  File "../libasr/asr.h", line 3480
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 2414
    visit_procedures(x);
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 2488
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 3708
  File "../libasr/asr.h", line 3514
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 4569
    handle_print(x);
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 4735
    ASRUtils::type_to_str(t) + " type.");
LCompilersException: Printing support is not available for list type.
```

**Comment by redbopo** [comment]
I'd like to have a look if no one else is currently adding it.

**Comment by certik** [comment]
@redbopo go for it!

**Comment by czgdp1807** [comment]
@Smit-create I hope you will be able to work on `list`, `tuple` printing.

**Comment by Smit-create** [comment]
The printing of `list` and `tuple` is working now with LLVM and C backend.
