### ISSUE TITLE
Subroutine vs Function

### ISSUE THREAD

**Issue by Smit-create** [lcompilers/lpython#9]
In the current implementation of python ast to asr, `visit_FunctionDef` creates a subroutine(`make_Subroutine_t`)node as:
```cpp
tmp = ASR::make_Subroutine_t(
            al, x.base.base.loc,
            /* a_symtab */ current_scope,
            /* a_name */ s2c(al, sym_name),
            /* a_args */ args.p,
            /* n_args */ args.size(),
            /* a_body */ nullptr,
            /* n_body */ 0,
            current_procedure_abi_type,
            s_access, deftype, bindc_name,
            is_pure, is_module);
```

We can also verify that `Functiondef` node in AST is converted to `Subroutine` node in ASR from below reference code:

<details>
<summary> AST</summary>

<p>

```bash
(Module [
   (FunctionDef 
      check 
      ([] [] [] [] [] [] []) [
      (AnnAssign 
         (Name 
            r 
            Store) 
         (Name 
            i32 
            Load) () 1) 
      (Assign [
         (Name 
            r 
            Store)] 
         (ConstantInt 0 ()) ()) 
      (AugAssign 
         (Name 
            r 
            Store) 
         Add 
         (ConstantInt 4 ()))] [] () ())] [])
```
</p>
</details>

<details>
<summary> ASR</summary>

<p>

```bash
(TranslationUnit 
   (SymbolTable 
      1 
      {
         check: 
            (Subroutine 
               (SymbolTable 
                  2 
                  {
                     r: 
                        (Variable 
                           2 
                           r 
                           Local () () 
                           Default 
                           (Integer 4 []) 
                           Source 
                           Public 
                           Required .false.)
                  }) 
               check [] [
               (= 
                  (Var 2 r) (ConstantInteger 0 
                  (Integer 4 [])) ()) 
               (Assign 0 
                  )] 
               Source 
               Public 
               Implementation () .false. .false.)
      }) 
   [])
```
</p>
</details>

This also might be the reason for the failure of https://github.com/lcompilers/lpython/issues/2#issuecomment-1008287037. How should we handle this Function vs Subroutine?

Sorry if this is very trivial question, I didn't find much difference between them and so thought to discuss over here.

**Comment by Smit-create** [comment]
I think we can discuss this issue since I also found an example where this is necessary:

On the reference code:

```py
def test_pow_1(a: i32, b: i32) -> i32:
    res: i32
    res = pow(a, b)
    return res
```

<details>
<summary> AST </summary>
<p>

```bash
(Module [
   (FunctionDef 
      test_pow_1 
      ([] [
         (
            a 
            (Name 
               i32 
               Load) ()) 
         (
            b 
            (Name 
               i32 
               Load) ())] [] [] [] [] []) [
      (AnnAssign 
         (Name 
            res 
            Store) 
         (Name 
            i32 
            Load) () 1) 
      (Assign [
         (Name 
            res 
            Store)] 
         (Call 
            (Name 
               pow 
               Load) [
            (Name 
               a 
               Load) 
            (Name 
               b 
               Load)] []) ()) 
      (Return 
         (Name 
            res 
            Load))] [] 
      (Name 
         i32 
         Load) ())] [])
```
</p>
</details>

<details>
<summary> ASR </summary>
<p>

```bash
(TranslationUnit 
   (SymbolTable 
      1 
      {
         test_pow_1: 
            (Subroutine 
               (SymbolTable 
                  2 
                  {
                     a: 
                        (Variable 
                           2 
                           a 
                           In () () 
                           Default 
                           (Integer 4 []) 
                           Source 
                           Public 
                           Required .false.), 
                     b: 
                        (Variable 
                           2 
                           b 
                           In () () 
                           Default 
                           (Integer 4 []) 
                           Source 
                           Public 
                           Required .false.), 
                     res: 
                        (Variable 
                           2 
                           res 
                           Local () () 
                           Default 
                           (Integer 4 []) 
                           Source 
                           Public 
                           Required .false.)
                  }) 
               test_pow_1 [
               (Var 2 a) 
               (Var 2 b)] [
               (= 
                  (Var 2 res) 
                  (BinOp 
                     (Var 2 a) 
                     Pow 
                     (Var 2 b) 
                     (Integer 4 []) () ()) ()) 
               (Return)] 
               Source 
               Public 
               Implementation () .false. .false.)
      }) 
   [])
```
</p>
</details>

<details>
<summary> CPP </summary>
<p>

```cpp
#include <iostream>
#include <string>
#include <vector>
#include <Kokkos_Core.hpp>
#include <lfortran_intrinsics.h>

template <typename T>
Kokkos::View<T*> from_std_vector(const std::vector<T> &v)
{
    Kokkos::View<T*> r("r", v.size());
    for (size_t i=0; i < v.size(); i++) {
        r(i) = v[i];
    }
    return r;
}

void test_pow_1(int a, int b)
{
    int res;
    res = std::pow(a, b);
    return;
}

```
</p>
</details>


The bug seems to be highlighted in CPP generated code where we can see `void` return type instead of `int` for function `test_pow_1`. Probably using `Function_t` should be a fix for this instead of using `Subroutine_t` for python `FunctionDef`.

**Comment by certik** [comment]
I just implemented a simple workaround for the main() function. Otherwise every function becomes a subroutine (with no return value). We need to check the function signature and if the return type is other than None, it needs to create a Function in ASR, and then properly assign the result from `return res` by assigning to the return variable, as I have done for the `main()` function.

**Comment by Smit-create** [comment]
I am trying to work on creating Function in ASR using the following diff:
```diff
diff --git a/src/lpython/semantics/python_ast_to_asr.cpp b/src/lpython/semantics/python_ast_to_asr.cpp
index 25ad83a0..653bb035 100644
--- a/src/lpython/semantics/python_ast_to_asr.cpp
+++ b/src/lpython/semantics/python_ast_to_asr.cpp
@@ -236,11 +236,47 @@ public:
         bool is_pure = false, is_module = false;
         ASR::accessType s_access = ASR::accessType::Public;
         ASR::deftypeType deftype = ASR::deftypeType::Implementation;
-        char *bindc_name=nullptr;
+        char *bindc_name = nullptr;
+
+        if (x.m_returns) {
+
+            if (x.m_returns->type == AST::exprType::Name) {
+                std::string return_var_name = to_lower(((AST::Name_t*)(x.m_returns))->m_id);
+                visit_expr(*x.m_returns);
+                ASR::ttype_t *type = ASRUtils::TYPE(tmp);
+                ASR::asr_t *return_var = ASR::make_Variable_t(al, x.base.base.loc,
+                    current_scope, s2c(al, return_var_name), ASRUtils::intent_return_var, nullptr, nullptr,
+                    ASR::storage_typeType::Default, type,
+                    current_procedure_abi_type, ASR::Public, ASR::presenceType::Required,
+                    false);
+                LFORTRAN_ASSERT(current_scope->scope.find(return_var_name) == current_scope->scope.end())
+                current_scope->scope[return_var_name]
+                    = ASR::down_cast<ASR::symbol_t>(return_var);
+                ASR::asr_t *return_var_ref = ASR::make_Var_t(al, x.base.base.loc,
+                    ASR::down_cast<ASR::symbol_t>(return_var));
+
+                tmp = ASR::make_Function_t(
+                    al, x.base.base.loc,
+                    /* a_symtab */ current_scope,
+                    /* a_name */ s2c(al, sym_name),
+                    /* a_args */ args.p,
+                    /* n_args */ args.size(),
+                    /* a_body */ nullptr,
+                    /* n_body */ 0,
+                    /* a_return_var */ ASRUtils::EXPR(return_var_ref),
+                    current_procedure_abi_type,
+                    s_access, deftype, bindc_name);
+                return;
+
+            } else {
+                throw SemanticError("Return variable must be an identifier",
+                    x.m_returns->base.loc);
+            }
+        }
         if (sym_name == "main") {
             // Temporary solution for the main() function
             std::string return_var_name = "main_return_var";
-            ASR::ttype_t *type = LFortran::ASRUtils::TYPE(ASR::make_Integer_t(al, x.base.base.loc, 8, nullptr, 0));
+            ASR::ttype_t *type = ASRUtils::TYPE(ASR::make_Integer_t(al, x.base.base.loc, 8, nullptr, 0));
             ASR::asr_t *return_var = ASR::make_Variable_t(al, x.base.base.loc,
                 current_scope, s2c(al, return_var_name), ASRUtils::intent_return_var, nullptr, nullptr,
                 ASR::storage_typeType::Default, type,
@@ -279,6 +315,18 @@ public:
         parent_scope->scope[sym_name] = ASR::down_cast<ASR::symbol_t>(tmp);
         current_scope = parent_scope;
     }
+
+    void visit_Name(const AST::Name_t &x) {
+        std::string name = x.m_id;
+        ASR::symbol_t *s = current_scope->resolve_symbol(name);
+        if (s) {
+            tmp = ASR::make_Var_t(al, x.base.base.loc, s);
+        } else {
+            throw SemanticError("Variable '" + name + "' not declared",
+                x.base.base.loc);
+        }
+    }
+
 };

```

I get the following error:
Reference code:

```py
def test() -> i32:
    a : i32
    a = 0
    return a
```

Error:

```
Traceback (most recent call last):
  Binary file "/home/admin-pc/Smitlunagariya/lpython/inst/bin/lpython", in _start()
  File "/build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c", line 310, in __libc_start_main()
  File "/home/admin-pc/Smitlunagariya/lpython/src/bin/lpython.cpp", line 1474, in main()
    with_intrinsic_modules, compiler_options);
  File "/home/admin-pc/Smitlunagariya/lpython/src/bin/lpython.cpp", line 551, in emit_asr()
    std::cerr << diagnostics.render(input, lm, compiler_options);
  File "/home/admin-pc/Smitlunagariya/lpython/src/libasr/diagnostics.cpp", line 71, in LFortran::diag::Diagnostics::render(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LFortran::LocationManager const&, LFortran::CompilerOptions const&)
    out += render_diagnostic(d, input, lm,
  File "/home/admin-pc/Smitlunagariya/lpython/src/libasr/diagnostics.cpp", line 134, in LFortran::diag::render_diagnostic(LFortran::diag::Diagnostic&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LFortran::LocationManager const&, bool, bool)
    populate_spans(d, lm, input);
  File "/home/admin-pc/Smitlunagariya/lpython/src/libasr/diagnostics.cpp", line 121, in LFortran::diag::populate_spans(LFortran::diag::Diagnostic&, LFortran::LocationManager const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    populate_span(s, lm, input);
  File "/home/admin-pc/Smitlunagariya/lpython/src/libasr/diagnostics.cpp", line 105, in LFortran::diag::populate_span(LFortran::diag::Span&, LFortran::LocationManager const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    lm.pos_to_linecol(lm.output_to_input_pos(s.loc.first, false),
  File "/home/admin-pc/Smitlunagariya/lpython/src/libasr/../libasr/location.h", line 120, in LFortran::LocationManager::output_to_input_pos(unsigned int, bool) const
    uint32_t rel_pos = out_pos - out_start[interval];
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in killpg()
Segfault: Signal SIGSEGV (segmentation fault) received
```
Any suggestions for fixing this?

**Comment by certik** [comment]
Yes, the error comes from printing an error message. We have incorrect location information in AST (a known problem) and the error printing mechanism has some bug in it that doesn't work in that case. The error reporting should be fixed, but also we need to actually store location information in AST to print the error message. Otherwise things might work, the ast to asr code is simply reporting a compiler error message.

**Comment by certik** [comment]
Change
```
+            if (x.m_returns->type == AST::exprType::Name) {
```
to
```
+            if (AST::is_a<AST::Name_t>(*x.m_returns)) {
```

**Comment by certik** [comment]
Replace:
```
+                std::string return_var_name = to_lower(((AST::Name_t*)(x.m_returns))->m_id);
```
with:
```
+                std::string return_var_name = to_lower(AST::down_cast<AST::Name_t>(x.m_returns)->m_id);
```

**Comment by certik** [comment]
```
ASR::ttype_t * ast_expr_to_asr_type(x.m_returns.base.loc, *x.m_returns);
```
