### ISSUE TITLE
Allow returning tuples from functions

### ISSUE THREAD

**Issue by namannimmo10** [lcompilers/lpython#906]
```console
(lp) namannimmo@srf lpython % cat t.py
def add1(a: i32, b: i32) -> tuple[i32, i32]:
    return (a + 1, b + 1)

def f():
    i: i32 = 1
    j: i32 = 1
    (i, j) = add1(i, j)
    print(i)
    print(j)
    

f()
(lp) namannimmo@srf lpython % lpython t.py && ./a.out 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/namannimmo/Applications/oss/lpython/src/bin/lpython.cpp", line 1081
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir, lpython_pass_manager, compiler_options, time_report);
  File "/Users/namannimmo/Applications/oss/lpython/src/bin/lpython.cpp", line 559
    res = fe.get_llvm3(*asr, pass_manager, diagnostics);
  File "/Users/namannimmo/Applications/oss/lpython/src/lpython/python_evaluator.cpp", line 57
    e->get_context(), al, lpm, compiler_options.platform,
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 5466
    v.nested_func_types = pass_find_nested_vars(asr, context,
  File "../libasr/asr.h", line 3741
  File "../libasr/asr.h", line 3719
  File "../libasr/asr.h", line 3742
  File "../libasr/asr.h", line 3518
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 1044
    visit_Function(*ASR::down_cast<ASR::Function_t>(item.second));
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 2396
    llvm_goto_targets.clear();
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 2511
    } else {
  File "/Users/namannimmo/Applications/oss/lpython/src/libasr/codegen/asr_to_llvm.cpp", line 2615
    LFORTRAN_ASSERT(false);
AssertFailed: false
```

**Comment by czgdp1807** [comment]
@Smit-create Will you be able to work on this?
