### ISSUE TITLE
Larger hexadecimal number is not recognized by the new parser

### ISSUE THREAD

**Issue by Thirumalai-Shaktivel** [lcompilers/lpython#917]
Code:
```py
b = np.array([0x7ff0000000000001], 'i8').view('f8')
```
```console
$ lpython --show-ast examples/expr2.py --tree --new-parser
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/thirumalai/Open_Source/lpython/src/bin/lpython", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/thirumalai/Open_Source/lpython/src/bin/lpython.cpp", line 1008, in ??
    return emit_ast(arg_file, runtime_library_dir, compiler_options);
  File "/home/thirumalai/Open_Source/lpython/src/bin/lpython.cpp", line 114, in ??
    al, runtime_library_dir, infile, diagnostics, compiler_options.new_parser);
  File "/home/thirumalai/Open_Source/lpython/src/lpython/parser/parser.cpp", line 123, in LFortran::parse_python_file(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LFortran::diag::Diagnostics&, bool)
    Result<LPython::AST::Module_t*> res = parse(al, input, diagnostics);
  File "/home/thirumalai/Open_Source/lpython/src/lpython/parser/parser.cpp", line 22, in LFortran::parse(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LFortran::diag::Diagnostics&)
    p.parse(s);
  File "/home/thirumalai/Open_Source/lpython/src/lpython/parser/parser.cpp", line 54, in LFortran::Parser::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    if (yyparse(*this) == 0) {
  File "/home/thirumalai/Open_Source/lpython/src/lpython/parser.tab.cc", line 3021, in yyparse(LFortran::Parser&)
  File "/home/thirumalai/Open_Source/lpython/src/lpython/parser.yy", line 36, in yylex(LFortran::YYSTYPE*, LFortran::Location*, LFortran::Parser&)
  File "/home/thirumalai/Open_Source/lpython/src/lpython/tokenizer.re", line 456, in LFortran::Tokenizer::lex(Allocator&, LFortran::YYSTYPE&, LFortran::Location&, LFortran::diag::Diagnostics&)
  File "/home/thirumalai/Open_Source/lpython/src/lpython/tokenizer.re", line 83, in LFortran::lex_int(Allocator&, unsigned char const*, unsigned char const*, LFortran::BigInt::BigInt&, LFortran::Location const&)
AssertFailed: is_small_int(i)
```

**Comment by Thirumalai-Shaktivel** [comment]
Another example
```py
lpython --show-ast --new-parser ./numpy/random/tests/test_direct.py
tokenizer error: Integer too large to convert
   --> ./numpy/random/tests/test_direct.py:352:17
    |
352 |         step = -0x9e3779b97f4a7c150000000000000000
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

**Comment by certik** [comment]
I think this we can work on after we switch to the new parser.
