### ISSUE TITLE
Tuple Subscript issue in the AST->ASR

### ISSUE THREAD

**Issue by Thirumalai-Shaktivel** [lcompilers/lpython#924]
Code:
```py
from ltypes import i32, f64

def test():
    x: tuple[i32, f64] = (1, 1.0)

    i: i32
    for i in range(2):
        print(x[i])

test()
```
Error:
```console
$ lpython examples/expr2.py --new-parser; ./a.out
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/thirumalai/Open_Source/lpython/src/bin/lpython", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/thirumalai/Open_Source/lpython/src/bin/lpython.cpp", line 1081, in ??
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir, lpython_pass_manager, compiler_options, time_report);
  File "/home/thirumalai/Open_Source/lpython/src/bin/lpython.cpp", line 541, in ??
    compiler_options.disable_main, compiler_options.symtab_only, infile);
  File "/home/thirumalai/Open_Source/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4409, in LFortran::LPython::python_ast_to_asr(Allocator&, LFortran::LPython::AST::ast_t&, LFortran::diag::Diagnostics&, bool, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
    ast_overload);
  File "/home/thirumalai/Open_Source/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 4335, in LFortran::LPython::body_visitor(Allocator&, LFortran::LPython::AST::Module_t const&, LFortran::diag::Diagnostics&, LFortran::ASR::asr_t*, bool, std::map<int, LFortran::ASR::symbol_t*, std::less<int>, std::allocator<std::pair<int const, LFortran::ASR::symbol_t*> > >&)
    b.visit_Module(ast);
  File "/home/thirumalai/Open_Source/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2611, in LFortran::LPython::BodyVisitor::visit_Module(LFortran::LPython::AST::Module_t const&)
    visit_stmt(*x.m_body[i]);
  File "/home/thirumalai/Open_Source/lpython/src/lpython/python_ast.h", line 1882, in LFortran::LPython::AST::BaseVisitor<LFortran::LPython::BodyVisitor>::visit_stmt(LFortran::LPython::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/thirumalai/Open_Source/lpython/src/lpython/python_ast.h", line 1750, in ??
    case stmtType::FunctionDef: { v.visit_FunctionDef((const FunctionDef_t &)x); return; }
  File "/home/thirumalai/Open_Source/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2638, in LFortran::LPython::BodyVisitor::visit_FunctionDef(LFortran::LPython::AST::FunctionDef_t const&)
    handle_fn(x, *f);
  File "/home/thirumalai/Open_Source/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2628, in LFortran::LPython::BodyVisitor::handle_fn(LFortran::LPython::AST::FunctionDef_t const&, LFortran::ASR::Function_t&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/thirumalai/Open_Source/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2586, in LFortran::LPython::BodyVisitor::transform_stmts(LFortran::Vec<LFortran::ASR::stmt_t*>&, unsigned long, LFortran::LPython::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/thirumalai/Open_Source/lpython/src/lpython/python_ast.h", line 1882, in LFortran::LPython::AST::BaseVisitor<LFortran::LPython::BodyVisitor>::visit_stmt(LFortran::LPython::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/thirumalai/Open_Source/lpython/src/lpython/python_ast.h", line 1758, in ??
    case stmtType::For: { v.visit_For((const For_t &)x); return; }
  File "/home/thirumalai/Open_Source/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3023, in LFortran::LPython::BodyVisitor::visit_For(LFortran::LPython::AST::For_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/thirumalai/Open_Source/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2586, in LFortran::LPython::BodyVisitor::transform_stmts(LFortran::Vec<LFortran::ASR::stmt_t*>&, unsigned long, LFortran::LPython::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/thirumalai/Open_Source/lpython/src/lpython/python_ast.h", line 1882, in LFortran::LPython::AST::BaseVisitor<LFortran::LPython::BodyVisitor>::visit_stmt(LFortran::LPython::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/thirumalai/Open_Source/lpython/src/lpython/python_ast.h", line 1772, in ??
    case stmtType::Expr: { v.visit_Expr((const Expr_t &)x); return; }
  File "/home/thirumalai/Open_Source/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 3616, in LFortran::LPython::BodyVisitor::visit_Expr(LFortran::LPython::AST::Expr_t const&)
    visit_expr_list(c->m_args, c->n_args, args);
  File "/home/thirumalai/Open_Source/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 466, in LFortran::LPython::CommonVisitor<LFortran::LPython::BodyVisitor>::visit_expr_list(LFortran::LPython::AST::expr_t**, unsigned long, LFortran::Vec<LFortran::ASR::call_arg_t>&)
    this->visit_expr(*exprs[i]);
  File "/home/thirumalai/Open_Source/lpython/src/lpython/python_ast.h", line 1909, in LFortran::LPython::AST::BaseVisitor<LFortran::LPython::BodyVisitor>::visit_expr(LFortran::LPython::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/thirumalai/Open_Source/lpython/src/lpython/python_ast.h", line 1811, in ??
    case exprType::Subscript: { v.visit_Subscript((const Subscript_t &)x); return; }
  File "/home/thirumalai/Open_Source/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2080, in LFortran::LPython::CommonVisitor<LFortran::LPython::BodyVisitor>::visit_Subscript(LFortran::LPython::AST::Subscript_t const&)
    if( !visit_SubscriptIndices(x.m_slice, args, value, type,
  File "/home/thirumalai/Open_Source/lpython/src/lpython/semantics/python_ast_to_asr.cpp", line 2049, in LFortran::LPython::CommonVisitor<LFortran::LPython::BodyVisitor>::visit_SubscriptIndices(LFortran::LPython::AST::expr_t*, LFortran::Vec<LFortran::ASR::array_index_t>&, LFortran::ASR::expr_t*, LFortran::ASR::ttype_t*, bool&, LFortran::Location const&)
    int i = ASR::down_cast<ASR::IntegerConstant_t>(ASRUtils::EXPR(tmp))->m_n;
AssertFailed: is_a<T>(*f)
```

**Comment by Thirumalai-Shaktivel** [comment]
I got couple questions on `Tuple`:
```py
lpython examples/expr2.py --new-parser; ./a.out
semantic error: Type mismatch in annotation-assignment, the types must be compatible
 --> examples/expr2.py:4:5
  |
4 |     x: tuple[i32] = (1, 2, 3)
  |     ^               ^^^^^^^^^ type mismatch ('tuple[i32]' and 'tuple[i32, i32, i32]')
```
* Why the above Error asks to replace `tuple[i32]` to `tuple[i32, i32, i32]`, would that be an optimal solution?

* Is this [Tuple Subscript issue](https://github.com/lcompilers/lpython/issues/924#top) valid with respect to LPython design?

* Any specific reason for not adding `TupleSection` node in the `ASR.asdl`?

cc @certik @czgdp1807 @Smit-create @namannimmo10

**Comment by Smit-create** [comment]
Currently, the ASR node are constructed as:
```
    | ListItem(expr a, expr pos, ttype type, expr? value)
    | TupleItem(expr a, expr pos, ttype type, expr? value)
```
The only use of type here during reading is to check the struct type:
```cpp
tmp = tuple_api->read_item(ptuple, pos, LLVM::is_llvm_struct(x.m_type));
```
With the tuple, we have difficulty detecting the i-th type during runtime when the index is a variable.

**Comment by czgdp1807** [comment]
I think passing non-constant indices to a tuple is impossible. Because each element of a tuple can be of different type so even building the ```TupleItem``` node in ASR is not possible with runtime indices for accessing elements of a tuple.
